import os

def update_env():
    file_path = ".env.example"
    with open(file_path, "r") as f:
        content = f.read()

    env_insertion = """
# Local Maintenance Settings
LOCAL_MAINTENANCE_ENABLED=true
DEFAULT_LOCAL_MAINTENANCE_PROFILE=balanced_local_maintenance
LOCAL_MAINTENANCE_DEFAULT_LANGUAGE=tr
LOCAL_MAINTENANCE_DRY_RUN_DEFAULT=true
LOCAL_MAINTENANCE_ALLOW_PRODUCTION_SCHEDULER=false
LOCAL_MAINTENANCE_ALLOW_BACKGROUND_DAEMON=false
LOCAL_MAINTENANCE_ALLOW_AUTO_UPGRADE=false
LOCAL_MAINTENANCE_ALLOW_AUTO_FIX=false
LOCAL_MAINTENANCE_ALLOW_FILE_MODIFICATION=false
LOCAL_MAINTENANCE_ALLOW_FILE_DELETION=false
LOCAL_MAINTENANCE_ALLOW_OVERWRITE=false
LOCAL_MAINTENANCE_ALLOW_CLOUD_UPLOAD=false
LOCAL_MAINTENANCE_ALLOW_EXTERNAL_SERVICE=false
LOCAL_MAINTENANCE_ALLOW_EXTERNAL_LLM=false
LOCAL_MAINTENANCE_ALLOW_LIVE_COMMANDS=false
LOCAL_MAINTENANCE_ALLOW_BROKER_COMMANDS=false
LOCAL_MAINTENANCE_ALLOW_DEPLOY_COMMANDS=false
LOCAL_MAINTENANCE_ALLOW_REAL_MARKET_DOWNLOAD=false
LOCAL_MAINTENANCE_SCAN_DOCS=true
LOCAL_MAINTENANCE_SCAN_TESTS=true
LOCAL_MAINTENANCE_SCAN_SCRIPTS=true
LOCAL_MAINTENANCE_SCAN_REPORTS=true
LOCAL_MAINTENANCE_SCAN_DATA_LAKE=true
LOCAL_MAINTENANCE_SCAN_CONFIGS=true
LOCAL_MAINTENANCE_SCAN_REQUIREMENTS=true
LOCAL_MAINTENANCE_SCAN_CROSS_LAYER_OUTPUTS=true
LOCAL_MAINTENANCE_DEFAULT_MONTHLY_REVIEW_DAY=1
LOCAL_MAINTENANCE_DEFAULT_QUARTERLY_REVIEW_MONTH_INTERVAL=3
LOCAL_MAINTENANCE_STALE_REPORT_DAYS_WARNING=45
LOCAL_MAINTENANCE_STALE_DOC_DAYS_WARNING=90
LOCAL_MAINTENANCE_STALE_TEST_DAYS_WARNING=90
LOCAL_MAINTENANCE_DEPENDENCY_AGE_DAYS_WARNING=180
LOCAL_MAINTENANCE_MAX_CHECKS=300000
LOCAL_MAINTENANCE_MIN_SUSTAINABILITY_SCORE=0.40
LOCAL_MAINTENANCE_MIN_QUALITY_SCORE=0.40
LOCAL_MAINTENANCE_SAVE_REPORTS=true
"""
    if "LOCAL_MAINTENANCE_ENABLED" not in content:
        with open(file_path, "a") as f:
            f.write(env_insertion)

update_env()
