import os
def update_architecture():
    file_path = "docs/ARCHITECTURE.md"
    if not os.path.exists(file_path):
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write("# Architecture\n\n")

    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    arch_insertion = """
## Local Maintenance Data Flow

Docs / Tests / Scripts / Reports / DataLake / Config / Requirements / Security / Backup / Packaging / Evidence / Metadata / Graph / Timeline / Consistency / Readiness
-> MaintenanceDomainRegistry
-> MaintenanceTaskRegistry
-> PeriodicReviewCalendar
-> RefreshCadence
-> DependencyAgingWatch
-> DependencyReviewChecklist
-> StaleArtifactWatch
-> StaleReportWatch
-> StaleDocumentationWatch
-> StaleTestWatch
-> ManualReviewQueue
-> MaintenanceGapRegister
-> MaintenanceRiskSummary
-> SustainabilityScoring
-> OperatorPeriodicReviewChecklist
-> ReviewTemplates
-> RefreshCommandPlan
-> MaintenanceRunbook
-> LongTermSustainabilityBinder
-> MaintenanceValidation
-> MaintenanceQuality
-> Local Maintenance Outputs
"""
    if "## Local Maintenance Data Flow" not in content:
        with open(file_path, "a", encoding="utf-8") as f:
            f.write(arch_insertion)

def update_phase_log():
    file_path = "docs/PHASE_LOG.md"
    if not os.path.exists(file_path):
        with open(file_path, "w", encoding="utf-8") as f:
            f.write("# Phase Log\n\n")

    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    phase_insertion = """
## Phase 70: Local Long-Term Maintenance Planner
- Local maintenance profile sistemi eklendi.
- Maintenance label registry eklendi.
- MaintenanceDomain, MaintenanceTask, DependencyWatchItem, MaintenanceFinding ve MaintenanceBinder modelleri eklendi.
- Maintenance domain registry eklendi.
- Maintenance task registry eklendi.
- Periodic review calendar eklendi.
- Refresh cadence registries eklendi.
- Dependency aging watch eklendi.
- Dependency review checklist eklendi.
- Deprecated/stale artifact watch raporları eklendi.
- Stale report/doc/test watch raporları eklendi.
- Manual review queue eklendi.
- Maintenance gap register eklendi.
- Maintenance risk summary eklendi.
- Sustainability score report eklendi.
- Operator periodic review checklist eklendi.
- Monthly/quarterly review templates eklendi.
- Refresh command plan eklendi.
- Maintenance runbook eklendi.
- Long-term sustainability binder eklendi.
- Maintenance validation ve quality report eklendi.
- LocalMaintenancePipeline eklendi.
- DataLake local maintenance kayıt desteği aldı.
- Local maintenance scriptleri eklendi.
- Testler genişletildi.
"""
    if "## Phase 70" not in content:
        with open(file_path, "a", encoding="utf-8") as f:
            f.write(phase_insertion)

def update_guides():
    guides = [
        "docs/OPERATOR_MANUAL.md",
        "docs/ANALYST_HANDBOOK.md",
        "docs/CODEX_AGENT_GUIDE.md",
        "docs/SAFE_USAGE_GUIDE.md",
        "docs/INSTALLATION.md",
        "docs/CONFIGURATION.md"
    ]

    guide_insertion = """
## Local Maintenance Overview

The local maintenance module is available to help evaluate project sustainability.

- **Maintenance domain registry:** Lists all managed parts of the offline infrastructure.
- **Periodic review calendar:** Gives manual hints for reviewing outputs. It is **NOT** a scheduler.
- **Refresh cadence:** Recommended manual refresh schedules.
- **Dependency aging watch:** Local-only scan (no internet connection) for missing metadata and stale files. Does **NOT** auto-upgrade.
- **Manual review queue:** Summarizes tasks and artifacts that require human review.
- **Sustainability score:** A local metric for project health. It is **NOT** an official SLA.
- **Maintenance runbook:** Documentation on how to operate offline checks, **NOT** automatic operations.
- **DISCLAIMER:** No live orders, no broker executions, no deployment scripts, no auto-upgrades, no cloud uploads, and absolutely no investment advice is generated by this module.
"""
    for guide in guides:
        if not os.path.exists(guide):
            os.makedirs(os.path.dirname(guide), exist_ok=True)
            with open(guide, "w", encoding="utf-8") as f:
                f.write(f"# {os.path.basename(guide).split('.')[0]}\n\n")

        with open(guide, "r", encoding="utf-8") as f:
            content = f.read()

        if "## Local Maintenance Overview" not in content:
            with open(guide, "a", encoding="utf-8") as f:
                f.write(guide_insertion)

update_architecture()
update_phase_log()
update_guides()
