import os

with open("config/paths.py", "r", encoding="utf-8") as f:
    content = f.read()

paths_code = '''
# Phase 73: Local Training
LAKE_LOCAL_TRAINING_DIR = LAKE_DIR / "local_training"
LAKE_LOCAL_TRAINING_DOMAINS_DIR = LAKE_LOCAL_TRAINING_DIR / "domains"
LAKE_LOCAL_TRAINING_ONBOARDING_DIR = LAKE_LOCAL_TRAINING_DIR / "onboarding"
LAKE_LOCAL_TRAINING_PACKS_DIR = LAKE_LOCAL_TRAINING_DIR / "packs"
LAKE_LOCAL_TRAINING_SAFE_USAGE_DIR = LAKE_LOCAL_TRAINING_DIR / "safe_usage"
LAKE_LOCAL_TRAINING_NON_USE_POLICY_DIR = LAKE_LOCAL_TRAINING_DIR / "non_use_policy"
LAKE_LOCAL_TRAINING_WALKTHROUGHS_DIR = LAKE_LOCAL_TRAINING_DIR / "walkthroughs"
LAKE_LOCAL_TRAINING_COMMANDS_DIR = LAKE_LOCAL_TRAINING_DIR / "commands"
LAKE_LOCAL_TRAINING_REPORTS_DIR = LAKE_LOCAL_TRAINING_DIR / "reports"
LAKE_LOCAL_TRAINING_DATALAKE_DIR = LAKE_LOCAL_TRAINING_DIR / "datalake"
LAKE_LOCAL_TRAINING_CROSS_LAYER_DIR = LAKE_LOCAL_TRAINING_DIR / "cross_layer"
LAKE_LOCAL_TRAINING_TROUBLESHOOTING_DIR = LAKE_LOCAL_TRAINING_DIR / "troubleshooting"
LAKE_LOCAL_TRAINING_GLOSSARY_DIR = LAKE_LOCAL_TRAINING_DIR / "glossary"
LAKE_LOCAL_TRAINING_CONCEPTS_DIR = LAKE_LOCAL_TRAINING_DIR / "concepts"
LAKE_LOCAL_TRAINING_FAQ_DIR = LAKE_LOCAL_TRAINING_DIR / "faq"
LAKE_LOCAL_TRAINING_HANDOVER_DIR = LAKE_LOCAL_TRAINING_DIR / "handover"
LAKE_LOCAL_TRAINING_CURRICULUM_DIR = LAKE_LOCAL_TRAINING_DIR / "curriculum"
LAKE_LOCAL_TRAINING_CHECKLISTS_DIR = LAKE_LOCAL_TRAINING_DIR / "checklists"
LAKE_LOCAL_TRAINING_GAPS_DIR = LAKE_LOCAL_TRAINING_DIR / "gaps"
LAKE_LOCAL_TRAINING_RISKS_DIR = LAKE_LOCAL_TRAINING_DIR / "risks"
LAKE_LOCAL_TRAINING_ASSESSMENT_DIR = LAKE_LOCAL_TRAINING_DIR / "assessment"
LAKE_LOCAL_TRAINING_VALIDATION_DIR = LAKE_LOCAL_TRAINING_DIR / "validation"
LAKE_LOCAL_TRAINING_QUALITY_DIR = LAKE_LOCAL_TRAINING_DIR / "quality"

REPORTS_LOCAL_TRAINING_DIR = REPORTS_OUTPUT_DIR / "local_training"
REPORTS_LOCAL_TRAINING_CSV_DIR = REPORTS_LOCAL_TRAINING_DIR / "csv"
REPORTS_LOCAL_TRAINING_MD_DIR = REPORTS_LOCAL_TRAINING_DIR / "markdown"
REPORTS_LOCAL_TRAINING_TXT_DIR = REPORTS_LOCAL_TRAINING_DIR / "txt"
REPORTS_LOCAL_TRAINING_JSON_DIR = REPORTS_LOCAL_TRAINING_DIR / "json"

DOCS_GENERATED_LOCAL_TRAINING_DIR = DOCS_DIR / "generated" / "local_training"
'''

new_project_dirs = '''
    LAKE_LOCAL_TRAINING_DIR,
    LAKE_LOCAL_TRAINING_DOMAINS_DIR,
    LAKE_LOCAL_TRAINING_ONBOARDING_DIR,
    LAKE_LOCAL_TRAINING_PACKS_DIR,
    LAKE_LOCAL_TRAINING_SAFE_USAGE_DIR,
    LAKE_LOCAL_TRAINING_NON_USE_POLICY_DIR,
    LAKE_LOCAL_TRAINING_WALKTHROUGHS_DIR,
    LAKE_LOCAL_TRAINING_COMMANDS_DIR,
    LAKE_LOCAL_TRAINING_REPORTS_DIR,
    LAKE_LOCAL_TRAINING_DATALAKE_DIR,
    LAKE_LOCAL_TRAINING_CROSS_LAYER_DIR,
    LAKE_LOCAL_TRAINING_TROUBLESHOOTING_DIR,
    LAKE_LOCAL_TRAINING_GLOSSARY_DIR,
    LAKE_LOCAL_TRAINING_CONCEPTS_DIR,
    LAKE_LOCAL_TRAINING_FAQ_DIR,
    LAKE_LOCAL_TRAINING_HANDOVER_DIR,
    LAKE_LOCAL_TRAINING_CURRICULUM_DIR,
    LAKE_LOCAL_TRAINING_CHECKLISTS_DIR,
    LAKE_LOCAL_TRAINING_GAPS_DIR,
    LAKE_LOCAL_TRAINING_RISKS_DIR,
    LAKE_LOCAL_TRAINING_ASSESSMENT_DIR,
    LAKE_LOCAL_TRAINING_VALIDATION_DIR,
    LAKE_LOCAL_TRAINING_QUALITY_DIR,
    REPORTS_LOCAL_TRAINING_DIR,
    REPORTS_LOCAL_TRAINING_CSV_DIR,
    REPORTS_LOCAL_TRAINING_MD_DIR,
    REPORTS_LOCAL_TRAINING_TXT_DIR,
    REPORTS_LOCAL_TRAINING_JSON_DIR,
    DOCS_GENERATED_LOCAL_TRAINING_DIR,
'''

new_all_exports = '''
    "LAKE_LOCAL_TRAINING_DIR",
    "LAKE_LOCAL_TRAINING_DOMAINS_DIR",
    "LAKE_LOCAL_TRAINING_ONBOARDING_DIR",
    "LAKE_LOCAL_TRAINING_PACKS_DIR",
    "LAKE_LOCAL_TRAINING_SAFE_USAGE_DIR",
    "LAKE_LOCAL_TRAINING_NON_USE_POLICY_DIR",
    "LAKE_LOCAL_TRAINING_WALKTHROUGHS_DIR",
    "LAKE_LOCAL_TRAINING_COMMANDS_DIR",
    "LAKE_LOCAL_TRAINING_REPORTS_DIR",
    "LAKE_LOCAL_TRAINING_DATALAKE_DIR",
    "LAKE_LOCAL_TRAINING_CROSS_LAYER_DIR",
    "LAKE_LOCAL_TRAINING_TROUBLESHOOTING_DIR",
    "LAKE_LOCAL_TRAINING_GLOSSARY_DIR",
    "LAKE_LOCAL_TRAINING_CONCEPTS_DIR",
    "LAKE_LOCAL_TRAINING_FAQ_DIR",
    "LAKE_LOCAL_TRAINING_HANDOVER_DIR",
    "LAKE_LOCAL_TRAINING_CURRICULUM_DIR",
    "LAKE_LOCAL_TRAINING_CHECKLISTS_DIR",
    "LAKE_LOCAL_TRAINING_GAPS_DIR",
    "LAKE_LOCAL_TRAINING_RISKS_DIR",
    "LAKE_LOCAL_TRAINING_ASSESSMENT_DIR",
    "LAKE_LOCAL_TRAINING_VALIDATION_DIR",
    "LAKE_LOCAL_TRAINING_QUALITY_DIR",
    "REPORTS_LOCAL_TRAINING_DIR",
    "REPORTS_LOCAL_TRAINING_CSV_DIR",
    "REPORTS_LOCAL_TRAINING_MD_DIR",
    "REPORTS_LOCAL_TRAINING_TXT_DIR",
    "REPORTS_LOCAL_TRAINING_JSON_DIR",
    "DOCS_GENERATED_LOCAL_TRAINING_DIR",
'''

# append paths_code before PROJECT_DIRS = [
content = content.replace("PROJECT_DIRS = [", paths_code + "\nPROJECT_DIRS = [\n" + new_project_dirs)

# append to __all__ = [
content = content.replace("__all__ = [", "__all__ = [\n" + new_all_exports)

with open("config/paths.py", "w", encoding="utf-8") as f:
    f.write(content)
