import os

with open(".env.example", "r", encoding="utf-8") as f:
    content = f.read()

env_vars = '''

# Local Training Settings
LOCAL_TRAINING_ENABLED=true
DEFAULT_LOCAL_TRAINING_PROFILE=balanced_local_training
LOCAL_TRAINING_DEFAULT_LANGUAGE=tr
LOCAL_TRAINING_DRY_RUN_DEFAULT=true
LOCAL_TRAINING_ALLOW_CLOUD_UPLOAD=false
LOCAL_TRAINING_ALLOW_EXTERNAL_TRAINING_SERVICE=false
LOCAL_TRAINING_ALLOW_EXTERNAL_LLM=false
LOCAL_TRAINING_ALLOW_FILE_MODIFICATION=false
LOCAL_TRAINING_ALLOW_FILE_DELETION=false
LOCAL_TRAINING_ALLOW_FILE_MOVE=false
LOCAL_TRAINING_ALLOW_OVERWRITE=false
LOCAL_TRAINING_ALLOW_LIVE_COMMANDS=false
LOCAL_TRAINING_ALLOW_BROKER_COMMANDS=false
LOCAL_TRAINING_ALLOW_DEPLOY_COMMANDS=false
LOCAL_TRAINING_ALLOW_BACKGROUND_DAEMONS=false
LOCAL_TRAINING_ALLOW_REAL_MARKET_DOWNLOAD=false
LOCAL_TRAINING_ALLOW_CERTIFICATION_CLAIM=false
LOCAL_TRAINING_ALLOW_INVESTMENT_ADVICE_TRAINING=false
LOCAL_TRAINING_SCAN_DOCS=true
LOCAL_TRAINING_SCAN_REPORTS=true
LOCAL_TRAINING_SCAN_SCRIPTS=true
LOCAL_TRAINING_SCAN_TESTS=true
LOCAL_TRAINING_SCAN_DATA_LAKE=true
LOCAL_TRAINING_SCAN_CROSS_LAYER_OUTPUTS=true
LOCAL_TRAINING_SCAN_SAFETY_DOCS=true
LOCAL_TRAINING_MAX_LESSONS=10000
LOCAL_TRAINING_MAX_WALKTHROUGH_STEPS=5000
LOCAL_TRAINING_MIN_TRAINING_QUALITY_SCORE=0.40
LOCAL_TRAINING_SAVE_REPORTS=true
'''

if "LOCAL_TRAINING_ENABLED" not in content:
    with open(".env.example", "a", encoding="utf-8") as f:
        f.write(env_vars)
