import re
from pathlib import Path

def patch_paths():
    path = Path("config/paths.py")
    content = path.read_text()

    if "LAKE_KNOWLEDGE_BASE_DIR" in content:
        print("Paths already patched.")
        return

    addition = """
# Phase 49: Knowledge Base
LAKE_KNOWLEDGE_BASE_DIR = LAKE_DIR / "knowledge_base"
LAKE_KNOWLEDGE_BASE_DOCUMENTS_DIR = LAKE_KNOWLEDGE_BASE_DIR / "documents"
LAKE_KNOWLEDGE_BASE_CHUNKS_DIR = LAKE_KNOWLEDGE_BASE_DIR / "chunks"
LAKE_KNOWLEDGE_BASE_INDEXES_DIR = LAKE_KNOWLEDGE_BASE_DIR / "indexes"
LAKE_KNOWLEDGE_BASE_RETRIEVAL_DIR = LAKE_KNOWLEDGE_BASE_DIR / "retrieval"
LAKE_KNOWLEDGE_BASE_MEMORY_CARDS_DIR = LAKE_KNOWLEDGE_BASE_DIR / "memory_cards"
LAKE_KNOWLEDGE_BASE_DECISION_JOURNAL_DIR = LAKE_KNOWLEDGE_BASE_DIR / "decision_journal"
LAKE_KNOWLEDGE_BASE_ANALYST_NOTES_DIR = LAKE_KNOWLEDGE_BASE_DIR / "analyst_notes"
LAKE_KNOWLEDGE_BASE_FINDINGS_DIR = LAKE_KNOWLEDGE_BASE_DIR / "findings"
LAKE_KNOWLEDGE_BASE_WORKSPACE_DIR = LAKE_KNOWLEDGE_BASE_DIR / "workspace"
LAKE_KNOWLEDGE_BASE_QUALITY_DIR = LAKE_KNOWLEDGE_BASE_DIR / "quality"

REPORTS_KNOWLEDGE_BASE_DIR = REPORTS_OUTPUT_DIR / "knowledge_base"
REPORTS_KNOWLEDGE_BASE_CSV_DIR = REPORTS_KNOWLEDGE_BASE_DIR / "csv"
REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR = REPORTS_KNOWLEDGE_BASE_DIR / "markdown"
REPORTS_KNOWLEDGE_BASE_TXT_DIR = REPORTS_KNOWLEDGE_BASE_DIR / "txt"
REPORTS_KNOWLEDGE_BASE_JSON_DIR = REPORTS_KNOWLEDGE_BASE_DIR / "json"

"""

    # Insert before ensure_project_directories
    content = content.replace("def ensure_project_directories", addition + "def ensure_project_directories")

    ensure_additions = """
        LAKE_KNOWLEDGE_BASE_DIR,
        LAKE_KNOWLEDGE_BASE_DOCUMENTS_DIR,
        LAKE_KNOWLEDGE_BASE_CHUNKS_DIR,
        LAKE_KNOWLEDGE_BASE_INDEXES_DIR,
        LAKE_KNOWLEDGE_BASE_RETRIEVAL_DIR,
        LAKE_KNOWLEDGE_BASE_MEMORY_CARDS_DIR,
        LAKE_KNOWLEDGE_BASE_DECISION_JOURNAL_DIR,
        LAKE_KNOWLEDGE_BASE_ANALYST_NOTES_DIR,
        LAKE_KNOWLEDGE_BASE_FINDINGS_DIR,
        LAKE_KNOWLEDGE_BASE_WORKSPACE_DIR,
        LAKE_KNOWLEDGE_BASE_QUALITY_DIR,
        REPORTS_KNOWLEDGE_BASE_DIR,
        REPORTS_KNOWLEDGE_BASE_CSV_DIR,
        REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR,
        REPORTS_KNOWLEDGE_BASE_TXT_DIR,
        REPORTS_KNOWLEDGE_BASE_JSON_DIR,
"""

    content = content.replace("        LOGS_DIR,", ensure_additions + "        LOGS_DIR,")

    # Add to ProjectPaths
    pp_additions = """
        self.LAKE_KNOWLEDGE_BASE_DIR = LAKE_KNOWLEDGE_BASE_DIR
        self.LAKE_KNOWLEDGE_BASE_DOCUMENTS_DIR = LAKE_KNOWLEDGE_BASE_DOCUMENTS_DIR
        self.LAKE_KNOWLEDGE_BASE_CHUNKS_DIR = LAKE_KNOWLEDGE_BASE_CHUNKS_DIR
        self.LAKE_KNOWLEDGE_BASE_INDEXES_DIR = LAKE_KNOWLEDGE_BASE_INDEXES_DIR
        self.LAKE_KNOWLEDGE_BASE_RETRIEVAL_DIR = LAKE_KNOWLEDGE_BASE_RETRIEVAL_DIR
        self.LAKE_KNOWLEDGE_BASE_MEMORY_CARDS_DIR = LAKE_KNOWLEDGE_BASE_MEMORY_CARDS_DIR
        self.LAKE_KNOWLEDGE_BASE_DECISION_JOURNAL_DIR = LAKE_KNOWLEDGE_BASE_DECISION_JOURNAL_DIR
        self.LAKE_KNOWLEDGE_BASE_ANALYST_NOTES_DIR = LAKE_KNOWLEDGE_BASE_ANALYST_NOTES_DIR
        self.LAKE_KNOWLEDGE_BASE_FINDINGS_DIR = LAKE_KNOWLEDGE_BASE_FINDINGS_DIR
        self.LAKE_KNOWLEDGE_BASE_WORKSPACE_DIR = LAKE_KNOWLEDGE_BASE_WORKSPACE_DIR
        self.LAKE_KNOWLEDGE_BASE_QUALITY_DIR = LAKE_KNOWLEDGE_BASE_QUALITY_DIR
        self.REPORTS_KNOWLEDGE_BASE_DIR = REPORTS_KNOWLEDGE_BASE_DIR
        self.REPORTS_KNOWLEDGE_BASE_CSV_DIR = REPORTS_KNOWLEDGE_BASE_CSV_DIR
        self.REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR = REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR
        self.REPORTS_KNOWLEDGE_BASE_TXT_DIR = REPORTS_KNOWLEDGE_BASE_TXT_DIR
        self.REPORTS_KNOWLEDGE_BASE_JSON_DIR = REPORTS_KNOWLEDGE_BASE_JSON_DIR
"""

    content = content.replace("        self.REPORTS_GOVERNANCE_JSON_DIR = REPORTS_GOVERNANCE_JSON_DIR", "        self.REPORTS_GOVERNANCE_JSON_DIR = REPORTS_GOVERNANCE_JSON_DIR\n" + pp_additions)

    path.write_text(content)
    print("Paths patched successfully.")

if __name__ == "__main__":
    patch_paths()
