import re

with open("commodity_fx_signal_bot/config/paths.py", "r") as f:
    content = f.read()

cc_paths_global = """
# Phase 50: Command Center
LAKE_COMMAND_CENTER_DIR = LAKE_DIR / "command_center"
LAKE_COMMAND_CENTER_REGISTRY_DIR = LAKE_COMMAND_CENTER_DIR / "registry"
LAKE_COMMAND_CENTER_WORKFLOWS_DIR = LAKE_COMMAND_CENTER_DIR / "workflows"
LAKE_COMMAND_CENTER_RUNBOOKS_DIR = LAKE_COMMAND_CENTER_DIR / "runbooks"
LAKE_COMMAND_CENTER_DRY_RUN_PLANS_DIR = LAKE_COMMAND_CENTER_DIR / "dry_run_plans"
LAKE_COMMAND_CENTER_QUERY_FLOWS_DIR = LAKE_COMMAND_CENTER_DIR / "query_flows"
LAKE_COMMAND_CENTER_PROJECT_STATUS_DIR = LAKE_COMMAND_CENTER_DIR / "project_status"
LAKE_COMMAND_CENTER_MODULE_HEALTH_DIR = LAKE_COMMAND_CENTER_DIR / "module_health"
LAKE_COMMAND_CENTER_SCRIPT_DISCOVERY_DIR = LAKE_COMMAND_CENTER_DIR / "script_discovery"
LAKE_COMMAND_CENTER_PHASE_COVERAGE_DIR = LAKE_COMMAND_CENTER_DIR / "phase_coverage"
LAKE_COMMAND_CENTER_CONSOLIDATION_DIR = LAKE_COMMAND_CENTER_DIR / "consolidation"
LAKE_COMMAND_CENTER_ONBOARDING_DIR = LAKE_COMMAND_CENTER_DIR / "onboarding"
LAKE_COMMAND_CENTER_TROUBLESHOOTING_DIR = LAKE_COMMAND_CENTER_DIR / "troubleshooting"
LAKE_COMMAND_CENTER_QUALITY_DIR = LAKE_COMMAND_CENTER_DIR / "quality"

REPORTS_COMMAND_CENTER_DIR = REPORTS_DIR / "command_center"
REPORTS_COMMAND_CENTER_CSV_DIR = REPORTS_COMMAND_CENTER_DIR / "csv"
REPORTS_COMMAND_CENTER_MARKDOWN_DIR = REPORTS_COMMAND_CENTER_DIR / "markdown"
REPORTS_COMMAND_CENTER_TXT_DIR = REPORTS_COMMAND_CENTER_DIR / "txt"
REPORTS_COMMAND_CENTER_JSON_DIR = REPORTS_COMMAND_CENTER_DIR / "json"

class ProjectPaths:"""

content = re.sub(r'class ProjectPaths:', cc_paths_global, content, count=1)

cc_paths_instance = """
        self.LAKE_KNOWLEDGE_BASE_QUALITY_DIR = LAKE_KNOWLEDGE_BASE_QUALITY_DIR
        self.REPORTS_KNOWLEDGE_BASE_DIR = REPORTS_KNOWLEDGE_BASE_DIR
        self.REPORTS_KNOWLEDGE_BASE_CSV_DIR = REPORTS_KNOWLEDGE_BASE_CSV_DIR
        self.REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR = REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR
        self.REPORTS_KNOWLEDGE_BASE_TXT_DIR = REPORTS_KNOWLEDGE_BASE_TXT_DIR
        self.REPORTS_KNOWLEDGE_BASE_JSON_DIR = REPORTS_KNOWLEDGE_BASE_JSON_DIR

        # Phase 50: Command Center
        self.LAKE_COMMAND_CENTER_DIR = LAKE_COMMAND_CENTER_DIR
        self.LAKE_COMMAND_CENTER_REGISTRY_DIR = LAKE_COMMAND_CENTER_REGISTRY_DIR
        self.LAKE_COMMAND_CENTER_WORKFLOWS_DIR = LAKE_COMMAND_CENTER_WORKFLOWS_DIR
        self.LAKE_COMMAND_CENTER_RUNBOOKS_DIR = LAKE_COMMAND_CENTER_RUNBOOKS_DIR
        self.LAKE_COMMAND_CENTER_DRY_RUN_PLANS_DIR = LAKE_COMMAND_CENTER_DRY_RUN_PLANS_DIR
        self.LAKE_COMMAND_CENTER_QUERY_FLOWS_DIR = LAKE_COMMAND_CENTER_QUERY_FLOWS_DIR
        self.LAKE_COMMAND_CENTER_PROJECT_STATUS_DIR = LAKE_COMMAND_CENTER_PROJECT_STATUS_DIR
        self.LAKE_COMMAND_CENTER_MODULE_HEALTH_DIR = LAKE_COMMAND_CENTER_MODULE_HEALTH_DIR
        self.LAKE_COMMAND_CENTER_SCRIPT_DISCOVERY_DIR = LAKE_COMMAND_CENTER_SCRIPT_DISCOVERY_DIR
        self.LAKE_COMMAND_CENTER_PHASE_COVERAGE_DIR = LAKE_COMMAND_CENTER_PHASE_COVERAGE_DIR
        self.LAKE_COMMAND_CENTER_CONSOLIDATION_DIR = LAKE_COMMAND_CENTER_CONSOLIDATION_DIR
        self.LAKE_COMMAND_CENTER_ONBOARDING_DIR = LAKE_COMMAND_CENTER_ONBOARDING_DIR
        self.LAKE_COMMAND_CENTER_TROUBLESHOOTING_DIR = LAKE_COMMAND_CENTER_TROUBLESHOOTING_DIR
        self.LAKE_COMMAND_CENTER_QUALITY_DIR = LAKE_COMMAND_CENTER_QUALITY_DIR

        self.REPORTS_COMMAND_CENTER_DIR = REPORTS_COMMAND_CENTER_DIR
        self.REPORTS_COMMAND_CENTER_CSV_DIR = REPORTS_COMMAND_CENTER_CSV_DIR
        self.REPORTS_COMMAND_CENTER_MARKDOWN_DIR = REPORTS_COMMAND_CENTER_MARKDOWN_DIR
        self.REPORTS_COMMAND_CENTER_TXT_DIR = REPORTS_COMMAND_CENTER_TXT_DIR
        self.REPORTS_COMMAND_CENTER_JSON_DIR = REPORTS_COMMAND_CENTER_JSON_DIR
"""

content = re.sub(
    r'        self\.LAKE_KNOWLEDGE_BASE_QUALITY_DIR = LAKE_KNOWLEDGE_BASE_QUALITY_DIR\n        self\.REPORTS_KNOWLEDGE_BASE_DIR = REPORTS_KNOWLEDGE_BASE_DIR\n        self\.REPORTS_KNOWLEDGE_BASE_CSV_DIR = REPORTS_KNOWLEDGE_BASE_CSV_DIR\n        self\.REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR = REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR\n        self\.REPORTS_KNOWLEDGE_BASE_TXT_DIR = REPORTS_KNOWLEDGE_BASE_TXT_DIR\n        self\.REPORTS_KNOWLEDGE_BASE_JSON_DIR = REPORTS_KNOWLEDGE_BASE_JSON_DIR',
    cc_paths_instance,
    content,
    flags=re.MULTILINE
)

cc_paths_ensure = """
            self.LAKE_KNOWLEDGE_BASE_QUALITY_DIR,
            self.REPORTS_KNOWLEDGE_BASE_DIR,
            self.REPORTS_KNOWLEDGE_BASE_CSV_DIR,
            self.REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR,
            self.REPORTS_KNOWLEDGE_BASE_TXT_DIR,
            self.REPORTS_KNOWLEDGE_BASE_JSON_DIR,
            # Phase 50
            self.LAKE_COMMAND_CENTER_DIR,
            self.LAKE_COMMAND_CENTER_REGISTRY_DIR,
            self.LAKE_COMMAND_CENTER_WORKFLOWS_DIR,
            self.LAKE_COMMAND_CENTER_RUNBOOKS_DIR,
            self.LAKE_COMMAND_CENTER_DRY_RUN_PLANS_DIR,
            self.LAKE_COMMAND_CENTER_QUERY_FLOWS_DIR,
            self.LAKE_COMMAND_CENTER_PROJECT_STATUS_DIR,
            self.LAKE_COMMAND_CENTER_MODULE_HEALTH_DIR,
            self.LAKE_COMMAND_CENTER_SCRIPT_DISCOVERY_DIR,
            self.LAKE_COMMAND_CENTER_PHASE_COVERAGE_DIR,
            self.LAKE_COMMAND_CENTER_CONSOLIDATION_DIR,
            self.LAKE_COMMAND_CENTER_ONBOARDING_DIR,
            self.LAKE_COMMAND_CENTER_TROUBLESHOOTING_DIR,
            self.LAKE_COMMAND_CENTER_QUALITY_DIR,
            self.REPORTS_COMMAND_CENTER_DIR,
            self.REPORTS_COMMAND_CENTER_CSV_DIR,
            self.REPORTS_COMMAND_CENTER_MARKDOWN_DIR,
            self.REPORTS_COMMAND_CENTER_TXT_DIR,
            self.REPORTS_COMMAND_CENTER_JSON_DIR,
"""

content = re.sub(
    r'            self\.LAKE_KNOWLEDGE_BASE_QUALITY_DIR,\n            self\.REPORTS_KNOWLEDGE_BASE_DIR,\n            self\.REPORTS_KNOWLEDGE_BASE_CSV_DIR,\n            self\.REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR,\n            self\.REPORTS_KNOWLEDGE_BASE_TXT_DIR,\n            self\.REPORTS_KNOWLEDGE_BASE_JSON_DIR,',
    cc_paths_ensure,
    content,
    flags=re.MULTILINE
)

with open("commodity_fx_signal_bot/config/paths.py", "w") as f:
    f.write(content)
