def update_paths():
    file_path = "config/paths.py"
    with open(file_path, "r") as f:
        content = f.read()

    paths_insertion = """
# Phase 70: Local Maintenance
LAKE_LOCAL_MAINTENANCE_DIR = LAKE_DIR / "local_maintenance"
LAKE_LOCAL_MAINTENANCE_DOMAINS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "domains"
LAKE_LOCAL_MAINTENANCE_TASKS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "tasks"
LAKE_LOCAL_MAINTENANCE_CALENDAR_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "calendar"
LAKE_LOCAL_MAINTENANCE_CADENCE_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "cadence"
LAKE_LOCAL_MAINTENANCE_DEPENDENCIES_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "dependencies"
LAKE_LOCAL_MAINTENANCE_DEPENDENCY_REVIEW_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "dependency_review"
LAKE_LOCAL_MAINTENANCE_STALE_ARTIFACTS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "stale_artifacts"
LAKE_LOCAL_MAINTENANCE_STALE_REPORTS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "stale_reports"
LAKE_LOCAL_MAINTENANCE_STALE_DOCS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "stale_docs"
LAKE_LOCAL_MAINTENANCE_STALE_TESTS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "stale_tests"
LAKE_LOCAL_MAINTENANCE_MANUAL_REVIEW_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "manual_review"
LAKE_LOCAL_MAINTENANCE_GAPS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "gaps"
LAKE_LOCAL_MAINTENANCE_RISKS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "risks"
LAKE_LOCAL_MAINTENANCE_SCORING_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "scoring"
LAKE_LOCAL_MAINTENANCE_OPERATOR_CHECKLISTS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "operator_checklists"
LAKE_LOCAL_MAINTENANCE_TEMPLATES_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "templates"
LAKE_LOCAL_MAINTENANCE_REFRESH_COMMANDS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "refresh_commands"
LAKE_LOCAL_MAINTENANCE_RUNBOOKS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "runbooks"
LAKE_LOCAL_MAINTENANCE_BINDERS_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "binders"
LAKE_LOCAL_MAINTENANCE_VALIDATION_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "validation"
LAKE_LOCAL_MAINTENANCE_QUALITY_DIR = LAKE_LOCAL_MAINTENANCE_DIR / "quality"

REPORTS_LOCAL_MAINTENANCE_DIR = REPORTS_OUTPUT_DIR / "local_maintenance"
REPORTS_LOCAL_MAINTENANCE_CSV_DIR = REPORTS_LOCAL_MAINTENANCE_DIR / "csv"
REPORTS_LOCAL_MAINTENANCE_MARKDOWN_DIR = REPORTS_LOCAL_MAINTENANCE_DIR / "markdown"
REPORTS_LOCAL_MAINTENANCE_TXT_DIR = REPORTS_LOCAL_MAINTENANCE_DIR / "txt"
REPORTS_LOCAL_MAINTENANCE_JSON_DIR = REPORTS_LOCAL_MAINTENANCE_DIR / "json"

DOCS_GENERATED_LOCAL_MAINTENANCE_DIR = DOCS_DIR / "generated" / "local_maintenance"
"""

    project_dirs_insertion = """
    LAKE_LOCAL_MAINTENANCE_DIR,
    LAKE_LOCAL_MAINTENANCE_DOMAINS_DIR,
    LAKE_LOCAL_MAINTENANCE_TASKS_DIR,
    LAKE_LOCAL_MAINTENANCE_CALENDAR_DIR,
    LAKE_LOCAL_MAINTENANCE_CADENCE_DIR,
    LAKE_LOCAL_MAINTENANCE_DEPENDENCIES_DIR,
    LAKE_LOCAL_MAINTENANCE_DEPENDENCY_REVIEW_DIR,
    LAKE_LOCAL_MAINTENANCE_STALE_ARTIFACTS_DIR,
    LAKE_LOCAL_MAINTENANCE_STALE_REPORTS_DIR,
    LAKE_LOCAL_MAINTENANCE_STALE_DOCS_DIR,
    LAKE_LOCAL_MAINTENANCE_STALE_TESTS_DIR,
    LAKE_LOCAL_MAINTENANCE_MANUAL_REVIEW_DIR,
    LAKE_LOCAL_MAINTENANCE_GAPS_DIR,
    LAKE_LOCAL_MAINTENANCE_RISKS_DIR,
    LAKE_LOCAL_MAINTENANCE_SCORING_DIR,
    LAKE_LOCAL_MAINTENANCE_OPERATOR_CHECKLISTS_DIR,
    LAKE_LOCAL_MAINTENANCE_TEMPLATES_DIR,
    LAKE_LOCAL_MAINTENANCE_REFRESH_COMMANDS_DIR,
    LAKE_LOCAL_MAINTENANCE_RUNBOOKS_DIR,
    LAKE_LOCAL_MAINTENANCE_BINDERS_DIR,
    LAKE_LOCAL_MAINTENANCE_VALIDATION_DIR,
    LAKE_LOCAL_MAINTENANCE_QUALITY_DIR,
    REPORTS_LOCAL_MAINTENANCE_DIR,
    REPORTS_LOCAL_MAINTENANCE_CSV_DIR,
    REPORTS_LOCAL_MAINTENANCE_MARKDOWN_DIR,
    REPORTS_LOCAL_MAINTENANCE_TXT_DIR,
    REPORTS_LOCAL_MAINTENANCE_JSON_DIR,
    DOCS_GENERATED_LOCAL_MAINTENANCE_DIR,
"""

    all_insertion = """
    "LAKE_LOCAL_MAINTENANCE_DIR",
    "LAKE_LOCAL_MAINTENANCE_DOMAINS_DIR",
    "LAKE_LOCAL_MAINTENANCE_TASKS_DIR",
    "LAKE_LOCAL_MAINTENANCE_CALENDAR_DIR",
    "LAKE_LOCAL_MAINTENANCE_CADENCE_DIR",
    "LAKE_LOCAL_MAINTENANCE_DEPENDENCIES_DIR",
    "LAKE_LOCAL_MAINTENANCE_DEPENDENCY_REVIEW_DIR",
    "LAKE_LOCAL_MAINTENANCE_STALE_ARTIFACTS_DIR",
    "LAKE_LOCAL_MAINTENANCE_STALE_REPORTS_DIR",
    "LAKE_LOCAL_MAINTENANCE_STALE_DOCS_DIR",
    "LAKE_LOCAL_MAINTENANCE_STALE_TESTS_DIR",
    "LAKE_LOCAL_MAINTENANCE_MANUAL_REVIEW_DIR",
    "LAKE_LOCAL_MAINTENANCE_GAPS_DIR",
    "LAKE_LOCAL_MAINTENANCE_RISKS_DIR",
    "LAKE_LOCAL_MAINTENANCE_SCORING_DIR",
    "LAKE_LOCAL_MAINTENANCE_OPERATOR_CHECKLISTS_DIR",
    "LAKE_LOCAL_MAINTENANCE_TEMPLATES_DIR",
    "LAKE_LOCAL_MAINTENANCE_REFRESH_COMMANDS_DIR",
    "LAKE_LOCAL_MAINTENANCE_RUNBOOKS_DIR",
    "LAKE_LOCAL_MAINTENANCE_BINDERS_DIR",
    "LAKE_LOCAL_MAINTENANCE_VALIDATION_DIR",
    "LAKE_LOCAL_MAINTENANCE_QUALITY_DIR",
    "REPORTS_LOCAL_MAINTENANCE_DIR",
    "REPORTS_LOCAL_MAINTENANCE_CSV_DIR",
    "REPORTS_LOCAL_MAINTENANCE_MARKDOWN_DIR",
    "REPORTS_LOCAL_MAINTENANCE_TXT_DIR",
    "REPORTS_LOCAL_MAINTENANCE_JSON_DIR",
    "DOCS_GENERATED_LOCAL_MAINTENANCE_DIR",
"""

    if "LAKE_LOCAL_MAINTENANCE_DIR" not in content:
        # Add paths
        idx1 = content.find("PROJECT_DIRS = [")
        if idx1 != -1:
            content = content[:idx1] + paths_insertion + "\n" + content[idx1:]

        # Add to PROJECT_DIRS
        idx2 = content.find("LAKE_LOCAL_READINESS_DIR", content.find("PROJECT_DIRS = ["))
        if idx2 != -1:
            content = content[:idx2] + project_dirs_insertion + "    " + content[idx2:]

        # Add to __all__
        idx3 = content.find('"LAKE_LOCAL_READINESS_DIR"', content.find("__all__ = ["))
        if idx3 != -1:
            content = content[:idx3] + all_insertion + '    ' + content[idx3:]

        with open(file_path, "w") as f:
            f.write(content)

update_paths()
