#!/bin/bash
pytest tests/test_maintenance_config.py
pytest tests/test_maintenance_labels.py
pytest tests/test_maintenance_models.py
pytest tests/test_domain_registry.py
pytest tests/test_task_registry.py
pytest tests/test_review_calendar.py
pytest tests/test_refresh_cadence.py
pytest tests/test_dependency_aging.py
pytest tests/test_dependency_review.py
pytest tests/test_stale_artifact_watch.py
pytest tests/test_stale_report_watch.py
pytest tests/test_stale_documentation_watch.py
pytest tests/test_stale_test_watch.py
pytest tests/test_manual_review_queue.py
pytest tests/test_maintenance_gaps.py
pytest tests/test_maintenance_risks.py
pytest tests/test_sustainability_scoring.py
pytest tests/test_operator_review_checklist.py
pytest tests/test_review_templates.py
pytest tests/test_refresh_command_plan.py
pytest tests/test_maintenance_runbook.py
pytest tests/test_sustainability_binder.py
pytest tests/test_maintenance_validation.py
pytest tests/test_maintenance_quality.py
pytest tests/test_maintenance_report_builder.py
pytest tests/test_maintenance_pipeline.py
pytest tests/test_local_maintenance_scripts_contract.py
