from typing import Tuple, Dict, Any, List
import pandas as pd

from advanced_technical_indicators.technical_indicator_config import TechnicalIndicatorProfile
from advanced_technical_indicators.technical_indicator_models import (
    TechnicalIndicatorCatalogItem,
    build_technical_indicator_id,
)

CATALOG_DATA: List[Dict[str, Any]] = [
    # 1. Price Action
    {
        "name": "high_low_range",
        "family": "family_price_action",
        "req": ["high", "low"],
        "opt": [],
        "out": ["high_low_range"],
        "params": {},
        "formula": "high - low",
        "warmup": "immediate",
        "no_lookahead": "current bar only",
        "usage": "Volatilite ve bar genişliği feature'ı. Sinyal değildir.",
    },
    {
        "name": "close_open_range",
        "family": "family_price_action",
        "req": ["close", "open"],
        "opt": [],
        "out": ["close_open_range"],
        "params": {},
        "formula": "close - open",
        "warmup": "immediate",
        "no_lookahead": "current bar only",
        "usage": "Bar yönü ve büyüklüğü feature'ı. Sinyal değildir.",
    },
    {
        "name": "range_pct",
        "family": "family_price_action",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["range_pct"],
        "params": {},
        "formula": "(high - low) / close",
        "warmup": "immediate",
        "no_lookahead": "current bar only",
        "usage": "Normalleştirilmiş aralık feature'ı. Sinyal değildir.",
    },
    {
        "name": "gap_from_prev_close",
        "family": "family_price_action",
        "req": ["open", "close"],
        "opt": [],
        "out": ["gap_from_prev_close"],
        "params": {},
        "formula": "open - close.shift(1)",
        "warmup": "1 bar",
        "no_lookahead": "shift(1) past only",
        "usage": "Açılış boşluğu feature'ı. Sinyal değildir.",
    },
    {
        "name": "close_location_value",
        "family": "family_price_action",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["close_location_value"],
        "params": {},
        "formula": "((close - low) - (high - close)) / (high - low)",
        "warmup": "immediate",
        "no_lookahead": "current bar only",
        "usage": "Kapanışın bar içi konumu [-1, 1]. Sinyal değildir.",
    },

    # 2. Returns
    {
        "name": "simple_return",
        "family": "family_returns",
        "req": ["close"],
        "opt": [],
        "out": ["simple_return_{window}"],
        "params": {"window": 1},
        "formula": "close / close.shift(window) - 1.0",
        "warmup": "window bars",
        "no_lookahead": "shift(window) past only",
        "usage": "Geçmiş getiri feature'ı. Sinyal/target değildir.",
    },
    {
        "name": "log_return",
        "family": "family_returns",
        "req": ["close"],
        "opt": [],
        "out": ["log_return_{window}"],
        "params": {"window": 1},
        "formula": "log(close / close.shift(window))",
        "warmup": "window bars",
        "no_lookahead": "shift(window) past only",
        "usage": "Logaritmik getiri feature'ı. Sinyal/target değildir.",
    },
    {
        "name": "cumulative_return",
        "family": "family_returns",
        "req": ["close"],
        "opt": [],
        "out": ["cumulative_return_{window}"],
        "params": {"window": 20},
        "formula": "(close / close.shift(window)) - 1.0",
        "warmup": "window bars",
        "no_lookahead": "shift(window) past only",
        "usage": "Kümülatif getiri feature'ı. Sinyal/target değildir.",
    },
    {
        "name": "rolling_return_sum",
        "family": "family_returns",
        "req": ["close"],
        "opt": [],
        "out": ["rolling_return_sum_{window}"],
        "params": {"window": 20},
        "formula": "simple_return(1).rolling(window).sum()",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Getiri toplamı feature'ı. Sinyal değildir.",
    },
    {
        "name": "return_volatility_ratio",
        "family": "family_returns",
        "req": ["close"],
        "opt": [],
        "out": ["return_vol_ratio_{window}"],
        "params": {"window": 20},
        "formula": "rolling_mean_return / rolling_std_return",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Getiri/oynaklık oranı feature'ı. Sharpe/trade tavsiyesi değildir.",
    },

    # 3. Moving Averages
    {
        "name": "sma",
        "family": "family_moving_average",
        "req": ["close"],
        "opt": [],
        "out": ["sma_{window}"],
        "params": {"window": 20},
        "formula": "rolling(window).mean()",
        "warmup": "window - 1 bars",
        "no_lookahead": "rolling past only",
        "usage": "Basit hareketli ortalama feature'ı. Sinyal değildir.",
    },
    {
        "name": "ema",
        "family": "family_moving_average",
        "req": ["close"],
        "opt": [],
        "out": ["ema_{window}"],
        "params": {"window": 20},
        "formula": "ewm(span=window, adjust=False).mean()",
        "warmup": "window bars",
        "no_lookahead": "ewm past only",
        "usage": "Üstel hareketli ortalama feature'ı. Sinyal değildir.",
    },
    {
        "name": "wma",
        "family": "family_moving_average",
        "req": ["close"],
        "opt": [],
        "out": ["wma_{window}"],
        "params": {"window": 20},
        "formula": "weighted rolling sum with linearly increasing weights",
        "warmup": "window - 1 bars",
        "no_lookahead": "rolling past only",
        "usage": "Ağırlıklı hareketli ortalama feature'ı. Sinyal değildir.",
    },
    {
        "name": "dema",
        "family": "family_moving_average",
        "req": ["close"],
        "opt": [],
        "out": ["dema_{window}"],
        "params": {"window": 20},
        "formula": "2 * EMA(window) - EMA(EMA(window))",
        "warmup": "2 * window bars",
        "no_lookahead": "ewm past only",
        "usage": "Double exponential moving average feature'ı. Sinyal değildir.",
    },
    {
        "name": "tema",
        "family": "family_moving_average",
        "req": ["close"],
        "opt": [],
        "out": ["tema_{window}"],
        "params": {"window": 20},
        "formula": "3 * EMA - 3 * EMA(EMA) + EMA(EMA(EMA))",
        "warmup": "3 * window bars",
        "no_lookahead": "ewm past only",
        "usage": "Triple exponential moving average feature'ı. Sinyal değildir.",
    },
    {
        "name": "ma_distance",
        "family": "family_moving_average",
        "req": ["close"],
        "opt": [],
        "out": ["ma_distance_{window}"],
        "params": {"window": 20, "ma_type": "sma"},
        "formula": "(close - MA) / MA",
        "warmup": "window bars",
        "no_lookahead": "past only",
        "usage": "Fiyatın MA'dan oransal sapması. Sinyal değildir.",
    },

    # 4. Trend Indicators
    {
        "name": "macd",
        "family": "family_trend",
        "req": ["close"],
        "opt": [],
        "out": ["{prefix}_line", "{prefix}_smooth", "{prefix}_hist"],
        "params": {"fast": 12, "slow": 26, "signal_window": 9, "prefix": "macd"},
        "formula": "EMA(12) - EMA(26); smooth line is EMA(9) of macd_line",
        "warmup": "slow + signal_window bars",
        "no_lookahead": "ewm past only",
        "usage": "MACD gösterge feature'ları. Smooth line adı 'smooth' olarak tutulur; crossover sinyali üretilmez.",
    },
    {
        "name": "ppo",
        "family": "family_trend",
        "req": ["close"],
        "opt": [],
        "out": ["{prefix}_line", "{prefix}_smooth", "{prefix}_hist"],
        "params": {"fast": 12, "slow": 26, "signal_window": 9, "prefix": "ppo"},
        "formula": "((EMA(12) - EMA(26)) / EMA(26)) * 100",
        "warmup": "slow + signal_window bars",
        "no_lookahead": "ewm past only",
        "usage": "Yüzdesel fiyat osilatörü. Sinyal değildir.",
    },
    {
        "name": "donchian_channel",
        "family": "family_trend",
        "req": ["high", "low"],
        "opt": [],
        "out": ["{prefix}_upper_{window}", "{prefix}_lower_{window}", "{prefix}_mid_{window}"],
        "params": {"window": 20, "prefix": "donchian"},
        "formula": "rolling max(high), rolling min(low), mean of both",
        "warmup": "window - 1 bars",
        "no_lookahead": "rolling past only",
        "usage": "Donchian kanalı bant feature'ları. Kırılım sinyali üretilmez.",
    },
    {
        "name": "aroon",
        "family": "family_trend",
        "req": ["high", "low"],
        "opt": [],
        "out": ["{prefix}_up_{window}", "{prefix}_down_{window}", "{prefix}_osc_{window}"],
        "params": {"window": 25, "prefix": "aroon"},
        "formula": "Aroon Up / Down / Oscillator (en son tepe/dip zamanı)",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Aroon trend göstergesi. Al/sat kuralı üretilmez.",
    },
    {
        "name": "adx_dmi_placeholder",
        "family": "family_trend",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["{prefix}_plus_di_{window}", "{prefix}_minus_di_{window}", "{prefix}_adx_{window}"],
        "params": {"window": 14, "prefix": "adx"},
        "formula": "Directional Movement System + ADX trend strength feature",
        "warmup": "2 * window bars",
        "no_lookahead": "rolling past only",
        "usage": "ADX/DMI feature seti. Trend gücü ölçümüdür, işlem tavsiyesi üretilmez.",
    },
    {
        "name": "ichimoku_placeholder",
        "family": "family_trend",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["{prefix}_tenkan", "{prefix}_kijun", "{prefix}_senkou_a", "{prefix}_senkou_b"],
        "params": {"prefix": "ichimoku"},
        "formula": "Tenkan (9), Kijun (26), Senkou Spans A/B backward-aligned",
        "warmup": "52 bars",
        "no_lookahead": "zero future cloud projection to avoid lookahead",
        "usage": "Ichimoku bulut seviyeleri feature'ı. İleri ötelenmiş tahmin veya sinyal üretilmez.",
    },

    # 5. Momentum
    {
        "name": "momentum",
        "family": "family_momentum",
        "req": ["close"],
        "opt": [],
        "out": ["momentum_{window}"],
        "params": {"window": 10},
        "formula": "close - close.shift(window)",
        "warmup": "window bars",
        "no_lookahead": "shift(window) past only",
        "usage": "Momentum büyüklük feature'ı. Sinyal değildir.",
    },
    {
        "name": "roc",
        "family": "family_momentum",
        "req": ["close"],
        "opt": [],
        "out": ["roc_{window}"],
        "params": {"window": 10},
        "formula": "((close - close.shift(window)) / close.shift(window)) * 100",
        "warmup": "window bars",
        "no_lookahead": "shift(window) past only",
        "usage": "Rate of change yüzdesi. Sinyal değildir.",
    },
    {
        "name": "rsi",
        "family": "family_momentum",
        "req": ["close"],
        "opt": [],
        "out": ["rsi_{window}"],
        "params": {"window": 14},
        "formula": "100 - (100 / (1 + RS))",
        "warmup": "window bars",
        "no_lookahead": "past only",
        "usage": "RSI osilatör değeri. Aşırı alım/satım yorumu veya trade sinyali üretilmez.",
    },
    {
        "name": "cmo",
        "family": "family_momentum",
        "req": ["close"],
        "opt": [],
        "out": ["cmo_{window}"],
        "params": {"window": 14},
        "formula": "100 * (sum_up - sum_down) / (sum_up + sum_down)",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Chande Momentum Osilatörü. Sinyal değildir.",
    },
    {
        "name": "tsi_placeholder",
        "family": "family_momentum",
        "req": ["close"],
        "opt": [],
        "out": ["tsi_{long_window}_{short_window}"],
        "params": {"long_window": 25, "short_window": 13},
        "formula": "True Strength Index double-smoothed momentum",
        "warmup": "long_window + short_window bars",
        "no_lookahead": "ewm past only",
        "usage": "TSI osilatör feature'ı. Sinyal değildir.",
    },

    # 6. Oscillators
    {
        "name": "stochastic",
        "family": "family_oscillator",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["{prefix}_k_{k_window}", "{prefix}_d_{k_window}_{d_window}"],
        "params": {"k_window": 14, "d_window": 3, "prefix": "stoch"},
        "formula": "%K = (close - lowest) / (highest - lowest) * 100; %D = SMA(%K)",
        "warmup": "k_window + d_window bars",
        "no_lookahead": "rolling past only",
        "usage": "Stochastic osilatör feature'ı. Crossover veya al/sat sinyali üretilmez.",
    },
    {
        "name": "williams_r",
        "family": "family_oscillator",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["williams_r_{window}"],
        "params": {"window": 14},
        "formula": "((highest - close) / (highest - lowest)) * -100",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Williams %R osilatör feature'ı. Sinyal üretilmez.",
    },
    {
        "name": "cci",
        "family": "family_oscillator",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["cci_{window}"],
        "params": {"window": 20},
        "formula": "(typical_price - sma(tp)) / (0.015 * mean_deviation)",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Commodity Channel Index. Aşırı bölge tavsiyesi üretilmez.",
    },
    {
        "name": "ultimate_oscillator_placeholder",
        "family": "family_oscillator",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["{prefix}"],
        "params": {"prefix": "ultimate_osc"},
        "formula": "Weighted average of buying pressure across 3 periods (7, 14, 28)",
        "warmup": "28 bars",
        "no_lookahead": "past only",
        "usage": "Ultimate Osilatör feature'ı. Sinyal değildir.",
    },
    {
        "name": "mfi_placeholder",
        "family": "family_oscillator",
        "req": ["high", "low", "close"],
        "opt": ["volume"],
        "out": ["mfi_{window}"],
        "params": {"window": 14},
        "formula": "Money Flow Index with volume weighting",
        "warmup": "window bars",
        "no_lookahead": "past only",
        "usage": "Money Flow Index feature'ı. Hacim eksikse graceful fallback sağlar.",
    },

    # 7. Volatility
    {
        "name": "true_range",
        "family": "family_volatility",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["true_range"],
        "params": {},
        "formula": "max(high-low, abs(high-prev_close), abs(low-prev_close))",
        "warmup": "1 bar",
        "no_lookahead": "shift(1) past only",
        "usage": "True Range oynaklık feature'ı. Sinyal değildir.",
    },
    {
        "name": "atr",
        "family": "family_volatility",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["atr_{window}"],
        "params": {"window": 14},
        "formula": "rolling mean or RMA of true_range",
        "warmup": "window bars",
        "no_lookahead": "past only",
        "usage": "Average True Range oynaklık feature'ı. Sinyal değildir.",
    },
    {
        "name": "rolling_std",
        "family": "family_volatility",
        "req": ["close"],
        "opt": [],
        "out": ["rolling_std_{window}"],
        "params": {"window": 20},
        "formula": "close.rolling(window).std()",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Kapanış standart sapması feature'ı. Sinyal değildir.",
    },
    {
        "name": "realized_volatility",
        "family": "family_volatility",
        "req": ["close"],
        "opt": [],
        "out": ["realized_vol_{window}"],
        "params": {"window": 20},
        "formula": "std(log_return) * sqrt(252)",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Yıllıklandırılmış gerçekleşen oynaklık. Risk veya trade tavsiyesi değildir.",
    },
    {
        "name": "parkinson_volatility",
        "family": "family_volatility",
        "req": ["high", "low"],
        "opt": [],
        "out": ["parkinson_vol_{window}"],
        "params": {"window": 20},
        "formula": "sqrt((1 / (4 * ln(2) * N)) * sum(ln(high/low)^2)) * sqrt(252)",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Parkinson High-Low oynaklık tahmini. Sinyal değildir.",
    },
    {
        "name": "garman_klass_volatility_placeholder",
        "family": "family_volatility",
        "req": ["open", "high", "low", "close"],
        "opt": [],
        "out": ["garman_klass_vol_{window}"],
        "params": {"window": 20},
        "formula": "Garman-Klass OHLC volatility estimator",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Garman-Klass oynaklık feature'ı. Sinyal değildir.",
    },

    # 8. Range
    {
        "name": "rolling_high_low_range",
        "family": "family_range",
        "req": ["high", "low"],
        "opt": [],
        "out": ["rolling_hl_range_{window}"],
        "params": {"window": 20},
        "formula": "rolling max(high) - rolling min(low)",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Belirli penceredeki fiyat aralığı. Sinyal değildir.",
    },
    {
        "name": "rolling_range_pct",
        "family": "family_range",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["rolling_range_pct_{window}"],
        "params": {"window": 20},
        "formula": "(rolling max(high) - rolling min(low)) / close",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Fiyata oranlanmış pencere aralığı. Sinyal değildir.",
    },
    {
        "name": "average_range",
        "family": "family_range",
        "req": ["high", "low"],
        "opt": [],
        "out": ["average_range_{window}"],
        "params": {"window": 20},
        "formula": "(high - low).rolling(window).mean()",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Ortalama bar aralığı feature'ı. Sinyal değildir.",
    },
    {
        "name": "range_zscore",
        "family": "family_range",
        "req": ["high", "low"],
        "opt": [],
        "out": ["range_zscore_{window}"],
        "params": {"window": 20},
        "formula": "(range - rolling_mean_range) / rolling_std_range",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Bar aralığı standart z-skoru. Sinyal değildir.",
    },

    # 9. Channels
    {
        "name": "bollinger_bands",
        "family": "family_channel",
        "req": ["close"],
        "opt": [],
        "out": ["{prefix}_upper_{window}", "{prefix}_mid_{window}", "{prefix}_lower_{window}"],
        "params": {"window": 20, "num_std": 2.0, "prefix": "bb"},
        "formula": "SMA +- num_std * rolling_std",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Bollinger bantları seviye feature'ları. Kırılım veya dönüş sinyali üretilmez.",
    },
    {
        "name": "bollinger_bandwidth",
        "family": "family_channel",
        "req": ["close"],
        "opt": [],
        "out": ["bb_bandwidth_{window}"],
        "params": {"window": 20, "num_std": 2.0},
        "formula": "(upper - lower) / mid",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Bollinger bant genişliği. Volatilite sıkışma feature'ıdır; yön bildirmez.",
    },
    {
        "name": "bollinger_percent_b",
        "family": "family_channel",
        "req": ["close"],
        "opt": [],
        "out": ["bb_percent_b_{window}"],
        "params": {"window": 20, "num_std": 2.0},
        "formula": "(close - lower) / (upper - lower)",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Fiyatın bant içindeki bağıl konumu. Sinyal değildir.",
    },
    {
        "name": "keltner_channel_placeholder",
        "family": "family_channel",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["{prefix}_upper_{window}", "{prefix}_mid_{window}", "{prefix}_lower_{window}"],
        "params": {"window": 20, "atr_window": 10, "prefix": "keltner"},
        "formula": "EMA +- 2 * ATR",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Keltner kanalı feature seviyeleri. Sinyal değildir.",
    },
    {
        "name": "donchian_position",
        "family": "family_channel",
        "req": ["high", "low", "close"],
        "opt": [],
        "out": ["donchian_position_{window}"],
        "params": {"window": 20},
        "formula": "(close - donchian_lower) / (donchian_upper - donchian_lower)",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Fiyatın Donchian kanalı içindeki bağıl konumu [0, 1]. Sinyal değildir.",
    },

    # 10. Candle Anatomy
    {
        "name": "candle_body_size",
        "family": "family_candle_anatomy",
        "req": ["open", "close"],
        "opt": [],
        "out": ["candle_body_size"],
        "params": {},
        "formula": "abs(close - open)",
        "warmup": "immediate",
        "no_lookahead": "current bar only",
        "usage": "Mum gövde büyüklüğü mutlak değeri. Sinyal değildir.",
    },
    {
        "name": "candle_body_pct",
        "family": "family_candle_anatomy",
        "req": ["open", "high", "low", "close"],
        "opt": [],
        "out": ["candle_body_pct"],
        "params": {},
        "formula": "abs(close - open) / (high - low)",
        "warmup": "immediate",
        "no_lookahead": "current bar only",
        "usage": "Mum gövdesinin toplam bara oranı. Sinyal değildir.",
    },
    {
        "name": "upper_wick_size",
        "family": "family_candle_anatomy",
        "req": ["open", "high", "close"],
        "opt": [],
        "out": ["upper_wick_size"],
        "params": {},
        "formula": "high - max(open, close)",
        "warmup": "immediate",
        "no_lookahead": "current bar only",
        "usage": "Üst gölge boyutu feature'ı. Sinyal değildir.",
    },
    {
        "name": "lower_wick_size",
        "family": "family_candle_anatomy",
        "req": ["open", "low", "close"],
        "opt": [],
        "out": ["lower_wick_size"],
        "params": {},
        "formula": "min(open, close) - low",
        "warmup": "immediate",
        "no_lookahead": "current bar only",
        "usage": "Alt gölge boyutu feature'ı. Sinyal değildir.",
    },
    {
        "name": "wick_balance",
        "family": "family_candle_anatomy",
        "req": ["open", "high", "low", "close"],
        "opt": [],
        "out": ["wick_balance"],
        "params": {},
        "formula": "(upper_wick - lower_wick) / (high - low)",
        "warmup": "immediate",
        "no_lookahead": "current bar only",
        "usage": "Gölge dengesi [-1, 1]. Formasyon al/sat yorumu üretilmez.",
    },

    # 11. Quote Microstructure
    {
        "name": "quote_mid",
        "family": "family_quote_microstructure",
        "req": ["bid", "ask"],
        "opt": [],
        "out": ["quote_mid"],
        "params": {},
        "formula": "(bid + ask) / 2.0",
        "warmup": "immediate",
        "no_lookahead": "current tick only",
        "usage": "Quote orta fiyat feature'ı. Sinyal değildir.",
    },
    {
        "name": "quote_spread",
        "family": "family_quote_microstructure",
        "req": ["bid", "ask"],
        "opt": [],
        "out": ["quote_spread"],
        "params": {},
        "formula": "ask - bid",
        "warmup": "immediate",
        "no_lookahead": "current tick only",
        "usage": "Quote farkı (spread) feature'ı. Sinyal değildir.",
    },
    {
        "name": "quote_spread_pct",
        "family": "family_quote_microstructure",
        "req": ["bid", "ask"],
        "opt": [],
        "out": ["quote_spread_pct"],
        "params": {},
        "formula": "(ask - bid) / quote_mid",
        "warmup": "immediate",
        "no_lookahead": "current tick only",
        "usage": "Yüzdesel spread feature'ı. Sinyal değildir.",
    },
    {
        "name": "bid_ask_ratio_placeholder",
        "family": "family_quote_microstructure",
        "req": ["bid", "ask"],
        "opt": [],
        "out": ["bid_ask_ratio_placeholder"],
        "params": {},
        "formula": "bid / ask",
        "warmup": "immediate",
        "no_lookahead": "current tick only",
        "usage": "Bid/Ask oran feature'ı. Sinyal değildir.",
    },
    {
        "name": "quote_staleness_placeholder",
        "family": "family_quote_microstructure",
        "req": ["timestamp"],
        "opt": [],
        "out": ["quote_staleness_placeholder"],
        "params": {},
        "formula": "seconds elapsed since previous timestamp",
        "warmup": "1 tick",
        "no_lookahead": "shift(1) past only",
        "usage": "Veri tazelik gecikmesi feature'ı. Sinyal değildir.",
    },

    # 12. Mean Reversion
    {
        "name": "rolling_zscore",
        "family": "family_mean_reversion",
        "req": ["close"],
        "opt": [],
        "out": ["rolling_zscore_{window}"],
        "params": {"window": 20},
        "formula": "(close - rolling_mean) / rolling_std",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Z-skoru feature'ı. Aşırı sapma al/sat tavsiyesi üretmez.",
    },
    {
        "name": "distance_to_sma",
        "family": "family_mean_reversion",
        "req": ["close"],
        "opt": [],
        "out": ["dist_to_sma_{window}"],
        "params": {"window": 20},
        "formula": "(close - SMA) / SMA",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "SMA uzaklık feature'ı. Sinyal değildir.",
    },
    {
        "name": "distance_to_ema",
        "family": "family_mean_reversion",
        "req": ["close"],
        "opt": [],
        "out": ["dist_to_ema_{window}"],
        "params": {"window": 20},
        "formula": "(close - EMA) / EMA",
        "warmup": "window bars",
        "no_lookahead": "ewm past only",
        "usage": "EMA uzaklık feature'ı. Sinyal değildir.",
    },
    {
        "name": "rolling_percentile_rank_placeholder",
        "family": "family_mean_reversion",
        "req": ["close"],
        "opt": [],
        "out": ["rolling_percentile_rank_{window}"],
        "params": {"window": 100},
        "formula": "percentile rank of close in rolling window [0, 100]",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Yüzdelik dilim feature'ı. Sinyal değildir.",
    },
    {
        "name": "rolling_deviation_ratio",
        "family": "family_mean_reversion",
        "req": ["close"],
        "opt": [],
        "out": ["rolling_deviation_ratio_{window}"],
        "params": {"window": 20},
        "formula": "abs(close - rolling_mean) / rolling_std",
        "warmup": "window bars",
        "no_lookahead": "rolling past only",
        "usage": "Mutlak sapma oranı feature'ı. Mean reversion giriş/çıkış sinyali üretmez.",
    },
]


def build_technical_indicator_catalog_expansion(
    profile: TechnicalIndicatorProfile,
) -> Tuple[pd.DataFrame, Dict[str, Any]]:
    items = []
    for c in CATALOG_DATA:
        cat_item = TechnicalIndicatorCatalogItem(
            indicator_id=build_technical_indicator_id(c["name"], c["family"]),
            indicator_name=c["name"],
            indicator_family=c["family"],
            required_fields=c["req"],
            optional_fields=c["opt"],
            output_fields=c["out"],
            default_parameters=c["params"],
            formula_note=c["formula"],
            warmup_policy=c["warmup"],
            no_lookahead_policy=c["no_lookahead"],
            non_signal_usage_note=c["usage"],
            status_label="indicator_ready",
            manual_review_required=False,
        )
        items.append(cat_item.to_dict())

    df = pd.DataFrame(items)
    families = sorted(list(set(df["indicator_family"].tolist())))
    summary = {
        "total_indicators": len(df),
        "total_families": len(families),
        "families": families,
        "status": "READY",
        "non_signal_guaranteed": True,
        "current_phase": profile.current_phase,
        "target_final_phase": profile.target_final_phase,
        "next_phase": profile.next_phase,
    }
    return df, summary
