import re

with open("commodity_fx_signal_bot/config/paths.py", "r") as f:
    content = f.read()

# Add definitions if they're missing above the class
new_paths = """
# Phase 43: Synthetic Indices
LAKE_SYNTHETIC_INDICES_DIR = LAKE_DIR / "synthetic_indices"
LAKE_SYNTHETIC_INDICES_DEFINITIONS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "definitions"
LAKE_SYNTHETIC_INDICES_LEVELS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "levels"
LAKE_SYNTHETIC_INDICES_RETURNS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "returns"
LAKE_SYNTHETIC_INDICES_RELATIVE_STRENGTH_DIR = LAKE_SYNTHETIC_INDICES_DIR / "relative_strength"
LAKE_SYNTHETIC_INDICES_RELATIVE_MOMENTUM_DIR = LAKE_SYNTHETIC_INDICES_DIR / "relative_momentum"
LAKE_SYNTHETIC_INDICES_ROTATION_DIR = LAKE_SYNTHETIC_INDICES_DIR / "rotation"
LAKE_SYNTHETIC_INDICES_LEADERSHIP_DIR = LAKE_SYNTHETIC_INDICES_DIR / "leadership"
LAKE_SYNTHETIC_INDICES_COMPARISONS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "comparisons"
LAKE_SYNTHETIC_INDICES_PERFORMANCE_DIR = LAKE_SYNTHETIC_INDICES_DIR / "performance"
LAKE_SYNTHETIC_INDICES_QUALITY_DIR = LAKE_SYNTHETIC_INDICES_DIR / "quality"

REPORTS_SYNTHETIC_INDICES_DIR = REPORTS_DIR / "synthetic_indices"
REPORTS_SYNTHETIC_INDICES_CSV_DIR = REPORTS_SYNTHETIC_INDICES_DIR / "csv"
REPORTS_SYNTHETIC_INDICES_MARKDOWN_DIR = REPORTS_SYNTHETIC_INDICES_DIR / "markdown"
REPORTS_SYNTHETIC_INDICES_TXT_DIR = REPORTS_SYNTHETIC_INDICES_DIR / "txt"

class ProjectPaths:
"""

if "LAKE_SYNTHETIC_INDICES_DIR =" not in content:
     content = content.replace("class ProjectPaths:", new_paths)

with open("commodity_fx_signal_bot/config/paths.py", "w") as f:
    f.write(content)
