import re

with open("commodity_fx_signal_bot/config/paths.py", "r") as f:
    content = f.read()

ensure_paths = """
        LAKE_SECURITY_READINESS_DIR,
        LAKE_SECURITY_QUALITY_DIR,
        REPORTS_SECURITY_REPORTS_DIR,
        LAKE_SYNTHETIC_INDICES_DIR,
        LAKE_SYNTHETIC_INDICES_DEFINITIONS_DIR,
        LAKE_SYNTHETIC_INDICES_LEVELS_DIR,
        LAKE_SYNTHETIC_INDICES_RETURNS_DIR,
        LAKE_SYNTHETIC_INDICES_RELATIVE_STRENGTH_DIR,
        LAKE_SYNTHETIC_INDICES_RELATIVE_MOMENTUM_DIR,
        LAKE_SYNTHETIC_INDICES_ROTATION_DIR,
        LAKE_SYNTHETIC_INDICES_LEADERSHIP_DIR,
        LAKE_SYNTHETIC_INDICES_COMPARISONS_DIR,
        LAKE_SYNTHETIC_INDICES_PERFORMANCE_DIR,
        LAKE_SYNTHETIC_INDICES_QUALITY_DIR,
        REPORTS_SYNTHETIC_INDICES_DIR,
        REPORTS_SYNTHETIC_INDICES_CSV_DIR,
        REPORTS_SYNTHETIC_INDICES_MARKDOWN_DIR,
        REPORTS_SYNTHETIC_INDICES_TXT_DIR,
    ]
"""

# Find REPORTS_SECURITY_REPORTS_DIR, and append the new paths
content = content.replace("        REPORTS_SECURITY_REPORTS_DIR,\n    ]", ensure_paths)

with open("commodity_fx_signal_bot/config/paths.py", "w") as f:
    f.write(content)
