import re

with open('commodity_fx_signal_bot/config/paths.py', 'r') as f:
    content = f.read()

# Replace all lines inside ensure_project_directories that are not indented properly
pattern = r"(\n)(LAKE_SCENARIO_REGRESSION_DIR,\nLAKE_SCENARIO_REGRESSION_REGISTRY_DIR,\nLAKE_SCENARIO_REGRESSION_GOLDEN_OUTPUTS_DIR,\nLAKE_SCENARIO_REGRESSION_SNAPSHOTS_DIR,\nLAKE_SCENARIO_REGRESSION_SNAPSHOT_DIFFS_DIR,\nLAKE_SCENARIO_REGRESSION_REPLAY_DIR,\nLAKE_SCENARIO_REGRESSION_FIXTURE_REPRODUCIBILITY_DIR,\nLAKE_SCENARIO_REGRESSION_OUTPUT_CONTRACTS_DIR,\nLAKE_SCENARIO_REGRESSION_DEMO_WORKFLOWS_DIR,\nLAKE_SCENARIO_REGRESSION_END_TO_END_ACCEPTANCE_DIR,\nLAKE_SCENARIO_REGRESSION_DRIFT_DIR,\nLAKE_SCENARIO_REGRESSION_FAILURES_DIR,\nLAKE_SCENARIO_REGRESSION_CHECKLISTS_DIR,\nLAKE_SCENARIO_REGRESSION_QUALITY_DIR,\nREPORTS_SCENARIO_REGRESSION_DIR,\nREPORTS_SCENARIO_REGRESSION_CSV_DIR,\nREPORTS_SCENARIO_REGRESSION_MARKDOWN_DIR,\nREPORTS_SCENARIO_REGRESSION_TXT_DIR,\nREPORTS_SCENARIO_REGRESSION_JSON_DIR,\nDOCS_SCENARIO_REGRESSION_DIR,)"

replacement = r"\1        LAKE_SCENARIO_REGRESSION_DIR,\n        LAKE_SCENARIO_REGRESSION_REGISTRY_DIR,\n        LAKE_SCENARIO_REGRESSION_GOLDEN_OUTPUTS_DIR,\n        LAKE_SCENARIO_REGRESSION_SNAPSHOTS_DIR,\n        LAKE_SCENARIO_REGRESSION_SNAPSHOT_DIFFS_DIR,\n        LAKE_SCENARIO_REGRESSION_REPLAY_DIR,\n        LAKE_SCENARIO_REGRESSION_FIXTURE_REPRODUCIBILITY_DIR,\n        LAKE_SCENARIO_REGRESSION_OUTPUT_CONTRACTS_DIR,\n        LAKE_SCENARIO_REGRESSION_DEMO_WORKFLOWS_DIR,\n        LAKE_SCENARIO_REGRESSION_END_TO_END_ACCEPTANCE_DIR,\n        LAKE_SCENARIO_REGRESSION_DRIFT_DIR,\n        LAKE_SCENARIO_REGRESSION_FAILURES_DIR,\n        LAKE_SCENARIO_REGRESSION_CHECKLISTS_DIR,\n        LAKE_SCENARIO_REGRESSION_QUALITY_DIR,\n        REPORTS_SCENARIO_REGRESSION_DIR,\n        REPORTS_SCENARIO_REGRESSION_CSV_DIR,\n        REPORTS_SCENARIO_REGRESSION_MARKDOWN_DIR,\n        REPORTS_SCENARIO_REGRESSION_TXT_DIR,\n        REPORTS_SCENARIO_REGRESSION_JSON_DIR,\n        DOCS_SCENARIO_REGRESSION_DIR,"

if "        LAKE_SCENARIO_REGRESSION_DIR" not in content:
    content = content.replace(
"""        LAKE_SCENARIO_REGRESSION_DIR,
        LAKE_SCENARIO_REGRESSION_REGISTRY_DIR,
        LAKE_SCENARIO_REGRESSION_GOLDEN_OUTPUTS_DIR,
        LAKE_SCENARIO_REGRESSION_SNAPSHOTS_DIR,
        LAKE_SCENARIO_REGRESSION_SNAPSHOT_DIFFS_DIR,
        LAKE_SCENARIO_REGRESSION_REPLAY_DIR,
        LAKE_SCENARIO_REGRESSION_FIXTURE_REPRODUCIBILITY_DIR,
        LAKE_SCENARIO_REGRESSION_OUTPUT_CONTRACTS_DIR,
        LAKE_SCENARIO_REGRESSION_DEMO_WORKFLOWS_DIR,
        LAKE_SCENARIO_REGRESSION_END_TO_END_ACCEPTANCE_DIR,
        LAKE_SCENARIO_REGRESSION_DRIFT_DIR,
        LAKE_SCENARIO_REGRESSION_FAILURES_DIR,
        LAKE_SCENARIO_REGRESSION_CHECKLISTS_DIR,
        LAKE_SCENARIO_REGRESSION_QUALITY_DIR,
        REPORTS_SCENARIO_REGRESSION_DIR,
        REPORTS_SCENARIO_REGRESSION_CSV_DIR,
        REPORTS_SCENARIO_REGRESSION_MARKDOWN_DIR,
        REPORTS_SCENARIO_REGRESSION_TXT_DIR,
        REPORTS_SCENARIO_REGRESSION_JSON_DIR,
        DOCS_SCENARIO_REGRESSION_DIR,
""", ""
    )
    content = content.replace(
"""LAKE_SCENARIO_REGRESSION_DIR,
LAKE_SCENARIO_REGRESSION_REGISTRY_DIR,
LAKE_SCENARIO_REGRESSION_GOLDEN_OUTPUTS_DIR,
LAKE_SCENARIO_REGRESSION_SNAPSHOTS_DIR,
LAKE_SCENARIO_REGRESSION_SNAPSHOT_DIFFS_DIR,
LAKE_SCENARIO_REGRESSION_REPLAY_DIR,
LAKE_SCENARIO_REGRESSION_FIXTURE_REPRODUCIBILITY_DIR,
LAKE_SCENARIO_REGRESSION_OUTPUT_CONTRACTS_DIR,
LAKE_SCENARIO_REGRESSION_DEMO_WORKFLOWS_DIR,
LAKE_SCENARIO_REGRESSION_END_TO_END_ACCEPTANCE_DIR,
LAKE_SCENARIO_REGRESSION_DRIFT_DIR,
LAKE_SCENARIO_REGRESSION_FAILURES_DIR,
LAKE_SCENARIO_REGRESSION_CHECKLISTS_DIR,
LAKE_SCENARIO_REGRESSION_QUALITY_DIR,
REPORTS_SCENARIO_REGRESSION_DIR,
REPORTS_SCENARIO_REGRESSION_CSV_DIR,
REPORTS_SCENARIO_REGRESSION_MARKDOWN_DIR,
REPORTS_SCENARIO_REGRESSION_TXT_DIR,
REPORTS_SCENARIO_REGRESSION_JSON_DIR,
DOCS_SCENARIO_REGRESSION_DIR,
""", ""
    )

    insert_idx = content.find("LAKE_COMMAND_CENTER_QUALITY_DIR,")
    insert_idx = content.find("\n", insert_idx) + 1

    new_dirs = """        LAKE_SCENARIO_REGRESSION_DIR,
        LAKE_SCENARIO_REGRESSION_REGISTRY_DIR,
        LAKE_SCENARIO_REGRESSION_GOLDEN_OUTPUTS_DIR,
        LAKE_SCENARIO_REGRESSION_SNAPSHOTS_DIR,
        LAKE_SCENARIO_REGRESSION_SNAPSHOT_DIFFS_DIR,
        LAKE_SCENARIO_REGRESSION_REPLAY_DIR,
        LAKE_SCENARIO_REGRESSION_FIXTURE_REPRODUCIBILITY_DIR,
        LAKE_SCENARIO_REGRESSION_OUTPUT_CONTRACTS_DIR,
        LAKE_SCENARIO_REGRESSION_DEMO_WORKFLOWS_DIR,
        LAKE_SCENARIO_REGRESSION_END_TO_END_ACCEPTANCE_DIR,
        LAKE_SCENARIO_REGRESSION_DRIFT_DIR,
        LAKE_SCENARIO_REGRESSION_FAILURES_DIR,
        LAKE_SCENARIO_REGRESSION_CHECKLISTS_DIR,
        LAKE_SCENARIO_REGRESSION_QUALITY_DIR,
        REPORTS_SCENARIO_REGRESSION_DIR,
        REPORTS_SCENARIO_REGRESSION_CSV_DIR,
        REPORTS_SCENARIO_REGRESSION_MARKDOWN_DIR,
        REPORTS_SCENARIO_REGRESSION_TXT_DIR,
        REPORTS_SCENARIO_REGRESSION_JSON_DIR,
        DOCS_SCENARIO_REGRESSION_DIR,
"""
    content = content[:insert_idx] + new_dirs + content[insert_idx:]

with open('commodity_fx_signal_bot/config/paths.py', 'w') as f:
    f.write(content)
