with open("commodity_fx_signal_bot/.env.example", "a") as f:
    f.write("\nSTRATEGY_CANDIDATES_ENABLED=true\n")
    f.write("STRATEGY_SELECTION_ENABLED=true\n")
    f.write("DEFAULT_STRATEGY_PROFILE=balanced_strategy_selection\n")
    f.write("DEFAULT_STRATEGY_TIMEFRAME=1d\n")
    f.write("STRATEGY_MIN_SELECTION_SCORE=0.45\n")
    f.write("STRATEGY_MIN_FIT_SCORE=0.45\n")
    f.write("STRATEGY_MIN_DECISION_CONFIDENCE=0.50\n")
    f.write("STRATEGY_MIN_DECISION_QUALITY=0.50\n")
    f.write("STRATEGY_MAX_CONFLICT_SCORE=0.65\n")
    f.write("STRATEGY_ALLOW_NO_TRADE_FAMILY=true\n")
    f.write("STRATEGY_ALLOW_WATCHLIST_FAMILY=true\n")
    f.write("SAVE_STRATEGY_CANDIDATES=true\n")
    f.write("SAVE_STRATEGY_POOL=true\n")
