import os
from pathlib import Path

def update_paths():
    paths_path = Path("commodity_fx_signal_bot/config/paths.py")
    if not paths_path.exists():
        return
    content = paths_path.read_text(encoding="utf-8")
    if "LAKE_LOCAL_PERFORMANCE_DIR" not in content:
        paths_to_add = """
# Phase 83: Local Performance Lake Directories
LAKE_LOCAL_PERFORMANCE_DIR = LAKE_DIR / "local_performance"
LAKE_LOCAL_PERFORMANCE_PROFILES_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "profiles"
LAKE_LOCAL_PERFORMANCE_DOMAINS_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "domains"
LAKE_LOCAL_PERFORMANCE_BUDGET_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "budget"
LAKE_LOCAL_PERFORMANCE_RUNTIME_PROFILE_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "runtime_profile"
LAKE_LOCAL_PERFORMANCE_RESOURCE_FOOTPRINT_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "resource_footprint"
LAKE_LOCAL_PERFORMANCE_CPU_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "cpu"
LAKE_LOCAL_PERFORMANCE_MEMORY_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "memory"
LAKE_LOCAL_PERFORMANCE_DISK_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "disk"
LAKE_LOCAL_PERFORMANCE_GROWTH_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "growth"
LAKE_LOCAL_PERFORMANCE_SCRIPT_RUNTIME_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "script_runtime"
LAKE_LOCAL_PERFORMANCE_TEST_RUNTIME_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "test_runtime"
LAKE_LOCAL_PERFORMANCE_PIPELINE_RUNTIME_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "pipeline_runtime"
LAKE_LOCAL_PERFORMANCE_MAINTENANCE_COST_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "maintenance_cost"
LAKE_LOCAL_PERFORMANCE_MAINTENANCE_EFFORT_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "maintenance_effort"
LAKE_LOCAL_PERFORMANCE_OPERATOR_TIME_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "operator_time"
LAKE_LOCAL_PERFORMANCE_MACHINE_SUITABILITY_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "machine_suitability"
LAKE_LOCAL_PERFORMANCE_EFFICIENCY_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "efficiency"
LAKE_LOCAL_PERFORMANCE_LIGHTWEIGHT_MODE_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "lightweight_mode"
LAKE_LOCAL_PERFORMANCE_WARNINGS_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "warnings"
LAKE_LOCAL_PERFORMANCE_RETENTION_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "retention"
LAKE_LOCAL_PERFORMANCE_NO_GO_SAFE_GO_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "no_go_safe_go"
LAKE_LOCAL_PERFORMANCE_EXCEPTIONS_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "exceptions"
LAKE_LOCAL_PERFORMANCE_GAPS_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "gaps"
LAKE_LOCAL_PERFORMANCE_RISKS_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "risks"
LAKE_LOCAL_PERFORMANCE_SCORING_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "scoring"
LAKE_LOCAL_PERFORMANCE_VALIDATION_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "validation"
LAKE_LOCAL_PERFORMANCE_QUALITY_DIR = LAKE_LOCAL_PERFORMANCE_DIR / "quality"
    
OUTPUT_LOCAL_PERFORMANCE_DIR = REPORTS_OUTPUT_DIR / "local_performance"
OUTPUT_LOCAL_PERFORMANCE_CSV_DIR = OUTPUT_LOCAL_PERFORMANCE_DIR / "csv"
OUTPUT_LOCAL_PERFORMANCE_MARKDOWN_DIR = OUTPUT_LOCAL_PERFORMANCE_DIR / "markdown"
OUTPUT_LOCAL_PERFORMANCE_TXT_DIR = OUTPUT_LOCAL_PERFORMANCE_DIR / "txt"
OUTPUT_LOCAL_PERFORMANCE_JSON_DIR = OUTPUT_LOCAL_PERFORMANCE_DIR / "json"
    
DOCS_GENERATED_LOCAL_PERFORMANCE_DIR = DOCS_DIR / "generated" / "local_performance"

"""
        # Append before `class ProjectPaths:`
        content = content.replace("class ProjectPaths:", paths_to_add + "class ProjectPaths:\n")
        
        # Now update ProjectPaths class definitions
        class_props = """
    @property
    def lake_local_performance_dir(self): return LAKE_LOCAL_PERFORMANCE_DIR
    @property
    def output_local_performance_dir(self): return OUTPUT_LOCAL_PERFORMANCE_DIR
    @property
    def docs_generated_local_performance_dir(self): return DOCS_GENERATED_LOCAL_PERFORMANCE_DIR
"""
        content = content.replace("class ProjectPaths:", "class ProjectPaths:\n" + class_props)

        # Update ProjectPaths class attributes (as done in other phases)
        class_attrs = """
    LAKE_LOCAL_PERFORMANCE_DIR: Path = LAKE_LOCAL_PERFORMANCE_DIR
    LAKE_LOCAL_PERFORMANCE_PROFILES_DIR: Path = LAKE_LOCAL_PERFORMANCE_PROFILES_DIR
    LAKE_LOCAL_PERFORMANCE_DOMAINS_DIR: Path = LAKE_LOCAL_PERFORMANCE_DOMAINS_DIR
    LAKE_LOCAL_PERFORMANCE_BUDGET_DIR: Path = LAKE_LOCAL_PERFORMANCE_BUDGET_DIR
    LAKE_LOCAL_PERFORMANCE_RUNTIME_PROFILE_DIR: Path = LAKE_LOCAL_PERFORMANCE_RUNTIME_PROFILE_DIR
    LAKE_LOCAL_PERFORMANCE_RESOURCE_FOOTPRINT_DIR: Path = LAKE_LOCAL_PERFORMANCE_RESOURCE_FOOTPRINT_DIR
    LAKE_LOCAL_PERFORMANCE_CPU_DIR: Path = LAKE_LOCAL_PERFORMANCE_CPU_DIR
    LAKE_LOCAL_PERFORMANCE_MEMORY_DIR: Path = LAKE_LOCAL_PERFORMANCE_MEMORY_DIR
    LAKE_LOCAL_PERFORMANCE_DISK_DIR: Path = LAKE_LOCAL_PERFORMANCE_DISK_DIR
    LAKE_LOCAL_PERFORMANCE_GROWTH_DIR: Path = LAKE_LOCAL_PERFORMANCE_GROWTH_DIR
    LAKE_LOCAL_PERFORMANCE_SCRIPT_RUNTIME_DIR: Path = LAKE_LOCAL_PERFORMANCE_SCRIPT_RUNTIME_DIR
    LAKE_LOCAL_PERFORMANCE_TEST_RUNTIME_DIR: Path = LAKE_LOCAL_PERFORMANCE_TEST_RUNTIME_DIR
    LAKE_LOCAL_PERFORMANCE_PIPELINE_RUNTIME_DIR: Path = LAKE_LOCAL_PERFORMANCE_PIPELINE_RUNTIME_DIR
    LAKE_LOCAL_PERFORMANCE_MAINTENANCE_COST_DIR: Path = LAKE_LOCAL_PERFORMANCE_MAINTENANCE_COST_DIR
    LAKE_LOCAL_PERFORMANCE_MAINTENANCE_EFFORT_DIR: Path = LAKE_LOCAL_PERFORMANCE_MAINTENANCE_EFFORT_DIR
    LAKE_LOCAL_PERFORMANCE_OPERATOR_TIME_DIR: Path = LAKE_LOCAL_PERFORMANCE_OPERATOR_TIME_DIR
    LAKE_LOCAL_PERFORMANCE_MACHINE_SUITABILITY_DIR: Path = LAKE_LOCAL_PERFORMANCE_MACHINE_SUITABILITY_DIR
    LAKE_LOCAL_PERFORMANCE_EFFICIENCY_DIR: Path = LAKE_LOCAL_PERFORMANCE_EFFICIENCY_DIR
    LAKE_LOCAL_PERFORMANCE_LIGHTWEIGHT_MODE_DIR: Path = LAKE_LOCAL_PERFORMANCE_LIGHTWEIGHT_MODE_DIR
    LAKE_LOCAL_PERFORMANCE_WARNINGS_DIR: Path = LAKE_LOCAL_PERFORMANCE_WARNINGS_DIR
    LAKE_LOCAL_PERFORMANCE_RETENTION_DIR: Path = LAKE_LOCAL_PERFORMANCE_RETENTION_DIR
    LAKE_LOCAL_PERFORMANCE_NO_GO_SAFE_GO_DIR: Path = LAKE_LOCAL_PERFORMANCE_NO_GO_SAFE_GO_DIR
    LAKE_LOCAL_PERFORMANCE_EXCEPTIONS_DIR: Path = LAKE_LOCAL_PERFORMANCE_EXCEPTIONS_DIR
    LAKE_LOCAL_PERFORMANCE_GAPS_DIR: Path = LAKE_LOCAL_PERFORMANCE_GAPS_DIR
    LAKE_LOCAL_PERFORMANCE_RISKS_DIR: Path = LAKE_LOCAL_PERFORMANCE_RISKS_DIR
    LAKE_LOCAL_PERFORMANCE_SCORING_DIR: Path = LAKE_LOCAL_PERFORMANCE_SCORING_DIR
    LAKE_LOCAL_PERFORMANCE_VALIDATION_DIR: Path = LAKE_LOCAL_PERFORMANCE_VALIDATION_DIR
    LAKE_LOCAL_PERFORMANCE_QUALITY_DIR: Path = LAKE_LOCAL_PERFORMANCE_QUALITY_DIR
    OUTPUT_LOCAL_PERFORMANCE_DIR: Path = OUTPUT_LOCAL_PERFORMANCE_DIR
    DOCS_GENERATED_LOCAL_PERFORMANCE_DIR: Path = DOCS_GENERATED_LOCAL_PERFORMANCE_DIR
"""
        content = content.replace("class ProjectPaths:\n", "class ProjectPaths:\n" + class_attrs)

        ensure_add = """
    LAKE_LOCAL_PERFORMANCE_DIR,
    LAKE_LOCAL_PERFORMANCE_PROFILES_DIR,
    LAKE_LOCAL_PERFORMANCE_DOMAINS_DIR,
    LAKE_LOCAL_PERFORMANCE_BUDGET_DIR,
    LAKE_LOCAL_PERFORMANCE_RUNTIME_PROFILE_DIR,
    LAKE_LOCAL_PERFORMANCE_RESOURCE_FOOTPRINT_DIR,
    LAKE_LOCAL_PERFORMANCE_CPU_DIR,
    LAKE_LOCAL_PERFORMANCE_MEMORY_DIR,
    LAKE_LOCAL_PERFORMANCE_DISK_DIR,
    LAKE_LOCAL_PERFORMANCE_GROWTH_DIR,
    LAKE_LOCAL_PERFORMANCE_SCRIPT_RUNTIME_DIR,
    LAKE_LOCAL_PERFORMANCE_TEST_RUNTIME_DIR,
    LAKE_LOCAL_PERFORMANCE_PIPELINE_RUNTIME_DIR,
    LAKE_LOCAL_PERFORMANCE_MAINTENANCE_COST_DIR,
    LAKE_LOCAL_PERFORMANCE_MAINTENANCE_EFFORT_DIR,
    LAKE_LOCAL_PERFORMANCE_OPERATOR_TIME_DIR,
    LAKE_LOCAL_PERFORMANCE_MACHINE_SUITABILITY_DIR,
    LAKE_LOCAL_PERFORMANCE_EFFICIENCY_DIR,
    LAKE_LOCAL_PERFORMANCE_LIGHTWEIGHT_MODE_DIR,
    LAKE_LOCAL_PERFORMANCE_WARNINGS_DIR,
    LAKE_LOCAL_PERFORMANCE_RETENTION_DIR,
    LAKE_LOCAL_PERFORMANCE_NO_GO_SAFE_GO_DIR,
    LAKE_LOCAL_PERFORMANCE_EXCEPTIONS_DIR,
    LAKE_LOCAL_PERFORMANCE_GAPS_DIR,
    LAKE_LOCAL_PERFORMANCE_RISKS_DIR,
    LAKE_LOCAL_PERFORMANCE_SCORING_DIR,
    LAKE_LOCAL_PERFORMANCE_VALIDATION_DIR,
    LAKE_LOCAL_PERFORMANCE_QUALITY_DIR,
    OUTPUT_LOCAL_PERFORMANCE_DIR,
    DOCS_GENERATED_LOCAL_PERFORMANCE_DIR,
"""
        # We need to insert this into the list returned by ensure_project_directories (or dirs_to_create)
        content = content.replace("def ensure_project_directories() -> None:\n    dirs_to_create = [", "def ensure_project_directories() -> None:\n    dirs_to_create = [" + ensure_add)
        
        paths_path.write_text(content, encoding="utf-8")
        print("Updated paths.py")

if __name__ == "__main__":
    update_paths()
