with open("commodity_fx_signal_bot/.env.example", "r") as f:
    content = f.read()

maintenance_env = """
# Maintenance Settings
MAINTENANCE_ENABLED=true
DEFAULT_MAINTENANCE_PROFILE=balanced_local_maintenance
MAINTENANCE_DEFAULT_TIMEFRAME=1d
MAINTENANCE_DRY_RUN_DEFAULT=true
MAINTENANCE_ALLOW_DELETE=false
MAINTENANCE_ALLOW_ARCHIVE_MOVE=false
MAINTENANCE_SCAN_DATA_LAKE=true
MAINTENANCE_SCAN_REPORTS_OUTPUT=true
MAINTENANCE_SCAN_LOGS=true
MAINTENANCE_SCAN_CACHE=true
MAINTENANCE_SCAN_CHECKPOINTS=true
MAINTENANCE_MAX_INVENTORY_FILES=50000
MAINTENANCE_LARGE_FILE_THRESHOLD_MB=100
MAINTENANCE_STALE_DAYS_DEFAULT=30
MAINTENANCE_KEEP_LATEST_N_REPORTS=10
MAINTENANCE_KEEP_LATEST_N_RUNS=20
MAINTENANCE_KEEP_QUALITY_REPORTS_DAYS=90
MAINTENANCE_KEEP_GOVERNANCE_REPORTS_DAYS=180
MAINTENANCE_KEEP_EXPERIMENT_MANIFESTS_DAYS=365
MAINTENANCE_KEEP_KNOWLEDGE_INDEX_DAYS=30
MAINTENANCE_KEEP_CACHE_DAYS=14
MAINTENANCE_KEEP_CHECKPOINTS_DAYS=30
MAINTENANCE_ARCHIVE_FORMAT=zip_manifest_only
MAINTENANCE_ARCHIVE_MAX_BUNDLE_MB=1024
MAINTENANCE_SAVE_REPORTS=true
MAINTENANCE_MIN_QUALITY_SCORE=0.40
"""

if "MAINTENANCE_ENABLED" not in content:
    with open("commodity_fx_signal_bot/.env.example", "a") as f:
        f.write(maintenance_env)
    print(".env.example patched")
else:
    print(".env.example already patched")
