import re

file_path = "commodity_fx_signal_bot/config/paths.py"
with open(file_path, "r") as f:
    content = f.read()

paths_injection = """
        # Phase 66: Local Knowledge Graph
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_NODES_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_NODES_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_EDGES_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_EDGES_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_GRAPHS_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_MODULE_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_MODULE_GRAPHS_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_REPORT_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_REPORT_GRAPHS_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_EVIDENCE_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_EVIDENCE_GRAPHS_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_CARD_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_CARD_GRAPHS_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_SCENARIO_REGRESSION_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_SCENARIO_REGRESSION_GRAPHS_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_COMMAND_REPORT_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_COMMAND_REPORT_GRAPHS_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_SEMANTIC_INDEX_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_SEMANTIC_INDEX_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_TFIDF_INDEX_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_TFIDF_INDEX_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_QUERIES_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_QUERIES_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_NEIGHBORHOODS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_NEIGHBORHOODS_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_ANALYSIS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_ANALYSIS_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_GAPS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_GAPS_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_EXPORTS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_EXPORTS_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_VALIDATION_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_VALIDATION_DIR
        self.LAKE_LOCAL_KNOWLEDGE_GRAPH_QUALITY_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_QUALITY_DIR

        self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_DIR = REPORTS_LOCAL_KNOWLEDGE_GRAPH_DIR
        self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_CSV_DIR = REPORTS_LOCAL_KNOWLEDGE_GRAPH_CSV_DIR
        self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_MARKDOWN_DIR = REPORTS_LOCAL_KNOWLEDGE_GRAPH_MARKDOWN_DIR
        self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_TXT_DIR = REPORTS_LOCAL_KNOWLEDGE_GRAPH_TXT_DIR
        self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_JSON_DIR = REPORTS_LOCAL_KNOWLEDGE_GRAPH_JSON_DIR
        self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_GRAPHML_DIR = REPORTS_LOCAL_KNOWLEDGE_GRAPH_GRAPHML_DIR

        self.DOCS_LOCAL_KNOWLEDGE_GRAPH_DIR = DOCS_LOCAL_KNOWLEDGE_GRAPH_DIR

"""

content = re.sub(r'# Phase 39: Research Reports', paths_injection + '# Phase 39: Research Reports', content, count=1)

paths_constants_injection = """
# Phase 66: Local Knowledge Graph
LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR = LAKE_DIR / "local_knowledge_graph"
LAKE_LOCAL_KNOWLEDGE_GRAPH_NODES_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "nodes"
LAKE_LOCAL_KNOWLEDGE_GRAPH_EDGES_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "edges"
LAKE_LOCAL_KNOWLEDGE_GRAPH_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "graphs"
LAKE_LOCAL_KNOWLEDGE_GRAPH_MODULE_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "module_graphs"
LAKE_LOCAL_KNOWLEDGE_GRAPH_REPORT_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "report_graphs"
LAKE_LOCAL_KNOWLEDGE_GRAPH_EVIDENCE_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "evidence_graphs"
LAKE_LOCAL_KNOWLEDGE_GRAPH_CARD_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "card_graphs"
LAKE_LOCAL_KNOWLEDGE_GRAPH_SCENARIO_REGRESSION_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "scenario_regression_graphs"
LAKE_LOCAL_KNOWLEDGE_GRAPH_COMMAND_REPORT_GRAPHS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "command_report_graphs"
LAKE_LOCAL_KNOWLEDGE_GRAPH_SEMANTIC_INDEX_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "semantic_index"
LAKE_LOCAL_KNOWLEDGE_GRAPH_TFIDF_INDEX_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "tfidf_index"
LAKE_LOCAL_KNOWLEDGE_GRAPH_QUERIES_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "queries"
LAKE_LOCAL_KNOWLEDGE_GRAPH_NEIGHBORHOODS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "neighborhoods"
LAKE_LOCAL_KNOWLEDGE_GRAPH_ANALYSIS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "analysis"
LAKE_LOCAL_KNOWLEDGE_GRAPH_GAPS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "gaps"
LAKE_LOCAL_KNOWLEDGE_GRAPH_EXPORTS_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "exports"
LAKE_LOCAL_KNOWLEDGE_GRAPH_VALIDATION_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "validation"
LAKE_LOCAL_KNOWLEDGE_GRAPH_QUALITY_DIR = LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR / "quality"

REPORTS_LOCAL_KNOWLEDGE_GRAPH_DIR = REPORTS_DIR / "local_knowledge_graph"
REPORTS_LOCAL_KNOWLEDGE_GRAPH_CSV_DIR = REPORTS_LOCAL_KNOWLEDGE_GRAPH_DIR / "csv"
REPORTS_LOCAL_KNOWLEDGE_GRAPH_MARKDOWN_DIR = REPORTS_LOCAL_KNOWLEDGE_GRAPH_DIR / "markdown"
REPORTS_LOCAL_KNOWLEDGE_GRAPH_TXT_DIR = REPORTS_LOCAL_KNOWLEDGE_GRAPH_DIR / "txt"
REPORTS_LOCAL_KNOWLEDGE_GRAPH_JSON_DIR = REPORTS_LOCAL_KNOWLEDGE_GRAPH_DIR / "json"
REPORTS_LOCAL_KNOWLEDGE_GRAPH_GRAPHML_DIR = REPORTS_LOCAL_KNOWLEDGE_GRAPH_DIR / "graphml"

DOCS_LOCAL_KNOWLEDGE_GRAPH_DIR = PROJECT_ROOT / "docs" / "generated" / "local_knowledge_graph"

"""

content = content + paths_constants_injection

paths_create_injection = """
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_NODES_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_EDGES_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_GRAPHS_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_MODULE_GRAPHS_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_REPORT_GRAPHS_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_EVIDENCE_GRAPHS_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_CARD_GRAPHS_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_SCENARIO_REGRESSION_GRAPHS_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_COMMAND_REPORT_GRAPHS_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_SEMANTIC_INDEX_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_TFIDF_INDEX_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_QUERIES_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_NEIGHBORHOODS_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_ANALYSIS_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_GAPS_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_EXPORTS_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_VALIDATION_DIR,
            self.LAKE_LOCAL_KNOWLEDGE_GRAPH_QUALITY_DIR,

            self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_DIR,
            self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_CSV_DIR,
            self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_MARKDOWN_DIR,
            self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_TXT_DIR,
            self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_JSON_DIR,
            self.REPORTS_LOCAL_KNOWLEDGE_GRAPH_GRAPHML_DIR,

            self.DOCS_LOCAL_KNOWLEDGE_GRAPH_DIR,
"""

content = re.sub(r'            self.DOCS_PORTABLE_PACKAGING_DIR,', '            self.DOCS_PORTABLE_PACKAGING_DIR,' + paths_create_injection, content)

with open(file_path, "w") as f:
    f.write(content)
