with open("commodity_fx_signal_bot/.env.example", "a") as f:
    f.write("\n# Phase 43: Synthetic Benchmark Baskets & Composite Indices\n")
    f.write("SYNTHETIC_INDICES_ENABLED=true\n")
    f.write("DEFAULT_SYNTHETIC_INDEX_PROFILE=balanced_synthetic_index_research\n")
    f.write("SYNTHETIC_INDEX_DEFAULT_TIMEFRAME=1d\n")
    f.write("SYNTHETIC_INDEX_BASE_VALUE=100\n")
    f.write("SYNTHETIC_INDEX_RETURN_METHOD=log\n")
    f.write("SYNTHETIC_INDEX_REBALANCE_METHOD=static\n")
    f.write("SYNTHETIC_INDEX_REBALANCE_FREQUENCY=monthly\n")
    f.write("SYNTHETIC_INDEX_MIN_SYMBOLS=3\n")
    f.write("SYNTHETIC_INDEX_MIN_OBSERVATIONS=120\n")
    f.write("SYNTHETIC_INDEX_MAX_SYMBOLS_PER_INDEX=20\n")
    f.write("SYNTHETIC_INDEX_MAX_SINGLE_WEIGHT=0.35\n")
    f.write("SYNTHETIC_INDEX_RELATIVE_STRENGTH_WINDOWS=20,60,120\n")
    f.write("SYNTHETIC_INDEX_ROTATION_LOOKBACK=60\n")
    f.write("SYNTHETIC_INDEX_ROTATION_TOP_N=5\n")
    f.write("SYNTHETIC_INDEX_ROTATION_BOTTOM_N=5\n")
    f.write("SYNTHETIC_INDEX_SAVE_DEFINITIONS=true\n")
    f.write("SYNTHETIC_INDEX_SAVE_LEVELS=true\n")
    f.write("SYNTHETIC_INDEX_SAVE_REPORTS=true\n")
    f.write("SYNTHETIC_INDEX_MIN_QUALITY_SCORE=0.40\n")
