# -*- coding: utf-8 -*-
"""Unit tests for Phase 155 Risk Reporting Labels."""

from advanced_risk_reporting.risk_reporting_labels import (
    RISK_REPORTING_PROFILE_DOMAIN,
    RISK_REPORT_CONTRACT_DOMAIN,
    EXPOSURE_ATTRIBUTION_DOMAIN,
    LIMIT_MONITORING_DOMAIN,
    RISK_SUMMARY_DOMAIN,
    EXPOSURE_SUMMARY_DOMAIN,
    EXPOSURE_PLACEHOLDER_DOMAIN,
    RISK_CONTRIBUTION_PLACEHOLDER_DOMAIN,
    RISK_MONITOR_PLACEHOLDER_DOMAIN,
    LIMIT_DEFINITION_DOMAIN,
    LIMIT_BREACH_PLACEHOLDER_DOMAIN,
    RISK_ALERT_PLACEHOLDER_DOMAIN,
    DASHBOARD_PLACEHOLDER_DOMAIN,
    MONITORING_SCHEDULE_PLACEHOLDER_DOMAIN,
    OUTPUT_CONTRACT_DOMAIN,
    METRIC_PLACEHOLDER_DOMAIN,
    DEPENDENCY_DOMAIN,
    CLAIM_GUARD_DOMAIN,
    DISABLED_EXECUTION_DOMAIN,
    FINDING_DOMAIN,
    READINESS_SCORE_DOMAIN,
    MANIFEST_DOMAIN,
    HEALTH_DOMAIN,
    VALIDATION_DOMAIN,
    SAFETY_DOMAIN,
    PHASE_156_HANDOFF_DOMAIN,
    ALL_DOMAINS,
    RISK_REPORT_CONTRACT_READY,
    RISK_REPORT_CONTRACT_READY_WITH_WARNINGS,
    RISK_REPORT_CONTRACT_MANUAL_REVIEW_REQUIRED,
    RISK_REPORT_CONTRACT_BLOCKED_BY_SAFETY,
    RISK_REPORT_CONTRACT_ONLY,
    ALL_STATUSES,
    EXECUTION_BLOCKED_NO_RISK_REPORT,
    EXECUTION_BLOCKED_NO_EXPOSURE_ATTRIBUTION,
    EXECUTION_BLOCKED_NO_LIMIT_MONITORING,
    EXECUTION_BLOCKED_NO_METRIC_CALCULATION,
    EXECUTION_BLOCKED_NO_ALERTING,
    EXECUTION_BLOCKED_NO_DASHBOARD,
    EXECUTION_BLOCKED_NO_PORTFOLIO_ADJUSTMENT,
    EXECUTION_CONTRACT_ONLY,
    ALL_EXECUTION_LABELS,
)


def test_domain_labels():
    assert len(ALL_DOMAINS) >= 20
    assert RISK_REPORTING_PROFILE_DOMAIN in ALL_DOMAINS
    assert RISK_REPORT_CONTRACT_DOMAIN in ALL_DOMAINS
    assert EXPOSURE_ATTRIBUTION_DOMAIN in ALL_DOMAINS
    assert LIMIT_MONITORING_DOMAIN in ALL_DOMAINS
    assert PHASE_156_HANDOFF_DOMAIN in ALL_DOMAINS


def test_status_labels():
    assert len(ALL_STATUSES) >= 5
    assert RISK_REPORT_CONTRACT_READY in ALL_STATUSES
    assert RISK_REPORT_CONTRACT_ONLY in ALL_STATUSES


def test_execution_labels():
    assert len(ALL_EXECUTION_LABELS) >= 10
    assert EXECUTION_BLOCKED_NO_RISK_REPORT in ALL_EXECUTION_LABELS
    assert EXECUTION_BLOCKED_NO_LIMIT_MONITORING in ALL_EXECUTION_LABELS
    assert EXECUTION_CONTRACT_ONLY in ALL_EXECUTION_LABELS
