"""
Path definitions and directory management for the project.
"""

from pathlib import Path

# Project root directory
PROJECT_ROOT = Path(__file__).parent.parent.resolve()

# Base directories
DATA_DIR = PROJECT_ROOT / "data"
LOGS_DIR = PROJECT_ROOT / "logs"
DOCS_DIR = PROJECT_ROOT / "docs"
REPORTS_DIR = PROJECT_ROOT / "reports"
REPORTS_OUTPUT_DIR = REPORTS_DIR / "output" / "output"

REPORTS_VALIDATION_DIR = REPORTS_DIR / "validation_reports"

# Meta Research paths
REPORTS_META_RESEARCH_DIR = REPORTS_DIR / "meta_research"
REPORTS_META_RESEARCH_CSV_DIR = REPORTS_META_RESEARCH_DIR / "csv"
REPORTS_META_RESEARCH_MD_DIR = REPORTS_META_RESEARCH_DIR / "markdown"
REPORTS_META_RESEARCH_TXT_DIR = REPORTS_META_RESEARCH_DIR / "txt"


# Specific data directories
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
CACHE_DIR = DATA_DIR / "cache"

# Data Lake directories
LAKE_DIR = DATA_DIR / "lake"
LAKE_OHLCV_DIR = LAKE_DIR / "ohlcv"
LAKE_MACRO_DIR = LAKE_DIR / "macro"
LAKE_MACRO_RAW_DIR = LAKE_MACRO_DIR / "raw"
LAKE_MACRO_PROCESSED_DIR = LAKE_MACRO_DIR / "processed"
LAKE_BENCHMARKS_DIR = LAKE_DIR / "benchmarks"
LAKE_SYNTHETIC_DIR = LAKE_DIR / "synthetic"
LAKE_MANIFESTS_DIR = LAKE_DIR / "manifests"
LAKE_JOURNALS_DIR = LAKE_DIR / "journals"

# Phase 36: Observability Lake Directories
LAKE_OBSERVABILITY_DIR = LAKE_DIR / "observability"
LAKE_OBSERVABILITY_LOGS_DIR = LAKE_OBSERVABILITY_DIR / "logs"
LAKE_OBSERVABILITY_JSON_LOGS_DIR = LAKE_OBSERVABILITY_DIR / "json_logs"
LAKE_OBSERVABILITY_HEALTH_DIR = LAKE_OBSERVABILITY_DIR / "health"
LAKE_OBSERVABILITY_RUNTIME_METRICS_DIR = LAKE_OBSERVABILITY_DIR / "runtime_metrics"
LAKE_OBSERVABILITY_DIAGNOSTICS_DIR = LAKE_OBSERVABILITY_DIR / "diagnostics"
LAKE_OBSERVABILITY_ERROR_TAXONOMY_DIR = LAKE_OBSERVABILITY_DIR / "error_taxonomy"
LAKE_OBSERVABILITY_DATA_FRESHNESS_DIR = LAKE_OBSERVABILITY_DIR / "data_freshness"
LAKE_OBSERVABILITY_ARTIFACT_INTEGRITY_DIR = LAKE_OBSERVABILITY_DIR / "artifact_integrity"
LAKE_OBSERVABILITY_QUALITY_DIR = LAKE_OBSERVABILITY_DIR / "quality"
REPORTS_OBSERVABILITY_DIR = REPORTS_DIR / "observability_reports"


# Processed Lake Directories
LAKE_PROCESSED_DIR = LAKE_DIR / "processed"
LAKE_PROCESSED_OHLCV_DIR = LAKE_PROCESSED_DIR / "ohlcv"
LAKE_QUALITY_REPORTS_DIR = LAKE_PROCESSED_DIR / "quality_reports"
LAKE_CLEANING_REPORTS_DIR = LAKE_PROCESSED_DIR / "cleaning_reports"

# Feature Lake Directories
LAKE_FEATURES_DIR = LAKE_DIR / "features"
LAKE_FEATURES_TECHNICAL_DIR = LAKE_FEATURES_DIR / "technical"
LAKE_FEATURES_MANIFESTS_DIR = LAKE_FEATURES_DIR / "manifests"
LAKE_FEATURES_REPORTS_DIR = LAKE_FEATURES_DIR / "reports"

INDICATOR_REPORTS_DIR = REPORTS_DIR / "indicator_reports"
LAKE_FEATURES_MOMENTUM_DIR = LAKE_FEATURES_DIR / "momentum"
LAKE_FEATURES_MOMENTUM_EVENTS_DIR = LAKE_FEATURES_DIR / "momentum_events"
MOMENTUM_REPORTS_DIR = REPORTS_DIR / "momentum_reports"

LAKE_FEATURES_TREND_DIR = LAKE_FEATURES_DIR / "trend"
LAKE_FEATURES_TREND_EVENTS_DIR = LAKE_FEATURES_DIR / "trend_events"

LAKE_FEATURES_TREND_DIR = LAKE_FEATURES_DIR / "trend"
LAKE_FEATURES_TREND_EVENTS_DIR = LAKE_FEATURES_DIR / "trend_events"
TREND_REPORTS_DIR = REPORTS_DIR / "trend_reports"


LAKE_FEATURES_VOLATILITY_DIR = LAKE_FEATURES_DIR / "volatility"
LAKE_FEATURES_VOLATILITY_EVENTS_DIR = LAKE_FEATURES_DIR / "volatility_events"
VOLATILITY_REPORTS_DIR = REPORTS_DIR / "volatility_reports"

LAKE_FEATURES_PRICE_ACTION_DIR = LAKE_FEATURES_DIR / "price_action"
LAKE_FEATURES_PRICE_ACTION_EVENTS_DIR = LAKE_FEATURES_DIR / "price_action_events"
PRICE_ACTION_REPORTS_DIR = REPORTS_DIR / "price_action_reports"

LAKE_FEATURES_DIVERGENCE_DIR = LAKE_FEATURES_DIR / "divergence"
LAKE_FEATURES_DIVERGENCE_EVENTS_DIR = LAKE_FEATURES_DIR / "divergence_events"
DIVERGENCE_REPORTS_DIR = REPORTS_DIR / "divergence_reports"


LAKE_FEATURES_MTF_DIR = LAKE_FEATURES_DIR / "mtf"
LAKE_FEATURES_MTF_EVENTS_DIR = LAKE_FEATURES_DIR / "mtf_events"
MTF_REPORTS_DIR = REPORTS_DIR / "mtf_reports"


LAKE_FEATURES_REGIME_DIR = LAKE_FEATURES_DIR / "regime"
LAKE_FEATURES_REGIME_EVENTS_DIR = LAKE_FEATURES_DIR / "regime_events"
REGIME_REPORTS_DIR = REPORTS_DIR / "regime_reports"

LAKE_FEATURES_MACRO_DIR = LAKE_FEATURES_DIR / "macro"
LAKE_FEATURES_MACRO_EVENTS_DIR = LAKE_FEATURES_DIR / "macro_events"
LAKE_FEATURES_BENCHMARKS_DIR = LAKE_FEATURES_DIR / "benchmarks"
MACRO_REPORTS_DIR = REPORTS_DIR / "macro_reports"

LAKE_TMP_DIR = LAKE_DIR / "tmp"


LAKE_FEATURES_ASSET_PROFILES_DIR = LAKE_FEATURES_DIR / "asset_profiles"
LAKE_FEATURES_ASSET_PROFILE_EVENTS_DIR = LAKE_FEATURES_DIR / "asset_profile_events"
LAKE_FEATURES_GROUP_FEATURES_DIR = LAKE_FEATURES_DIR / "group_features"
ASSET_PROFILE_REPORTS_DIR = REPORTS_DIR / "asset_profile_reports"

LAKE_FEATURES_SIGNAL_CANDIDATES_DIR = LAKE_FEATURES_DIR / "signal_candidates"
LAKE_FEATURES_SIGNAL_POOL_DIR = LAKE_FEATURES_DIR / "signal_pool"
SIGNAL_REPORTS_DIR = REPORTS_DIR / "signal_reports"
LAKE_FEATURES_DECISION_CANDIDATES_DIR = LAKE_FEATURES_DIR / "decision_candidates"
LAKE_FEATURES_DECISION_POOL_DIR = LAKE_FEATURES_DIR / "decision_pool"
DECISION_REPORTS_DIR = REPORTS_DIR / "decision_reports"

LAKE_FEATURES_STRATEGY_CANDIDATES_DIR = LAKE_FEATURES_DIR / "strategy_candidates"
LAKE_FEATURES_STRATEGY_POOL_DIR = LAKE_FEATURES_DIR / "strategy_pool"
STRATEGY_REPORTS_DIR = REPORTS_DIR / "strategy_reports"

LAKE_FEATURES_STRATEGY_RULE_CANDIDATES_DIR = (
    LAKE_FEATURES_DIR / "strategy_rule_candidates"
)
LAKE_FEATURES_ENTRY_EXIT_CANDIDATES_DIR = LAKE_FEATURES_DIR / "entry_exit_candidates"
LAKE_FEATURES_STRATEGY_RULE_POOL_DIR = LAKE_FEATURES_DIR / "strategy_rule_pool"
STRATEGY_RULE_REPORTS_DIR = REPORTS_DIR / "strategy_rule_reports"



# Phase 29: ML Dataset Preparation
LAKE_ML_DIR = LAKE_DIR / "ml"
LAKE_ML_FEATURES_DIR = LAKE_ML_DIR / "features"
LAKE_ML_TARGETS_DIR = LAKE_ML_DIR / "targets"
LAKE_ML_DATASETS_DIR = LAKE_ML_DIR / "datasets"
LAKE_ML_SPLITS_DIR = LAKE_ML_DIR / "splits"
LAKE_ML_METADATA_DIR = LAKE_ML_DIR / "metadata"
LAKE_ML_QUALITY_DIR = LAKE_ML_DIR / "quality"

# ML Training Directories
LAKE_ML_MODELS_DIR = LAKE_ML_DIR / "models"
LAKE_ML_MODEL_ARTIFACTS_DIR = LAKE_ML_DIR / "model_artifacts"
LAKE_ML_MODEL_REGISTRY_DIR = LAKE_ML_DIR / "model_registry"
LAKE_ML_MODEL_EVALUATIONS_DIR = LAKE_ML_DIR / "model_evaluations"
LAKE_ML_MODEL_CV_DIR = LAKE_ML_DIR / "model_cv"
LAKE_ML_MODEL_QUALITY_DIR = LAKE_ML_DIR / "model_quality"

REPORTS_ML_TRAINING_REPORTS_DIR = REPORTS_DIR / "ml_training_reports"
REPORTS_ML_REPORTS_DIR = REPORTS_DIR / "ml_reports"

# Phase 32: ML Context Integration
LAKE_ML_INTEGRATION_DIR = LAKE_ML_DIR / "integration"
LAKE_ML_INTEGRATION_FEATURES_DIR = LAKE_ML_INTEGRATION_DIR / "features"
LAKE_ML_INTEGRATION_ALIGNMENT_DIR = LAKE_ML_INTEGRATION_DIR / "alignment"
LAKE_ML_INTEGRATION_CONFLICTS_DIR = LAKE_ML_INTEGRATION_DIR / "conflicts"
LAKE_ML_INTEGRATION_QUALITY_DIR = LAKE_ML_INTEGRATION_DIR / "quality"
REPORTS_ML_INTEGRATION_REPORTS_DIR = REPORTS_DIR / "ml_integration_reports"



# Phase 33: Paper Trading Simulation
LAKE_PAPER_DIR = LAKE_DIR / "paper"
LAKE_PAPER_RUNS_DIR = LAKE_PAPER_DIR / "runs"
LAKE_PAPER_ORDERS_DIR = LAKE_PAPER_DIR / "orders"
LAKE_PAPER_ORDER_BOOKS_DIR = LAKE_PAPER_DIR / "order_books"
LAKE_PAPER_POSITIONS_DIR = LAKE_PAPER_DIR / "positions"
LAKE_PAPER_PORTFOLIOS_DIR = LAKE_PAPER_DIR / "portfolios"
LAKE_PAPER_LEDGERS_DIR = LAKE_PAPER_DIR / "ledgers"
LAKE_PAPER_EQUITY_CURVES_DIR = LAKE_PAPER_DIR / "equity_curves"
LAKE_PAPER_AUDITS_DIR = LAKE_PAPER_DIR / "audits"
LAKE_PAPER_QUALITY_DIR = LAKE_PAPER_DIR / "quality"
PAPER_REPORTS_DIR = REPORTS_DIR / "paper_reports"

LAKE_NOTIFICATIONS_DIR = LAKE_DIR / "notifications"
LAKE_NOTIFICATIONS_MESSAGES_DIR = LAKE_NOTIFICATIONS_DIR / "messages"
LAKE_NOTIFICATIONS_DELIVERY_LOGS_DIR = LAKE_NOTIFICATIONS_DIR / "delivery_logs"
LAKE_NOTIFICATIONS_AUDITS_DIR = LAKE_NOTIFICATIONS_DIR / "audits"
LAKE_NOTIFICATIONS_QUALITY_DIR = LAKE_NOTIFICATIONS_DIR / "quality"
NOTIFICATION_REPORT_OUTPUT_DIR = REPORTS_DIR / "notification_reports"




# Orchestration Output Directories
LAKE_ORCHESTRATION_DIR = DATA_DIR / "orchestration"
LAKE_ORCHESTRATION_RUNS_DIR = LAKE_ORCHESTRATION_DIR / "runs"
LAKE_ORCHESTRATION_MANIFESTS_DIR = LAKE_ORCHESTRATION_DIR / "manifests"
LAKE_ORCHESTRATION_DEPENDENCY_GRAPHS_DIR = LAKE_ORCHESTRATION_DIR / "dependency_graphs"
LAKE_ORCHESTRATION_EXECUTION_PLANS_DIR = LAKE_ORCHESTRATION_DIR / "execution_plans"
LAKE_ORCHESTRATION_JOB_LOGS_DIR = LAKE_ORCHESTRATION_DIR / "job_logs"
LAKE_ORCHESTRATION_QUALITY_DIR = LAKE_ORCHESTRATION_DIR / "quality"
ORCHESTRATION_REPORT_OUTPUT_DIR = REPORTS_DIR / "orchestration_reports"



# Phase 37: Security
LAKE_SECURITY_DIR = LAKE_DIR / "security"
LAKE_SECURITY_AUDITS_DIR = LAKE_SECURITY_DIR / "audits"
LAKE_SECURITY_SECRET_HYGIENE_DIR = LAKE_SECURITY_DIR / "secret_hygiene"
LAKE_SECURITY_CONFIG_HARDENING_DIR = LAKE_SECURITY_DIR / "config_hardening"
LAKE_SECURITY_SAFE_DEFAULTS_DIR = LAKE_SECURITY_DIR / "safe_defaults"
LAKE_SECURITY_PERMISSIONS_DIR = LAKE_SECURITY_DIR / "permissions"
LAKE_SECURITY_PATH_SAFETY_DIR = LAKE_SECURITY_DIR / "path_safety"
LAKE_SECURITY_TOKEN_SCANS_DIR = LAKE_SECURITY_DIR / "token_scans"
LAKE_SECURITY_READINESS_DIR = LAKE_SECURITY_DIR / "readiness"
LAKE_SECURITY_QUALITY_DIR = LAKE_SECURITY_DIR / "quality"
REPORTS_SECURITY_REPORTS_DIR = REPORTS_DIR / "security_reports"


# Phase 40: Report Exports, Archive and Comparisons
LAKE_REPORT_EXPORTS_DIR = LAKE_DIR / "report_exports"
LAKE_REPORT_EXPORTS_MANIFESTS_DIR = LAKE_REPORT_EXPORTS_DIR / "manifests"
LAKE_REPORT_EXPORTS_ARCHIVE_DIR = LAKE_REPORT_EXPORTS_DIR / "archive"
LAKE_REPORT_EXPORTS_COMPARISONS_DIR = LAKE_REPORT_EXPORTS_DIR / "comparisons"
LAKE_REPORT_EXPORTS_TRACKING_DIR = LAKE_REPORT_EXPORTS_DIR / "tracking"
LAKE_REPORT_EXPORTS_PACKAGES_DIR = LAKE_REPORT_EXPORTS_DIR / "packages"
LAKE_REPORT_EXPORTS_QUALITY_DIR = LAKE_REPORT_EXPORTS_DIR / "quality"

REPORTS_REPORT_EXPORTS_DIR = REPORTS_DIR / "report_exports"
REPORTS_REPORT_EXPORTS_HTML_DIR = REPORTS_REPORT_EXPORTS_DIR / "html"
REPORTS_REPORT_EXPORTS_PDF_DIR = REPORTS_REPORT_EXPORTS_DIR / "pdf"
REPORTS_REPORT_EXPORTS_CSV_DIR = REPORTS_REPORT_EXPORTS_DIR / "csv"
REPORTS_REPORT_EXPORTS_PACKAGES_DIR = REPORTS_REPORT_EXPORTS_DIR / "packages"
REPORTS_REPORT_EXPORTS_COMPARISONS_DIR = REPORTS_REPORT_EXPORTS_DIR / "comparisons"
REPORTS_REPORT_EXPORTS_TRACKING_DIR = REPORTS_REPORT_EXPORTS_DIR / "tracking"


# Phase 42: Portfolio Regime Research
LAKE_PORTFOLIO_REGIME_DIR = LAKE_DIR / "portfolio_regime"
LAKE_PORTFOLIO_REGIME_REGIMES_DIR = LAKE_PORTFOLIO_REGIME_DIR / "regimes"
LAKE_PORTFOLIO_REGIME_CONDITIONED_RETURNS_DIR = LAKE_PORTFOLIO_REGIME_DIR / "conditioned_returns"
LAKE_PORTFOLIO_REGIME_CORRELATION_DIR = LAKE_PORTFOLIO_REGIME_DIR / "correlation"
LAKE_PORTFOLIO_REGIME_SCENARIOS_DIR = LAKE_PORTFOLIO_REGIME_DIR / "scenarios"
LAKE_PORTFOLIO_REGIME_STRESS_TESTS_DIR = LAKE_PORTFOLIO_REGIME_DIR / "stress_tests"
LAKE_PORTFOLIO_REGIME_DRAWDOWNS_DIR = LAKE_PORTFOLIO_REGIME_DIR / "drawdowns"
LAKE_PORTFOLIO_REGIME_RECOVERY_DIR = LAKE_PORTFOLIO_REGIME_DIR / "recovery"
LAKE_PORTFOLIO_REGIME_TAIL_RISK_DIR = LAKE_PORTFOLIO_REGIME_DIR / "tail_risk"
LAKE_PORTFOLIO_REGIME_EXPOSURE_DIR = LAKE_PORTFOLIO_REGIME_DIR / "exposure"
LAKE_PORTFOLIO_REGIME_QUALITY_DIR = LAKE_PORTFOLIO_REGIME_DIR / "quality"

REPORTS_PORTFOLIO_REGIME_DIR = REPORTS_DIR / "portfolio_regime"
REPORTS_PORTFOLIO_REGIME_CSV_DIR = REPORTS_PORTFOLIO_REGIME_DIR / "csv"
REPORTS_PORTFOLIO_REGIME_MARKDOWN_DIR = REPORTS_PORTFOLIO_REGIME_DIR / "markdown"
REPORTS_PORTFOLIO_REGIME_TXT_DIR = REPORTS_PORTFOLIO_REGIME_DIR / "txt"


# Governance Paths
DATA_LAKE_GOVERNANCE_DIR = LAKE_DIR / "governance"
DATA_LAKE_GOVERNANCE_INVENTORY_DIR = DATA_LAKE_GOVERNANCE_DIR / "inventory"
DATA_LAKE_GOVERNANCE_FINGERPRINTS_DIR = DATA_LAKE_GOVERNANCE_DIR / "fingerprints"
DATA_LAKE_GOVERNANCE_PROVENANCE_DIR = DATA_LAKE_GOVERNANCE_DIR / "provenance"
DATA_LAKE_GOVERNANCE_LINEAGE_DIR = DATA_LAKE_GOVERNANCE_DIR / "lineage"
DATA_LAKE_GOVERNANCE_DEPENDENCIES_DIR = DATA_LAKE_GOVERNANCE_DIR / "dependencies"
DATA_LAKE_GOVERNANCE_AUDIT_DIR = DATA_LAKE_GOVERNANCE_DIR / "audit"
DATA_LAKE_GOVERNANCE_SOURCE_ATTRIBUTION_DIR = DATA_LAKE_GOVERNANCE_DIR / "source_attribution"
DATA_LAKE_GOVERNANCE_CHECKLISTS_DIR = DATA_LAKE_GOVERNANCE_DIR / "checklists"
DATA_LAKE_GOVERNANCE_QUALITY_DIR = DATA_LAKE_GOVERNANCE_DIR / "quality"

REPORTS_GOVERNANCE_DIR = REPORTS_DIR / "governance"
REPORTS_GOVERNANCE_CSV_DIR = REPORTS_GOVERNANCE_DIR / "csv"
REPORTS_GOVERNANCE_MARKDOWN_DIR = REPORTS_GOVERNANCE_DIR / "markdown"
REPORTS_GOVERNANCE_TXT_DIR = REPORTS_GOVERNANCE_DIR / "txt"
REPORTS_GOVERNANCE_JSON_DIR = REPORTS_GOVERNANCE_DIR / "json"


# Phase 48: Research Planning
LAKE_RESEARCH_PLANNING_DIR = LAKE_DIR / "research_planning"
LAKE_RESEARCH_PLANNING_SIGNALS_DIR = LAKE_RESEARCH_PLANNING_DIR / "signals"
LAKE_RESEARCH_PLANNING_TASKS_DIR = LAKE_RESEARCH_PLANNING_DIR / "tasks"
LAKE_RESEARCH_PLANNING_BACKLOG_DIR = LAKE_RESEARCH_PLANNING_DIR / "backlog"
LAKE_RESEARCH_PLANNING_PRIORITIES_DIR = LAKE_RESEARCH_PLANNING_DIR / "priorities"
LAKE_RESEARCH_PLANNING_NEXT_BEST_DIR = LAKE_RESEARCH_PLANNING_DIR / "next_best"
LAKE_RESEARCH_PLANNING_DEBT_DIR = LAKE_RESEARCH_PLANNING_DIR / "debt"
LAKE_RESEARCH_PLANNING_OPPORTUNITIES_DIR = LAKE_RESEARCH_PLANNING_DIR / "opportunities"
LAKE_RESEARCH_PLANNING_ROADMAP_DIR = LAKE_RESEARCH_PLANNING_DIR / "roadmap"
LAKE_RESEARCH_PLANNING_DEPENDENCIES_DIR = LAKE_RESEARCH_PLANNING_DIR / "dependencies"
LAKE_RESEARCH_PLANNING_MILESTONES_DIR = LAKE_RESEARCH_PLANNING_DIR / "milestones"
LAKE_RESEARCH_PLANNING_ORCHESTRATION_DIR = LAKE_RESEARCH_PLANNING_DIR / "orchestration"
LAKE_RESEARCH_PLANNING_QUALITY_DIR = LAKE_RESEARCH_PLANNING_DIR / "quality"

REPORTS_RESEARCH_PLANNING_DIR = REPORTS_DIR / "research_planning"
REPORTS_RESEARCH_PLANNING_CSV_DIR = REPORTS_RESEARCH_PLANNING_DIR / "csv"
REPORTS_RESEARCH_PLANNING_MARKDOWN_DIR = REPORTS_RESEARCH_PLANNING_DIR / "markdown"
REPORTS_RESEARCH_PLANNING_TXT_DIR = REPORTS_RESEARCH_PLANNING_DIR / "txt"
REPORTS_RESEARCH_PLANNING_JSON_DIR = REPORTS_RESEARCH_PLANNING_DIR / "json"


# Phase 49: Knowledge Base
LAKE_KNOWLEDGE_BASE_DIR = LAKE_DIR / "knowledge_base"
LAKE_KNOWLEDGE_BASE_DOCUMENTS_DIR = LAKE_KNOWLEDGE_BASE_DIR / "documents"
LAKE_KNOWLEDGE_BASE_CHUNKS_DIR = LAKE_KNOWLEDGE_BASE_DIR / "chunks"
LAKE_KNOWLEDGE_BASE_INDEXES_DIR = LAKE_KNOWLEDGE_BASE_DIR / "indexes"
LAKE_KNOWLEDGE_BASE_RETRIEVAL_DIR = LAKE_KNOWLEDGE_BASE_DIR / "retrieval"
LAKE_KNOWLEDGE_BASE_MEMORY_CARDS_DIR = LAKE_KNOWLEDGE_BASE_DIR / "memory_cards"
LAKE_KNOWLEDGE_BASE_DECISION_JOURNAL_DIR = LAKE_KNOWLEDGE_BASE_DIR / "decision_journal"
LAKE_KNOWLEDGE_BASE_ANALYST_NOTES_DIR = LAKE_KNOWLEDGE_BASE_DIR / "analyst_notes"
LAKE_KNOWLEDGE_BASE_FINDINGS_DIR = LAKE_KNOWLEDGE_BASE_DIR / "findings"
LAKE_KNOWLEDGE_BASE_WORKSPACE_DIR = LAKE_KNOWLEDGE_BASE_DIR / "workspace"
LAKE_KNOWLEDGE_BASE_QUALITY_DIR = LAKE_KNOWLEDGE_BASE_DIR / "quality"

REPORTS_KNOWLEDGE_BASE_DIR = REPORTS_OUTPUT_DIR / "knowledge_base"
REPORTS_KNOWLEDGE_BASE_CSV_DIR = REPORTS_KNOWLEDGE_BASE_DIR / "csv"
REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR = REPORTS_KNOWLEDGE_BASE_DIR / "markdown"
REPORTS_KNOWLEDGE_BASE_TXT_DIR = REPORTS_KNOWLEDGE_BASE_DIR / "txt"
REPORTS_KNOWLEDGE_BASE_JSON_DIR = REPORTS_KNOWLEDGE_BASE_DIR / "json"

FINAL_REVIEW_DATA = LAKE_DIR / "final_review"
FINAL_REVIEW_SYSTEM_INVENTORY = FINAL_REVIEW_DATA / "system_inventory"
FINAL_REVIEW_ARCHITECTURE = FINAL_REVIEW_DATA / "architecture"
FINAL_REVIEW_SAFETY = FINAL_REVIEW_DATA / "safety"
FINAL_REVIEW_INTEGRATION = FINAL_REVIEW_DATA / "integration"
FINAL_REVIEW_COMMANDS = FINAL_REVIEW_DATA / "commands"
FINAL_REVIEW_DATALAKE = FINAL_REVIEW_DATA / "datalake"
FINAL_REVIEW_REPORT_OUTPUTS = FINAL_REVIEW_DATA / "report_outputs"
FINAL_REVIEW_DOCUMENTATION = FINAL_REVIEW_DATA / "documentation"
FINAL_REVIEW_QUALITY_GATES = FINAL_REVIEW_DATA / "quality_gates"
FINAL_REVIEW_READINESS = FINAL_REVIEW_DATA / "readiness"
FINAL_REVIEW_RISKS = FINAL_REVIEW_DATA / "risks"
FINAL_REVIEW_GAPS = FINAL_REVIEW_DATA / "gaps"
FINAL_REVIEW_ACCEPTANCE = FINAL_REVIEW_DATA / "acceptance"
FINAL_REVIEW_CONSOLIDATION = FINAL_REVIEW_DATA / "consolidation"
FINAL_REVIEW_QUALITY = FINAL_REVIEW_DATA / "quality"

FINAL_REVIEW_REPORTS_DIR = REPORTS_DIR / "output" / "final_review"
FINAL_REVIEW_REPORTS_CSV = FINAL_REVIEW_REPORTS_DIR / "csv"
FINAL_REVIEW_REPORTS_MARKDOWN = FINAL_REVIEW_REPORTS_DIR / "markdown"
FINAL_REVIEW_REPORTS_TXT = FINAL_REVIEW_REPORTS_DIR / "txt"
FINAL_REVIEW_REPORTS_JSON = FINAL_REVIEW_REPORTS_DIR / "json"


# Scenario paths
DATA_SCENARIOS_DIR = LAKE_DIR / "scenarios"
DATA_SCENARIOS_REGISTRY_DIR = DATA_SCENARIOS_DIR / "registry"
DATA_SCENARIOS_SAMPLE_DATA_DIR = DATA_SCENARIOS_DIR / "sample_data"
DATA_SCENARIOS_FIXTURES_DIR = DATA_SCENARIOS_DIR / "fixtures"
DATA_SCENARIOS_EXPECTED_OUTPUTS_DIR = DATA_SCENARIOS_DIR / "expected_outputs"
DATA_SCENARIOS_WORKFLOWS_DIR = DATA_SCENARIOS_DIR / "workflows"
DATA_SCENARIOS_DEMO_COMMANDS_DIR = DATA_SCENARIOS_DIR / "demo_commands"
DATA_SCENARIOS_DRY_RUNS_DIR = DATA_SCENARIOS_DIR / "dry_runs"
DATA_SCENARIOS_VALIDATION_DIR = DATA_SCENARIOS_DIR / "validation"
DATA_SCENARIOS_CASE_STUDIES_DIR = DATA_SCENARIOS_DIR / "case_studies"
DATA_SCENARIOS_MODULE_FLOWS_DIR = DATA_SCENARIOS_DIR / "module_flows"
DATA_SCENARIOS_END_TO_END_DIR = DATA_SCENARIOS_DIR / "end_to_end"
DATA_SCENARIOS_QUALITY_DIR = DATA_SCENARIOS_DIR / "quality"

REPORTS_SCENARIOS_DIR = REPORTS_OUTPUT_DIR / "scenarios"
REPORTS_SCENARIOS_CSV_DIR = REPORTS_SCENARIOS_DIR / "csv"
REPORTS_SCENARIOS_MARKDOWN_DIR = REPORTS_SCENARIOS_DIR / "markdown"
REPORTS_SCENARIOS_TXT_DIR = REPORTS_SCENARIOS_DIR / "txt"
REPORTS_SCENARIOS_JSON_DIR = REPORTS_SCENARIOS_DIR / "json"

DOCS_GENERATED_SCENARIOS_DIR = DOCS_DIR / "generated" / "scenarios"



# Report Summarization Paths
LAKE_REPORT_SUMMARIZATION_DIR = LAKE_DIR / "report_summarization"
LAKE_REPORT_SUMMARIZATION_INVENTORY_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "inventory"
LAKE_REPORT_SUMMARIZATION_SUMMARIES_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "summaries"
LAKE_REPORT_SUMMARIZATION_FINDINGS_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "findings"
LAKE_REPORT_SUMMARIZATION_WARNINGS_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "warnings"
LAKE_REPORT_SUMMARIZATION_RISKS_GAPS_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "risks_gaps"
LAKE_REPORT_SUMMARIZATION_MODULE_SUMMARIES_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "module_summaries"
LAKE_REPORT_SUMMARIZATION_EXECUTIVE_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "executive"
LAKE_REPORT_SUMMARIZATION_ANALYST_BRIEFS_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "analyst_briefs"
LAKE_REPORT_SUMMARIZATION_WEEKLY_REVIEW_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "weekly_review"
LAKE_REPORT_SUMMARIZATION_DIGEST_CARDS_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "digest_cards"
LAKE_REPORT_SUMMARIZATION_SYMBOL_BRIEFS_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "symbol_briefs"
LAKE_REPORT_SUMMARIZATION_SAFETY_QUALITY_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "safety_quality"
LAKE_REPORT_SUMMARIZATION_FOLLOW_UPS_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "follow_ups"
LAKE_REPORT_SUMMARIZATION_VALIDATION_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "validation"
LAKE_REPORT_SUMMARIZATION_QUALITY_DIR = LAKE_REPORT_SUMMARIZATION_DIR / "quality"

REPORTS_REPORT_SUMMARIZATION_DIR = REPORTS_DIR / "report_summarization"
REPORTS_REPORT_SUMMARIZATION_CSV_DIR = REPORTS_REPORT_SUMMARIZATION_DIR / "csv"
REPORTS_REPORT_SUMMARIZATION_MARKDOWN_DIR = REPORTS_REPORT_SUMMARIZATION_DIR / "markdown"
REPORTS_REPORT_SUMMARIZATION_TXT_DIR = REPORTS_REPORT_SUMMARIZATION_DIR / "txt"
REPORTS_REPORT_SUMMARIZATION_JSON_DIR = REPORTS_REPORT_SUMMARIZATION_DIR / "json"

DOCS_GENERATED_REPORT_SUMMARIES_DIR = PROJECT_ROOT / "docs" / "generated" / "report_summaries"


LAKE_MASTER_ORCHESTRATION = LAKE_DIR / "master_orchestration"
LAKE_MASTER_ORCHESTRATION_LAYER_MAPS = LAKE_MASTER_ORCHESTRATION / "layer_maps"
LAKE_MASTER_ORCHESTRATION_DEPENDENCIES = LAKE_MASTER_ORCHESTRATION / "dependencies"
LAKE_MASTER_ORCHESTRATION_COMMAND_GRAPHS = LAKE_MASTER_ORCHESTRATION / "command_graphs"
LAKE_MASTER_ORCHESTRATION_MASTER_PLANS = LAKE_MASTER_ORCHESTRATION / "master_plans"
LAKE_MASTER_ORCHESTRATION_META_RUNNER = LAKE_MASTER_ORCHESTRATION / "meta_runner"
LAKE_MASTER_ORCHESTRATION_OPERATING_MODES = LAKE_MASTER_ORCHESTRATION / "operating_modes"
LAKE_MASTER_ORCHESTRATION_PLAYBOOKS = LAKE_MASTER_ORCHESTRATION / "playbooks"
LAKE_MASTER_ORCHESTRATION_RUN_ORDERS = LAKE_MASTER_ORCHESTRATION / "run_orders"
LAKE_MASTER_ORCHESTRATION_HANDOFFS = LAKE_MASTER_ORCHESTRATION / "handoffs"
LAKE_MASTER_ORCHESTRATION_CONSOLIDATION = LAKE_MASTER_ORCHESTRATION / "consolidation"
LAKE_MASTER_ORCHESTRATION_SAFETY = LAKE_MASTER_ORCHESTRATION / "safety"
LAKE_MASTER_ORCHESTRATION_STATUS = LAKE_MASTER_ORCHESTRATION / "status"
LAKE_MASTER_ORCHESTRATION_QUALITY = LAKE_MASTER_ORCHESTRATION / "quality"
REPORTS_MASTER_ORCHESTRATION = REPORTS_OUTPUT_DIR / "master_orchestration"
REPORTS_MASTER_ORCHESTRATION_CSV = REPORTS_MASTER_ORCHESTRATION / "csv"
REPORTS_MASTER_ORCHESTRATION_MARKDOWN = REPORTS_MASTER_ORCHESTRATION / "markdown"
REPORTS_MASTER_ORCHESTRATION_TXT = REPORTS_MASTER_ORCHESTRATION / "txt"
REPORTS_MASTER_ORCHESTRATION_JSON = REPORTS_MASTER_ORCHESTRATION / "json"
DOCS_MASTER_ORCHESTRATION = PROJECT_ROOT / "docs" / "generated" / "master_orchestration"


# Backup Recovery
BACKUP_RECOVERY_DIR = DATA_DIR / "lake" / "backup_recovery"
BACKUP_RECOVERY_STATE_INVENTORY_DIR = BACKUP_RECOVERY_DIR / "state_inventory"
BACKUP_RECOVERY_POLICIES_DIR = BACKUP_RECOVERY_DIR / "policies"
BACKUP_RECOVERY_SCOPES_DIR = BACKUP_RECOVERY_DIR / "scopes"
BACKUP_RECOVERY_CRITICAL_ARTIFACTS_DIR = BACKUP_RECOVERY_DIR / "critical_artifacts"
BACKUP_RECOVERY_MANIFESTS_DIR = BACKUP_RECOVERY_DIR / "manifests"
BACKUP_RECOVERY_BACKUP_DRY_RUN_DIR = BACKUP_RECOVERY_DIR / "backup_dry_run"
BACKUP_RECOVERY_RESTORE_DRY_RUN_DIR = BACKUP_RECOVERY_DIR / "restore_dry_run"
BACKUP_RECOVERY_RESTORE_VERIFICATION_DIR = BACKUP_RECOVERY_DIR / "restore_verification"
BACKUP_RECOVERY_DISASTER_RECOVERY_DIR = BACKUP_RECOVERY_DIR / "disaster_recovery"
BACKUP_RECOVERY_RUNBOOKS_DIR = BACKUP_RECOVERY_DIR / "runbooks"
BACKUP_RECOVERY_INTEGRITY_DIR = BACKUP_RECOVERY_DIR / "integrity"
BACKUP_RECOVERY_GAPS_DIR = BACKUP_RECOVERY_DIR / "gaps"
BACKUP_RECOVERY_SAFETY_DIR = BACKUP_RECOVERY_DIR / "safety"
BACKUP_RECOVERY_QUALITY_DIR = BACKUP_RECOVERY_DIR / "quality"

REPORTS_BACKUP_RECOVERY_OUTPUT_DIR = REPORTS_OUTPUT_DIR / "backup_recovery"
REPORTS_BACKUP_RECOVERY_CSV_DIR = REPORTS_BACKUP_RECOVERY_OUTPUT_DIR / "csv"
REPORTS_BACKUP_RECOVERY_MARKDOWN_DIR = REPORTS_BACKUP_RECOVERY_OUTPUT_DIR / "markdown"
REPORTS_BACKUP_RECOVERY_TXT_DIR = REPORTS_BACKUP_RECOVERY_OUTPUT_DIR / "txt"
REPORTS_BACKUP_RECOVERY_JSON_DIR = REPORTS_BACKUP_RECOVERY_OUTPUT_DIR / "json"

BACKUP_RECOVERY_BUNDLE_DIR = PROJECT_ROOT / "backup_recovery_bundle"
BACKUP_RECOVERY_BUNDLE_MANIFESTS_DIR = BACKUP_RECOVERY_BUNDLE_DIR / "manifests"
BACKUP_RECOVERY_BUNDLE_DRY_RUN_PLANS_DIR = BACKUP_RECOVERY_BUNDLE_DIR / "dry_run_plans"
BACKUP_RECOVERY_BUNDLE_RUNBOOKS_DIR = BACKUP_RECOVERY_BUNDLE_DIR / "runbooks"

DOCS_GENERATED_BACKUP_RECOVERY_DIR = DOCS_DIR / "generated" / "backup_recovery"


def ensure_project_directories() -> None:


    """
    Ensure that all required project directories exist.
    Creates them if they do not exist.
    """
    directories = [
        LAKE_RESEARCH_PLANNING_DIR,
        LAKE_RESEARCH_PLANNING_SIGNALS_DIR,
        LAKE_RESEARCH_PLANNING_TASKS_DIR,
        LAKE_RESEARCH_PLANNING_BACKLOG_DIR,
        LAKE_RESEARCH_PLANNING_PRIORITIES_DIR,
        LAKE_RESEARCH_PLANNING_NEXT_BEST_DIR,
        LAKE_RESEARCH_PLANNING_DEBT_DIR,
        LAKE_RESEARCH_PLANNING_OPPORTUNITIES_DIR,
        LAKE_RESEARCH_PLANNING_ROADMAP_DIR,
        LAKE_RESEARCH_PLANNING_DEPENDENCIES_DIR,
        LAKE_RESEARCH_PLANNING_MILESTONES_DIR,
        LAKE_RESEARCH_PLANNING_ORCHESTRATION_DIR,
        LAKE_RESEARCH_PLANNING_QUALITY_DIR,
        REPORTS_RESEARCH_PLANNING_DIR,
        REPORTS_RESEARCH_PLANNING_CSV_DIR,
        REPORTS_RESEARCH_PLANNING_MARKDOWN_DIR,
        REPORTS_RESEARCH_PLANNING_TXT_DIR,
        REPORTS_RESEARCH_PLANNING_JSON_DIR,


        LAKE_KNOWLEDGE_BASE_DIR,
        LAKE_KNOWLEDGE_BASE_DOCUMENTS_DIR,
        LAKE_KNOWLEDGE_BASE_CHUNKS_DIR,
        LAKE_KNOWLEDGE_BASE_INDEXES_DIR,
        LAKE_KNOWLEDGE_BASE_RETRIEVAL_DIR,
        LAKE_KNOWLEDGE_BASE_MEMORY_CARDS_DIR,
        LAKE_KNOWLEDGE_BASE_DECISION_JOURNAL_DIR,
        LAKE_KNOWLEDGE_BASE_ANALYST_NOTES_DIR,
        LAKE_KNOWLEDGE_BASE_FINDINGS_DIR,
        LAKE_KNOWLEDGE_BASE_WORKSPACE_DIR,
        LAKE_KNOWLEDGE_BASE_QUALITY_DIR,
        REPORTS_KNOWLEDGE_BASE_DIR,
        REPORTS_KNOWLEDGE_BASE_CSV_DIR,
        REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR,
        REPORTS_KNOWLEDGE_BASE_TXT_DIR,
        REPORTS_KNOWLEDGE_BASE_JSON_DIR,
        LOGS_DIR,
        REPORTS_DIR,
        RAW_DATA_DIR,
        PROCESSED_DATA_DIR,
        CACHE_DIR,
        LAKE_DIR,
        LAKE_OHLCV_DIR,
        LAKE_MACRO_DIR,
        LAKE_SYNTHETIC_DIR,
        LAKE_MANIFESTS_DIR,
        LAKE_JOURNALS_DIR,

        LAKE_OBSERVABILITY_DIR,
        LAKE_OBSERVABILITY_LOGS_DIR,
        LAKE_OBSERVABILITY_JSON_LOGS_DIR,
        LAKE_OBSERVABILITY_HEALTH_DIR,
        LAKE_OBSERVABILITY_RUNTIME_METRICS_DIR,
        LAKE_OBSERVABILITY_DIAGNOSTICS_DIR,
        LAKE_OBSERVABILITY_ERROR_TAXONOMY_DIR,
        LAKE_OBSERVABILITY_DATA_FRESHNESS_DIR,
        LAKE_OBSERVABILITY_ARTIFACT_INTEGRITY_DIR,
        LAKE_OBSERVABILITY_QUALITY_DIR,
        REPORTS_OBSERVABILITY_DIR,
        LAKE_PROCESSED_DIR,
        LAKE_PROCESSED_OHLCV_DIR,
        LAKE_QUALITY_REPORTS_DIR,
        LAKE_CLEANING_REPORTS_DIR,
        LAKE_FEATURES_DIR,
        LAKE_FEATURES_TECHNICAL_DIR,
        LAKE_FEATURES_MOMENTUM_DIR,
        LAKE_FEATURES_MOMENTUM_EVENTS_DIR,
        LAKE_FEATURES_MANIFESTS_DIR,
        LAKE_FEATURES_REPORTS_DIR,
        INDICATOR_REPORTS_DIR,
        MOMENTUM_REPORTS_DIR,
        LAKE_FEATURES_TREND_DIR,
        LAKE_FEATURES_TREND_EVENTS_DIR,
        LAKE_FEATURES_TREND_EVENTS_DIR,
        TREND_REPORTS_DIR,
        LAKE_FEATURES_VOLATILITY_DIR,
        LAKE_FEATURES_VOLATILITY_EVENTS_DIR,
        VOLATILITY_REPORTS_DIR,
        LAKE_FEATURES_PRICE_ACTION_DIR,
        LAKE_FEATURES_PRICE_ACTION_EVENTS_DIR,
        PRICE_ACTION_REPORTS_DIR,
        LAKE_FEATURES_DIVERGENCE_DIR,
        LAKE_FEATURES_DIVERGENCE_EVENTS_DIR,
        DIVERGENCE_REPORTS_DIR,
        LAKE_FEATURES_MTF_DIR,
        LAKE_FEATURES_MTF_EVENTS_DIR,
        MTF_REPORTS_DIR,
        LAKE_FEATURES_REGIME_DIR,
        LAKE_FEATURES_REGIME_EVENTS_DIR,
        REGIME_REPORTS_DIR,
        LAKE_MACRO_RAW_DIR,
        LAKE_MACRO_PROCESSED_DIR,
        LAKE_BENCHMARKS_DIR,
        LAKE_FEATURES_MACRO_DIR,
        LAKE_FEATURES_MACRO_EVENTS_DIR,
        LAKE_FEATURES_BENCHMARKS_DIR,
        MACRO_REPORTS_DIR,
        LAKE_TMP_DIR,
        LAKE_FEATURES_ASSET_PROFILES_DIR,
        LAKE_FEATURES_ASSET_PROFILE_EVENTS_DIR,
        LAKE_FEATURES_GROUP_FEATURES_DIR,
        ASSET_PROFILE_REPORTS_DIR,
        LAKE_FEATURES_SIGNAL_CANDIDATES_DIR,
        LAKE_FEATURES_SIGNAL_POOL_DIR,
        SIGNAL_REPORTS_DIR,
        LAKE_FEATURES_DECISION_CANDIDATES_DIR,
        LAKE_FEATURES_DECISION_POOL_DIR,
        DECISION_REPORTS_DIR,
        LAKE_FEATURES_STRATEGY_CANDIDATES_DIR,
        LAKE_FEATURES_STRATEGY_POOL_DIR,
        STRATEGY_REPORTS_DIR,
        LAKE_FEATURES_STRATEGY_RULE_CANDIDATES_DIR,
        LAKE_FEATURES_ENTRY_EXIT_CANDIDATES_DIR,
        LAKE_FEATURES_STRATEGY_RULE_POOL_DIR,
        REPORTS_RISK_REPORTS_DIR,
        LAKE_FEATURES_RISK_CANDIDATES_DIR,
        LAKE_FEATURES_RISK_POOL_DIR,
        STRATEGY_RULE_REPORTS_DIR,
        REPORTS_SIZING_REPORTS_DIR,
        LAKE_FEATURES_SIZING_CANDIDATES_DIR,
        LAKE_FEATURES_SIZING_POOL_DIR,
        LAKE_FEATURES_LEVEL_CANDIDATES_DIR,
        LAKE_FEATURES_LEVEL_POOL_DIR,
        REPORTS_LEVEL_REPORTS_DIR,
        LAKE_DIR / "backtests",
        LAKE_DIR / "backtests" / "runs",
        LAKE_DIR / "backtests" / "trades",
        LAKE_DIR / "backtests" / "equity_curves",
        LAKE_DIR / "backtests" / "audits",
        REPORTS_DIR / "backtest_reports",
        LAKE_ML_DIR,
        LAKE_ML_FEATURES_DIR,
        LAKE_ML_TARGETS_DIR,
        LAKE_ML_DATASETS_DIR,
        LAKE_ML_SPLITS_DIR,
        LAKE_ML_METADATA_DIR,
        LAKE_ML_QUALITY_DIR,
        LAKE_ML_MODELS_DIR,
        LAKE_ML_MODEL_ARTIFACTS_DIR,
        LAKE_ML_MODEL_REGISTRY_DIR,
        LAKE_ML_MODEL_EVALUATIONS_DIR,
        LAKE_ML_MODEL_CV_DIR,
        LAKE_ML_MODEL_QUALITY_DIR,
        REPORTS_ML_TRAINING_REPORTS_DIR,
        REPORTS_ML_REPORTS_DIR,
        LAKE_ML_INTEGRATION_DIR,
        LAKE_ML_INTEGRATION_FEATURES_DIR,
        LAKE_ML_INTEGRATION_ALIGNMENT_DIR,
        LAKE_ML_INTEGRATION_CONFLICTS_DIR,
        LAKE_ML_INTEGRATION_QUALITY_DIR,
        REPORTS_ML_INTEGRATION_REPORTS_DIR,
        LAKE_PAPER_DIR,
        LAKE_PAPER_RUNS_DIR,
        LAKE_PAPER_ORDERS_DIR,
        LAKE_PAPER_ORDER_BOOKS_DIR,
        LAKE_PAPER_POSITIONS_DIR,
        LAKE_PAPER_PORTFOLIOS_DIR,
        LAKE_PAPER_LEDGERS_DIR,
        LAKE_PAPER_EQUITY_CURVES_DIR,
        LAKE_PAPER_AUDITS_DIR,
        LAKE_PAPER_QUALITY_DIR,
        PAPER_REPORTS_DIR,
        LAKE_NOTIFICATIONS_DIR,
        LAKE_NOTIFICATIONS_MESSAGES_DIR,
        LAKE_NOTIFICATIONS_DELIVERY_LOGS_DIR,
        LAKE_NOTIFICATIONS_AUDITS_DIR,
        LAKE_NOTIFICATIONS_QUALITY_DIR,
        NOTIFICATION_REPORT_OUTPUT_DIR,
        LAKE_ORCHESTRATION_DIR,
        LAKE_ORCHESTRATION_RUNS_DIR,
        LAKE_ORCHESTRATION_MANIFESTS_DIR,
        LAKE_ORCHESTRATION_DEPENDENCY_GRAPHS_DIR,

        LAKE_ORCHESTRATION_EXECUTION_PLANS_DIR,
        LAKE_ORCHESTRATION_JOB_LOGS_DIR,
        LAKE_ORCHESTRATION_QUALITY_DIR,
    ORCHESTRATION_REPORT_OUTPUT_DIR,
        LAKE_SECURITY_DIR,
        LAKE_SECURITY_AUDITS_DIR,
        LAKE_SECURITY_SECRET_HYGIENE_DIR,
        LAKE_SECURITY_CONFIG_HARDENING_DIR,
        LAKE_SECURITY_SAFE_DEFAULTS_DIR,
        LAKE_SECURITY_PERMISSIONS_DIR,
        LAKE_SECURITY_PATH_SAFETY_DIR,
        LAKE_SECURITY_TOKEN_SCANS_DIR,
        LAKE_SECURITY_READINESS_DIR,
        LAKE_SECURITY_QUALITY_DIR,
        REPORTS_SECURITY_REPORTS_DIR,
        DATA_LAKE_GOVERNANCE_DIR,
        DATA_LAKE_GOVERNANCE_INVENTORY_DIR,
        DATA_LAKE_GOVERNANCE_FINGERPRINTS_DIR,
        DATA_LAKE_GOVERNANCE_PROVENANCE_DIR,
        DATA_LAKE_GOVERNANCE_LINEAGE_DIR,
        DATA_LAKE_GOVERNANCE_DEPENDENCIES_DIR,
        DATA_LAKE_GOVERNANCE_AUDIT_DIR,
        DATA_LAKE_GOVERNANCE_SOURCE_ATTRIBUTION_DIR,
        DATA_LAKE_GOVERNANCE_CHECKLISTS_DIR,
        DATA_LAKE_GOVERNANCE_QUALITY_DIR,
        REPORTS_GOVERNANCE_DIR,
        REPORTS_GOVERNANCE_CSV_DIR,
        REPORTS_GOVERNANCE_MARKDOWN_DIR,
        REPORTS_GOVERNANCE_TXT_DIR,
        REPORTS_GOVERNANCE_JSON_DIR,
        DATA_SCENARIOS_DIR,
        DATA_SCENARIOS_REGISTRY_DIR,
        DATA_SCENARIOS_SAMPLE_DATA_DIR,
        DATA_SCENARIOS_FIXTURES_DIR,
        DATA_SCENARIOS_EXPECTED_OUTPUTS_DIR,
        DATA_SCENARIOS_WORKFLOWS_DIR,
        DATA_SCENARIOS_DEMO_COMMANDS_DIR,
        DATA_SCENARIOS_DRY_RUNS_DIR,
        DATA_SCENARIOS_VALIDATION_DIR,
        DATA_SCENARIOS_CASE_STUDIES_DIR,
        DATA_SCENARIOS_MODULE_FLOWS_DIR,
        DATA_SCENARIOS_END_TO_END_DIR,
        DATA_SCENARIOS_QUALITY_DIR,
        REPORTS_SCENARIOS_DIR,
        REPORTS_SCENARIOS_CSV_DIR,
        REPORTS_SCENARIOS_MARKDOWN_DIR,
        REPORTS_SCENARIOS_TXT_DIR,
        REPORTS_SCENARIOS_JSON_DIR,
        DOCS_GENERATED_SCENARIOS_DIR,
    ]
    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)


# Risk Reports directories
REPORTS_RISK_REPORTS_DIR = REPORTS_DIR / "risk_reports"


# Risk Data Lake directories
LAKE_FEATURES_RISK_CANDIDATES_DIR = LAKE_FEATURES_DIR / "risk_candidates"
LAKE_FEATURES_RISK_POOL_DIR = LAKE_FEATURES_DIR / "risk_pool"

# Sizing Reports
REPORTS_SIZING_REPORTS_DIR = REPORTS_DIR / "sizing_reports"

# Sizing Data Lake directories
LAKE_FEATURES_SIZING_CANDIDATES_DIR = LAKE_FEATURES_DIR / "sizing_candidates"
LAKE_FEATURES_SIZING_POOL_DIR = LAKE_FEATURES_DIR / "sizing_pool"
LAKE_FEATURES_LEVEL_CANDIDATES_DIR = LAKE_FEATURES_DIR / "level_candidates"
LAKE_FEATURES_LEVEL_POOL_DIR = LAKE_FEATURES_DIR / "level_pool"

REPORTS_LEVEL_REPORTS_DIR = REPORTS_DIR / "level_reports"



# Phase 43: Synthetic Indices
LAKE_SYNTHETIC_INDICES_DIR = LAKE_DIR / "synthetic_indices"
LAKE_SYNTHETIC_INDICES_DEFINITIONS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "definitions"
LAKE_SYNTHETIC_INDICES_LEVELS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "levels"
LAKE_SYNTHETIC_INDICES_RETURNS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "returns"
LAKE_SYNTHETIC_INDICES_RELATIVE_STRENGTH_DIR = LAKE_SYNTHETIC_INDICES_DIR / "relative_strength"
LAKE_SYNTHETIC_INDICES_RELATIVE_MOMENTUM_DIR = LAKE_SYNTHETIC_INDICES_DIR / "relative_momentum"
LAKE_SYNTHETIC_INDICES_ROTATION_DIR = LAKE_SYNTHETIC_INDICES_DIR / "rotation"
LAKE_SYNTHETIC_INDICES_LEADERSHIP_DIR = LAKE_SYNTHETIC_INDICES_DIR / "leadership"
LAKE_SYNTHETIC_INDICES_COMPARISONS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "comparisons"
LAKE_SYNTHETIC_INDICES_PERFORMANCE_DIR = LAKE_SYNTHETIC_INDICES_DIR / "performance"
LAKE_SYNTHETIC_INDICES_QUALITY_DIR = LAKE_SYNTHETIC_INDICES_DIR / "quality"

REPORTS_SYNTHETIC_INDICES_DIR = REPORTS_DIR / "synthetic_indices"
REPORTS_SYNTHETIC_INDICES_CSV_DIR = REPORTS_SYNTHETIC_INDICES_DIR / "csv"
REPORTS_SYNTHETIC_INDICES_MARKDOWN_DIR = REPORTS_SYNTHETIC_INDICES_DIR / "markdown"
REPORTS_SYNTHETIC_INDICES_TXT_DIR = REPORTS_SYNTHETIC_INDICES_DIR / "txt"


# Phase 44: Factor Research
LAKE_FACTOR_RESEARCH_DIR = LAKE_DIR / "factor_research"
LAKE_FACTOR_RESEARCH_DEFINITIONS_DIR = LAKE_FACTOR_RESEARCH_DIR / "definitions"
LAKE_FACTOR_RESEARCH_SCORES_DIR = LAKE_FACTOR_RESEARCH_DIR / "scores"
LAKE_FACTOR_RESEARCH_RANKS_DIR = LAKE_FACTOR_RESEARCH_DIR / "ranks"
LAKE_FACTOR_RESEARCH_BACKTESTS_DIR = LAKE_FACTOR_RESEARCH_DIR / "backtests"
LAKE_FACTOR_RESEARCH_IC_DIR = LAKE_FACTOR_RESEARCH_DIR / "ic"
LAKE_FACTOR_RESEARCH_STABILITY_DIR = LAKE_FACTOR_RESEARCH_DIR / "stability"
LAKE_FACTOR_RESEARCH_EXPOSURE_DIR = LAKE_FACTOR_RESEARCH_DIR / "exposure"
LAKE_FACTOR_RESEARCH_NEUTRALIZATION_DIR = LAKE_FACTOR_RESEARCH_DIR / "neutralization"
LAKE_FACTOR_RESEARCH_REPORTS_DIR = LAKE_FACTOR_RESEARCH_DIR / "reports"

# Phase 45: Meta Research
LAKE_META_RESEARCH_DIR = LAKE_DIR / "meta_research"
LAKE_META_RESEARCH_EVIDENCE_DIR = LAKE_META_RESEARCH_DIR / "evidence"
LAKE_META_RESEARCH_RELIABILITY_DIR = LAKE_META_RESEARCH_DIR / "reliability"
LAKE_META_RESEARCH_CONSENSUS_DIR = LAKE_META_RESEARCH_DIR / "consensus"
LAKE_META_RESEARCH_CONFLICTS_DIR = LAKE_META_RESEARCH_DIR / "conflicts"
LAKE_META_RESEARCH_UNCERTAINTY_DIR = LAKE_META_RESEARCH_DIR / "uncertainty"
LAKE_META_RESEARCH_ENSEMBLE_DIR = LAKE_META_RESEARCH_DIR / "ensemble"
LAKE_META_RESEARCH_RANKINGS_DIR = LAKE_META_RESEARCH_DIR / "rankings"
LAKE_META_RESEARCH_SNAPSHOTS_DIR = LAKE_META_RESEARCH_DIR / "snapshots"
LAKE_META_RESEARCH_REPORTS_DIR = LAKE_META_RESEARCH_DIR / "reports"
LAKE_META_RESEARCH_QUALITY_DIR = LAKE_META_RESEARCH_DIR / "quality"
LAKE_FACTOR_RESEARCH_QUALITY_DIR = LAKE_FACTOR_RESEARCH_DIR / "quality"

REPORTS_FACTOR_RESEARCH_DIR = REPORTS_DIR / "factor_research"
REPORTS_FACTOR_RESEARCH_CSV_DIR = REPORTS_FACTOR_RESEARCH_DIR / "csv"
REPORTS_FACTOR_RESEARCH_MARKDOWN_DIR = REPORTS_FACTOR_RESEARCH_DIR / "markdown"
REPORTS_FACTOR_RESEARCH_TXT_DIR = REPORTS_FACTOR_RESEARCH_DIR / "txt"


# Phase 46: Experiment Tracking
LAKE_EXPERIMENTS_DIR = LAKE_DIR / "experiments"
LAKE_EXPERIMENTS_HYPOTHESES_DIR = LAKE_EXPERIMENTS_DIR / "hypotheses"
LAKE_EXPERIMENTS_DEFINITIONS_DIR = LAKE_EXPERIMENTS_DIR / "definitions"
LAKE_EXPERIMENTS_RUNS_DIR = LAKE_EXPERIMENTS_DIR / "runs"
LAKE_EXPERIMENTS_ARTIFACTS_DIR = LAKE_EXPERIMENTS_DIR / "artifacts"
LAKE_EXPERIMENTS_REPRODUCIBILITY_DIR = LAKE_EXPERIMENTS_DIR / "reproducibility"
LAKE_EXPERIMENTS_VERSIONS_DIR = LAKE_EXPERIMENTS_DIR / "versions"
LAKE_EXPERIMENTS_ABLATION_DIR = LAKE_EXPERIMENTS_DIR / "ablation"
LAKE_EXPERIMENTS_COMPARISONS_DIR = LAKE_EXPERIMENTS_DIR / "comparisons"
LAKE_EXPERIMENTS_LEADERBOARDS_DIR = LAKE_EXPERIMENTS_DIR / "leaderboards"
LAKE_EXPERIMENTS_QUALITY_DIR = LAKE_EXPERIMENTS_DIR / "quality"

REPORTS_EXPERIMENTS_DIR = REPORTS_DIR / "experiments"
REPORTS_EXPERIMENTS_CSV_DIR = REPORTS_EXPERIMENTS_DIR / "csv"
REPORTS_EXPERIMENTS_MARKDOWN_DIR = REPORTS_EXPERIMENTS_DIR / "markdown"
REPORTS_EXPERIMENTS_TXT_DIR = REPORTS_EXPERIMENTS_DIR / "txt"
REPORTS_EXPERIMENTS_JSON_DIR = REPORTS_EXPERIMENTS_DIR / "json"


# Phase 50: Command Center
LAKE_COMMAND_CENTER_DIR = LAKE_DIR / "command_center"
LAKE_COMMAND_CENTER_REGISTRY_DIR = LAKE_COMMAND_CENTER_DIR / "registry"
LAKE_COMMAND_CENTER_WORKFLOWS_DIR = LAKE_COMMAND_CENTER_DIR / "workflows"
LAKE_COMMAND_CENTER_RUNBOOKS_DIR = LAKE_COMMAND_CENTER_DIR / "runbooks"
LAKE_COMMAND_CENTER_DRY_RUN_PLANS_DIR = LAKE_COMMAND_CENTER_DIR / "dry_run_plans"
LAKE_COMMAND_CENTER_QUERY_FLOWS_DIR = LAKE_COMMAND_CENTER_DIR / "query_flows"
LAKE_COMMAND_CENTER_PROJECT_STATUS_DIR = LAKE_COMMAND_CENTER_DIR / "project_status"
LAKE_COMMAND_CENTER_MODULE_HEALTH_DIR = LAKE_COMMAND_CENTER_DIR / "module_health"
LAKE_COMMAND_CENTER_SCRIPT_DISCOVERY_DIR = LAKE_COMMAND_CENTER_DIR / "script_discovery"
LAKE_COMMAND_CENTER_PHASE_COVERAGE_DIR = LAKE_COMMAND_CENTER_DIR / "phase_coverage"
LAKE_COMMAND_CENTER_CONSOLIDATION_DIR = LAKE_COMMAND_CENTER_DIR / "consolidation"
LAKE_COMMAND_CENTER_ONBOARDING_DIR = LAKE_COMMAND_CENTER_DIR / "onboarding"
LAKE_COMMAND_CENTER_TROUBLESHOOTING_DIR = LAKE_COMMAND_CENTER_DIR / "troubleshooting"
LAKE_COMMAND_CENTER_QUALITY_DIR = LAKE_COMMAND_CENTER_DIR / "quality"

REPORTS_COMMAND_CENTER_DIR = REPORTS_DIR / "command_center"
REPORTS_COMMAND_CENTER_CSV_DIR = REPORTS_COMMAND_CENTER_DIR / "csv"
REPORTS_COMMAND_CENTER_MARKDOWN_DIR = REPORTS_COMMAND_CENTER_DIR / "markdown"
REPORTS_COMMAND_CENTER_TXT_DIR = REPORTS_COMMAND_CENTER_DIR / "txt"
REPORTS_COMMAND_CENTER_JSON_DIR = REPORTS_COMMAND_CENTER_DIR / "json"

class ProjectPaths:

    # Secrets Hygiene Lake Paths
    lake_secrets_hygiene_dir: Path = LAKE_DIR / "secrets_hygiene"
    lake_secrets_hygiene_sensitive_files_dir: Path = lake_secrets_hygiene_dir / "sensitive_files"
    lake_secrets_hygiene_pattern_findings_dir: Path = lake_secrets_hygiene_dir / "pattern_findings"
    lake_secrets_hygiene_entropy_findings_dir: Path = lake_secrets_hygiene_dir / "entropy_findings"
    lake_secrets_hygiene_env_template_audit_dir: Path = lake_secrets_hygiene_dir / "env_template_audit"
    lake_secrets_hygiene_credential_boundary_dir: Path = lake_secrets_hygiene_dir / "credential_boundary"
    lake_secrets_hygiene_private_data_dir: Path = lake_secrets_hygiene_dir / "private_data"
    lake_secrets_hygiene_gitignore_dir: Path = lake_secrets_hygiene_dir / "gitignore"
    lake_secrets_hygiene_config_boundary_dir: Path = lake_secrets_hygiene_dir / "config_boundary"
    lake_secrets_hygiene_leakage_dir: Path = lake_secrets_hygiene_dir / "leakage"
    lake_secrets_hygiene_source_audit_dir: Path = lake_secrets_hygiene_dir / "source_audit"
    lake_secrets_hygiene_test_fixtures_dir: Path = lake_secrets_hygiene_dir / "test_fixtures"
    lake_secrets_hygiene_documentation_dir: Path = lake_secrets_hygiene_dir / "documentation"
    lake_secrets_hygiene_backup_packaging_dir: Path = lake_secrets_hygiene_dir / "backup_packaging"
    lake_secrets_hygiene_remediation_dir: Path = lake_secrets_hygiene_dir / "remediation"
    lake_secrets_hygiene_runbooks_dir: Path = lake_secrets_hygiene_dir / "runbooks"
    lake_secrets_hygiene_safety_dir: Path = lake_secrets_hygiene_dir / "safety"
    lake_secrets_hygiene_quality_dir: Path = lake_secrets_hygiene_dir / "quality"

    # Secrets Hygiene Report Outputs
    output_secrets_hygiene_dir: Path = REPORTS_OUTPUT_DIR / "secrets_hygiene"
    output_secrets_hygiene_csv_dir: Path = output_secrets_hygiene_dir / "csv"
    output_secrets_hygiene_markdown_dir: Path = output_secrets_hygiene_dir / "markdown"
    output_secrets_hygiene_txt_dir: Path = output_secrets_hygiene_dir / "txt"
    output_secrets_hygiene_json_dir: Path = output_secrets_hygiene_dir / "json"

    # Secrets Hygiene Docs Output
    docs_generated_secrets_hygiene_dir: Path = (DOCS_DIR / "generated") / "secrets_hygiene"

    LAKE_PERFORMANCE = LAKE_DIR / "performance"
    LAKE_PERFORMANCE_PROFILES = LAKE_PERFORMANCE / "profiles"
    LAKE_PERFORMANCE_RUNTIME = LAKE_PERFORMANCE / "runtime"
    LAKE_PERFORMANCE_MEMORY = LAKE_PERFORMANCE / "memory"
    LAKE_PERFORMANCE_BUDGET = LAKE_PERFORMANCE / "resource_budget"
    LAKE_PERFORMANCE_CPU_GPU = LAKE_PERFORMANCE / "cpu_gpu"
    LAKE_PERFORMANCE_CACHE = LAKE_PERFORMANCE / "cache"
    LAKE_PERFORMANCE_BATCH_PLANS = LAKE_PERFORMANCE / "batch_plans"
    LAKE_PERFORMANCE_CHECKPOINTS = LAKE_PERFORMANCE / "checkpoints"
    LAKE_PERFORMANCE_STABILITY = LAKE_PERFORMANCE / "stability"
    LAKE_PERFORMANCE_BOTTLENECKS = LAKE_PERFORMANCE / "bottlenecks"
    LAKE_PERFORMANCE_OPTIMIZATION = LAKE_PERFORMANCE / "optimization"
    LAKE_PERFORMANCE_QUALITY = LAKE_PERFORMANCE / "quality"

    REPORTS_PERFORMANCE = REPORTS_OUTPUT_DIR / "performance"
    REPORTS_PERFORMANCE_CSV = REPORTS_PERFORMANCE / "csv"
    REPORTS_PERFORMANCE_MARKDOWN = REPORTS_PERFORMANCE / "markdown"
    REPORTS_PERFORMANCE_TXT = REPORTS_PERFORMANCE / "txt"
    REPORTS_PERFORMANCE_JSON = REPORTS_PERFORMANCE / "json"

    LAKE_DOCUMENTATION_DIR = LAKE_DIR / "documentation"
    LAKE_DOCUMENTATION_INVENTORY_DIR = LAKE_DOCUMENTATION_DIR / "inventory"
    LAKE_DOCUMENTATION_COVERAGE_DIR = LAKE_DOCUMENTATION_DIR / "coverage"
    LAKE_DOCUMENTATION_LINK_CHECKS_DIR = LAKE_DOCUMENTATION_DIR / "link_checks"
    LAKE_DOCUMENTATION_SAFETY_SCAN_DIR = LAKE_DOCUMENTATION_DIR / "safety_scan"
    LAKE_DOCUMENTATION_CONSISTENCY_DIR = LAKE_DOCUMENTATION_DIR / "consistency"
    LAKE_DOCUMENTATION_MANIFESTS_DIR = LAKE_DOCUMENTATION_DIR / "manifests"
    LAKE_DOCUMENTATION_INDEX_DIR = LAKE_DOCUMENTATION_DIR / "index"
    LAKE_DOCUMENTATION_QUALITY_DIR = LAKE_DOCUMENTATION_DIR / "quality"

    REPORTS_DOCUMENTATION_DIR = REPORTS_OUTPUT_DIR / "documentation"
    REPORTS_DOCUMENTATION_CSV_DIR = REPORTS_DOCUMENTATION_DIR / "csv"
    REPORTS_DOCUMENTATION_MARKDOWN_DIR = REPORTS_DOCUMENTATION_DIR / "markdown"
    REPORTS_DOCUMENTATION_TXT_DIR = REPORTS_DOCUMENTATION_DIR / "txt"
    REPORTS_DOCUMENTATION_JSON_DIR = REPORTS_DOCUMENTATION_DIR / "json"

    def __init__(self):

        self.experiments_dir = LAKE_EXPERIMENTS_DIR
        self.experiments_hypotheses = LAKE_EXPERIMENTS_HYPOTHESES_DIR
        self.experiments_definitions = LAKE_EXPERIMENTS_DEFINITIONS_DIR
        self.experiments_runs = LAKE_EXPERIMENTS_RUNS_DIR
        self.experiments_artifacts = LAKE_EXPERIMENTS_ARTIFACTS_DIR
        self.experiments_reproducibility = LAKE_EXPERIMENTS_REPRODUCIBILITY_DIR
        self.experiments_versions = LAKE_EXPERIMENTS_VERSIONS_DIR
        self.experiments_ablation = LAKE_EXPERIMENTS_ABLATION_DIR
        self.experiments_comparisons = LAKE_EXPERIMENTS_COMPARISONS_DIR
        self.experiments_leaderboards = LAKE_EXPERIMENTS_LEADERBOARDS_DIR
        self.experiments_quality = LAKE_EXPERIMENTS_QUALITY_DIR

        self.experiments_reports = REPORTS_EXPERIMENTS_DIR
        self.experiments_reports_csv = REPORTS_EXPERIMENTS_CSV_DIR
        self.experiments_reports_markdown = REPORTS_EXPERIMENTS_MARKDOWN_DIR
        self.experiments_reports_txt = REPORTS_EXPERIMENTS_TXT_DIR
        self.experiments_reports_json = REPORTS_EXPERIMENTS_JSON_DIR

        self.project_root = PROJECT_ROOT
        self.data_dir = DATA_DIR
        self.lake_dir = LAKE_DIR
        self.reports_dir = REPORTS_DIR
        self.backtests = LAKE_DIR / "backtests"
        self.backtest_runs = self.backtests / "runs"
        self.backtest_trades = self.backtests / "trades"
        self.backtest_equity_curves = self.backtests / "equity_curves"
        self.backtest_audits = self.backtests / "audits"
        self.backtest_reports = REPORTS_DIR / "backtest_reports"
        self.ml_dir = LAKE_ML_DIR
        self.ml_features = LAKE_ML_FEATURES_DIR
        self.ml_targets = LAKE_ML_TARGETS_DIR
        self.ml_datasets = LAKE_ML_DATASETS_DIR
        self.ml_splits = LAKE_ML_SPLITS_DIR
        self.ml_metadata = LAKE_ML_METADATA_DIR
        self.ml_quality = LAKE_ML_QUALITY_DIR
        self.ml_models = LAKE_ML_MODELS_DIR
        self.ml_model_artifacts = LAKE_ML_MODEL_ARTIFACTS_DIR
        self.ml_model_registry = LAKE_ML_MODEL_REGISTRY_DIR
        self.ml_model_evaluations = LAKE_ML_MODEL_EVALUATIONS_DIR
        self.ml_model_cv = LAKE_ML_MODEL_CV_DIR
        self.ml_model_quality = LAKE_ML_MODEL_QUALITY_DIR
        self.ml_training_reports = REPORTS_ML_TRAINING_REPORTS_DIR
        self.ml_reports = REPORTS_ML_REPORTS_DIR

        # Phase 32: ML Context Integration
        self.ml_integration = LAKE_ML_INTEGRATION_DIR
        self.ml_integration_features = LAKE_ML_INTEGRATION_FEATURES_DIR
        self.ml_integration_alignment = LAKE_ML_INTEGRATION_ALIGNMENT_DIR
        self.ml_integration_conflicts = LAKE_ML_INTEGRATION_CONFLICTS_DIR
        self.ml_integration_quality = LAKE_ML_INTEGRATION_QUALITY_DIR
        self.ml_integration_reports = REPORTS_ML_INTEGRATION_REPORTS_DIR

        # Phase 33: Paper Trading
        self.paper_dir = LAKE_PAPER_DIR
        self.paper_runs = LAKE_PAPER_RUNS_DIR
        self.paper_orders = LAKE_PAPER_ORDERS_DIR
        self.paper_order_books = LAKE_PAPER_ORDER_BOOKS_DIR
        self.paper_positions = LAKE_PAPER_POSITIONS_DIR
        self.paper_portfolios = LAKE_PAPER_PORTFOLIOS_DIR
        self.paper_ledgers = LAKE_PAPER_LEDGERS_DIR
        self.paper_equity_curves = LAKE_PAPER_EQUITY_CURVES_DIR
        self.paper_audits = LAKE_PAPER_AUDITS_DIR
        self.paper_quality = LAKE_PAPER_QUALITY_DIR
        self.paper_reports = PAPER_REPORTS_DIR


        # Phase 34: Notifications
        self.LAKE_NOTIFICATIONS_DIR = LAKE_NOTIFICATIONS_DIR
        self.LAKE_NOTIFICATIONS_MESSAGES_DIR = LAKE_NOTIFICATIONS_MESSAGES_DIR
        self.LAKE_NOTIFICATIONS_DELIVERY_LOGS_DIR = LAKE_NOTIFICATIONS_DELIVERY_LOGS_DIR
        self.LAKE_NOTIFICATIONS_AUDITS_DIR = LAKE_NOTIFICATIONS_AUDITS_DIR
        self.LAKE_NOTIFICATIONS_QUALITY_DIR = LAKE_NOTIFICATIONS_QUALITY_DIR
        self.NOTIFICATION_REPORT_OUTPUT_DIR = NOTIFICATION_REPORT_OUTPUT_DIR

        # Phase 37: Security
        self.security_dir = LAKE_SECURITY_DIR
        self.security_audits = LAKE_SECURITY_AUDITS_DIR
        self.security_secret_hygiene = LAKE_SECURITY_SECRET_HYGIENE_DIR
        self.security_config_hardening = LAKE_SECURITY_CONFIG_HARDENING_DIR
        self.security_safe_defaults = LAKE_SECURITY_SAFE_DEFAULTS_DIR
        self.security_permissions = LAKE_SECURITY_PERMISSIONS_DIR
        self.security_path_safety = LAKE_SECURITY_PATH_SAFETY_DIR
        self.security_token_scans = LAKE_SECURITY_TOKEN_SCANS_DIR
        self.security_readiness = LAKE_SECURITY_READINESS_DIR
        self.security_quality = LAKE_SECURITY_QUALITY_DIR
        self.security_reports = REPORTS_SECURITY_REPORTS_DIR


        # Phase 42: Portfolio Regime Research
        self.portfolio_regime_dir = LAKE_PORTFOLIO_REGIME_DIR
        self.portfolio_regime_regimes = LAKE_PORTFOLIO_REGIME_REGIMES_DIR
        self.portfolio_regime_conditioned_returns = LAKE_PORTFOLIO_REGIME_CONDITIONED_RETURNS_DIR
        self.portfolio_regime_correlation = LAKE_PORTFOLIO_REGIME_CORRELATION_DIR
        self.portfolio_regime_scenarios = LAKE_PORTFOLIO_REGIME_SCENARIOS_DIR
        self.portfolio_regime_stress_tests = LAKE_PORTFOLIO_REGIME_STRESS_TESTS_DIR
        self.portfolio_regime_drawdowns = LAKE_PORTFOLIO_REGIME_DRAWDOWNS_DIR
        self.portfolio_regime_recovery = LAKE_PORTFOLIO_REGIME_RECOVERY_DIR
        self.portfolio_regime_tail_risk = LAKE_PORTFOLIO_REGIME_TAIL_RISK_DIR
        self.portfolio_regime_exposure = LAKE_PORTFOLIO_REGIME_EXPOSURE_DIR
        self.portfolio_regime_quality = LAKE_PORTFOLIO_REGIME_QUALITY_DIR

        self.portfolio_regime_reports = REPORTS_PORTFOLIO_REGIME_DIR

        # Phase 43: Synthetic Indices
        self.synthetic_indices_dir = LAKE_SYNTHETIC_INDICES_DIR
        self.synthetic_indices_definitions = LAKE_SYNTHETIC_INDICES_DEFINITIONS_DIR
        self.synthetic_indices_levels = LAKE_SYNTHETIC_INDICES_LEVELS_DIR
        self.synthetic_indices_returns = LAKE_SYNTHETIC_INDICES_RETURNS_DIR
        self.synthetic_indices_relative_strength = LAKE_SYNTHETIC_INDICES_RELATIVE_STRENGTH_DIR
        self.synthetic_indices_relative_momentum = LAKE_SYNTHETIC_INDICES_RELATIVE_MOMENTUM_DIR
        self.synthetic_indices_rotation = LAKE_SYNTHETIC_INDICES_ROTATION_DIR
        self.synthetic_indices_leadership = LAKE_SYNTHETIC_INDICES_LEADERSHIP_DIR
        self.synthetic_indices_comparisons = LAKE_SYNTHETIC_INDICES_COMPARISONS_DIR
        self.synthetic_indices_performance = LAKE_SYNTHETIC_INDICES_PERFORMANCE_DIR
        self.synthetic_indices_quality = LAKE_SYNTHETIC_INDICES_QUALITY_DIR
        self.synthetic_indices_reports = REPORTS_SYNTHETIC_INDICES_DIR
        self.synthetic_indices_reports_csv = REPORTS_SYNTHETIC_INDICES_CSV_DIR
        self.synthetic_indices_reports_markdown = REPORTS_SYNTHETIC_INDICES_MARKDOWN_DIR
        self.synthetic_indices_reports_txt = REPORTS_SYNTHETIC_INDICES_TXT_DIR

        # Phase 44: Factor Research
        self.factor_research_dir = LAKE_FACTOR_RESEARCH_DIR
        self.factor_research_definitions = LAKE_FACTOR_RESEARCH_DEFINITIONS_DIR
        self.factor_research_scores = LAKE_FACTOR_RESEARCH_SCORES_DIR
        self.factor_research_ranks = LAKE_FACTOR_RESEARCH_RANKS_DIR
        self.factor_research_backtests = LAKE_FACTOR_RESEARCH_BACKTESTS_DIR
        self.factor_research_ic = LAKE_FACTOR_RESEARCH_IC_DIR
        self.factor_research_stability = LAKE_FACTOR_RESEARCH_STABILITY_DIR
        self.factor_research_exposure = LAKE_FACTOR_RESEARCH_EXPOSURE_DIR
        self.factor_research_neutralization = LAKE_FACTOR_RESEARCH_NEUTRALIZATION_DIR
        self.factor_research_quality = LAKE_FACTOR_RESEARCH_QUALITY_DIR
        self.factor_research_lake_reports = LAKE_FACTOR_RESEARCH_REPORTS_DIR

        self.factor_research_reports = REPORTS_FACTOR_RESEARCH_DIR
        self.factor_research_reports_csv = REPORTS_FACTOR_RESEARCH_CSV_DIR
        self.factor_research_reports_markdown = REPORTS_FACTOR_RESEARCH_MARKDOWN_DIR
        self.factor_research_reports_txt = REPORTS_FACTOR_RESEARCH_TXT_DIR

        # Phase 47: Governance
        self.DATA_LAKE_GOVERNANCE_DIR = DATA_LAKE_GOVERNANCE_DIR
        self.DATA_LAKE_GOVERNANCE_INVENTORY_DIR = DATA_LAKE_GOVERNANCE_INVENTORY_DIR
        self.DATA_LAKE_GOVERNANCE_FINGERPRINTS_DIR = DATA_LAKE_GOVERNANCE_FINGERPRINTS_DIR
        self.DATA_LAKE_GOVERNANCE_PROVENANCE_DIR = DATA_LAKE_GOVERNANCE_PROVENANCE_DIR
        self.DATA_LAKE_GOVERNANCE_LINEAGE_DIR = DATA_LAKE_GOVERNANCE_LINEAGE_DIR
        self.DATA_LAKE_GOVERNANCE_DEPENDENCIES_DIR = DATA_LAKE_GOVERNANCE_DEPENDENCIES_DIR
        self.DATA_LAKE_GOVERNANCE_AUDIT_DIR = DATA_LAKE_GOVERNANCE_AUDIT_DIR
        self.DATA_LAKE_GOVERNANCE_SOURCE_ATTRIBUTION_DIR = DATA_LAKE_GOVERNANCE_SOURCE_ATTRIBUTION_DIR
        self.DATA_LAKE_GOVERNANCE_CHECKLISTS_DIR = DATA_LAKE_GOVERNANCE_CHECKLISTS_DIR
        self.DATA_LAKE_GOVERNANCE_QUALITY_DIR = DATA_LAKE_GOVERNANCE_QUALITY_DIR

        self.REPORTS_GOVERNANCE_DIR = REPORTS_GOVERNANCE_DIR
        self.REPORTS_GOVERNANCE_CSV_DIR = REPORTS_GOVERNANCE_CSV_DIR
        self.REPORTS_GOVERNANCE_MARKDOWN_DIR = REPORTS_GOVERNANCE_MARKDOWN_DIR
        self.REPORTS_GOVERNANCE_TXT_DIR = REPORTS_GOVERNANCE_TXT_DIR
        self.REPORTS_GOVERNANCE_JSON_DIR = REPORTS_GOVERNANCE_JSON_DIR

        self.LAKE_KNOWLEDGE_BASE_DIR = LAKE_KNOWLEDGE_BASE_DIR
        self.LAKE_KNOWLEDGE_BASE_DOCUMENTS_DIR = LAKE_KNOWLEDGE_BASE_DOCUMENTS_DIR
        self.LAKE_KNOWLEDGE_BASE_CHUNKS_DIR = LAKE_KNOWLEDGE_BASE_CHUNKS_DIR
        self.LAKE_KNOWLEDGE_BASE_INDEXES_DIR = LAKE_KNOWLEDGE_BASE_INDEXES_DIR
        self.LAKE_KNOWLEDGE_BASE_RETRIEVAL_DIR = LAKE_KNOWLEDGE_BASE_RETRIEVAL_DIR
        self.LAKE_KNOWLEDGE_BASE_MEMORY_CARDS_DIR = LAKE_KNOWLEDGE_BASE_MEMORY_CARDS_DIR
        self.LAKE_KNOWLEDGE_BASE_DECISION_JOURNAL_DIR = LAKE_KNOWLEDGE_BASE_DECISION_JOURNAL_DIR
        self.LAKE_KNOWLEDGE_BASE_ANALYST_NOTES_DIR = LAKE_KNOWLEDGE_BASE_ANALYST_NOTES_DIR
        self.LAKE_KNOWLEDGE_BASE_FINDINGS_DIR = LAKE_KNOWLEDGE_BASE_FINDINGS_DIR
        self.LAKE_KNOWLEDGE_BASE_WORKSPACE_DIR = LAKE_KNOWLEDGE_BASE_WORKSPACE_DIR

        self.LAKE_KNOWLEDGE_BASE_QUALITY_DIR = LAKE_KNOWLEDGE_BASE_QUALITY_DIR
        self.REPORTS_KNOWLEDGE_BASE_DIR = REPORTS_KNOWLEDGE_BASE_DIR
        self.REPORTS_KNOWLEDGE_BASE_CSV_DIR = REPORTS_KNOWLEDGE_BASE_CSV_DIR
        self.REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR = REPORTS_KNOWLEDGE_BASE_MARKDOWN_DIR
        self.REPORTS_KNOWLEDGE_BASE_TXT_DIR = REPORTS_KNOWLEDGE_BASE_TXT_DIR
        self.REPORTS_KNOWLEDGE_BASE_JSON_DIR = REPORTS_KNOWLEDGE_BASE_JSON_DIR

        # Phase 50: Command Center
        self.LAKE_COMMAND_CENTER_DIR = LAKE_COMMAND_CENTER_DIR
        self.LAKE_COMMAND_CENTER_REGISTRY_DIR = LAKE_COMMAND_CENTER_REGISTRY_DIR
        self.LAKE_COMMAND_CENTER_WORKFLOWS_DIR = LAKE_COMMAND_CENTER_WORKFLOWS_DIR
        self.LAKE_COMMAND_CENTER_RUNBOOKS_DIR = LAKE_COMMAND_CENTER_RUNBOOKS_DIR
        self.LAKE_COMMAND_CENTER_DRY_RUN_PLANS_DIR = LAKE_COMMAND_CENTER_DRY_RUN_PLANS_DIR
        self.LAKE_COMMAND_CENTER_QUERY_FLOWS_DIR = LAKE_COMMAND_CENTER_QUERY_FLOWS_DIR
        self.LAKE_COMMAND_CENTER_PROJECT_STATUS_DIR = LAKE_COMMAND_CENTER_PROJECT_STATUS_DIR
        self.LAKE_COMMAND_CENTER_MODULE_HEALTH_DIR = LAKE_COMMAND_CENTER_MODULE_HEALTH_DIR
        self.LAKE_COMMAND_CENTER_SCRIPT_DISCOVERY_DIR = LAKE_COMMAND_CENTER_SCRIPT_DISCOVERY_DIR
        self.LAKE_COMMAND_CENTER_PHASE_COVERAGE_DIR = LAKE_COMMAND_CENTER_PHASE_COVERAGE_DIR
        self.LAKE_COMMAND_CENTER_CONSOLIDATION_DIR = LAKE_COMMAND_CENTER_CONSOLIDATION_DIR
        self.LAKE_COMMAND_CENTER_ONBOARDING_DIR = LAKE_COMMAND_CENTER_ONBOARDING_DIR
        self.LAKE_COMMAND_CENTER_TROUBLESHOOTING_DIR = LAKE_COMMAND_CENTER_TROUBLESHOOTING_DIR
        self.LAKE_COMMAND_CENTER_QUALITY_DIR = LAKE_COMMAND_CENTER_QUALITY_DIR

        self.REPORTS_COMMAND_CENTER_DIR = REPORTS_COMMAND_CENTER_DIR
        self.REPORTS_COMMAND_CENTER_CSV_DIR = REPORTS_COMMAND_CENTER_CSV_DIR
        self.REPORTS_COMMAND_CENTER_MARKDOWN_DIR = REPORTS_COMMAND_CENTER_MARKDOWN_DIR
        self.REPORTS_COMMAND_CENTER_TXT_DIR = REPORTS_COMMAND_CENTER_TXT_DIR
        self.REPORTS_COMMAND_CENTER_JSON_DIR = REPORTS_COMMAND_CENTER_JSON_DIR

        # Phase 57: Scenario Regression
        self.scenario_regression_dir = LAKE_SCENARIO_REGRESSION_DIR
        self.scenario_regression_registry_dir = LAKE_SCENARIO_REGRESSION_REGISTRY_DIR
        self.scenario_regression_golden_outputs_dir = LAKE_SCENARIO_REGRESSION_GOLDEN_OUTPUTS_DIR
        self.scenario_regression_snapshots_dir = LAKE_SCENARIO_REGRESSION_SNAPSHOTS_DIR
        self.scenario_regression_snapshot_diffs_dir = LAKE_SCENARIO_REGRESSION_SNAPSHOT_DIFFS_DIR
        self.scenario_regression_replay_dir = LAKE_SCENARIO_REGRESSION_REPLAY_DIR
        self.scenario_regression_fixture_reproducibility_dir = LAKE_SCENARIO_REGRESSION_FIXTURE_REPRODUCIBILITY_DIR
        self.scenario_regression_output_contracts_dir = LAKE_SCENARIO_REGRESSION_OUTPUT_CONTRACTS_DIR
        self.scenario_regression_demo_workflows_dir = LAKE_SCENARIO_REGRESSION_DEMO_WORKFLOWS_DIR
        self.scenario_regression_end_to_end_acceptance_dir = LAKE_SCENARIO_REGRESSION_END_TO_END_ACCEPTANCE_DIR
        self.scenario_regression_drift_dir = LAKE_SCENARIO_REGRESSION_DRIFT_DIR
        self.scenario_regression_failures_dir = LAKE_SCENARIO_REGRESSION_FAILURES_DIR
        self.scenario_regression_checklists_dir = LAKE_SCENARIO_REGRESSION_CHECKLISTS_DIR
        self.scenario_regression_quality_dir = LAKE_SCENARIO_REGRESSION_QUALITY_DIR

        self.reports_scenario_regression_dir = REPORTS_SCENARIO_REGRESSION_DIR
        self.reports_scenario_regression_csv_dir = REPORTS_SCENARIO_REGRESSION_CSV_DIR
        self.reports_scenario_regression_markdown_dir = REPORTS_SCENARIO_REGRESSION_MARKDOWN_DIR
        self.reports_scenario_regression_txt_dir = REPORTS_SCENARIO_REGRESSION_TXT_DIR
        self.reports_scenario_regression_json_dir = REPORTS_SCENARIO_REGRESSION_JSON_DIR

        self.docs_scenario_regression_dir = DOCS_SCENARIO_REGRESSION_DIR







        # Phase 61: Portable Packaging
        self.LAKE_PORTABLE_PACKAGING_DIR = LAKE_PORTABLE_PACKAGING_DIR
        self.LAKE_PORTABLE_PACKAGING_ENVIRONMENT_DIR = LAKE_PORTABLE_PACKAGING_ENVIRONMENT_DIR
        self.LAKE_PORTABLE_PACKAGING_DEPENDENCIES_DIR = LAKE_PORTABLE_PACKAGING_DEPENDENCIES_DIR
        self.LAKE_PORTABLE_PACKAGING_REQUIREMENTS_DIR = LAKE_PORTABLE_PACKAGING_REQUIREMENTS_DIR
        self.LAKE_PORTABLE_PACKAGING_INSTALL_VERIFICATION_DIR = LAKE_PORTABLE_PACKAGING_INSTALL_VERIFICATION_DIR
        self.LAKE_PORTABLE_PACKAGING_IMPORT_VERIFICATION_DIR = LAKE_PORTABLE_PACKAGING_IMPORT_VERIFICATION_DIR
        self.LAKE_PORTABLE_PACKAGING_SCRIPT_VERIFICATION_DIR = LAKE_PORTABLE_PACKAGING_SCRIPT_VERIFICATION_DIR
        self.LAKE_PORTABLE_PACKAGING_CONFIG_VERIFICATION_DIR = LAKE_PORTABLE_PACKAGING_CONFIG_VERIFICATION_DIR
        self.LAKE_PORTABLE_PACKAGING_BUNDLE_MANIFEST_DIR = LAKE_PORTABLE_PACKAGING_BUNDLE_MANIFEST_DIR
        self.LAKE_PORTABLE_PACKAGING_ARCHIVE_MANIFEST_DIR = LAKE_PORTABLE_PACKAGING_ARCHIVE_MANIFEST_DIR
        self.LAKE_PORTABLE_PACKAGING_SOURCE_POLICY_DIR = LAKE_PORTABLE_PACKAGING_SOURCE_POLICY_DIR
        self.LAKE_PORTABLE_PACKAGING_SETUP_GUIDES_DIR = LAKE_PORTABLE_PACKAGING_SETUP_GUIDES_DIR
        self.LAKE_PORTABLE_PACKAGING_DRIFT_DIR = LAKE_PORTABLE_PACKAGING_DRIFT_DIR
        self.LAKE_PORTABLE_PACKAGING_SAFETY_DIR = LAKE_PORTABLE_PACKAGING_SAFETY_DIR
        self.LAKE_PORTABLE_PACKAGING_QUALITY_DIR = LAKE_PORTABLE_PACKAGING_QUALITY_DIR

        self.REPORTS_PORTABLE_PACKAGING_DIR = REPORTS_PORTABLE_PACKAGING_DIR
        self.REPORTS_PORTABLE_PACKAGING_CSV_DIR = REPORTS_PORTABLE_PACKAGING_CSV_DIR
        self.REPORTS_PORTABLE_PACKAGING_MARKDOWN_DIR = REPORTS_PORTABLE_PACKAGING_MARKDOWN_DIR
        self.REPORTS_PORTABLE_PACKAGING_TXT_DIR = REPORTS_PORTABLE_PACKAGING_TXT_DIR
        self.REPORTS_PORTABLE_PACKAGING_JSON_DIR = REPORTS_PORTABLE_PACKAGING_JSON_DIR

        self.PORTABLE_BUNDLE_DIR = PORTABLE_BUNDLE_DIR
        self.PORTABLE_BUNDLE_MANIFESTS_DIR = PORTABLE_BUNDLE_MANIFESTS_DIR
        self.PORTABLE_BUNDLE_SETUP_DIR = PORTABLE_BUNDLE_SETUP_DIR
        self.PORTABLE_BUNDLE_ARCHIVE_PLANS_DIR = PORTABLE_BUNDLE_ARCHIVE_PLANS_DIR

        self.DOCS_PORTABLE_PACKAGING_DIR = DOCS_PORTABLE_PACKAGING_DIR

# Phase 39: Research Reports

# Phase 57: Scenario Regression
LAKE_SCENARIO_REGRESSION_DIR = LAKE_DIR / "scenario_regression"
LAKE_SCENARIO_REGRESSION_REGISTRY_DIR = LAKE_SCENARIO_REGRESSION_DIR / "registry"
LAKE_SCENARIO_REGRESSION_GOLDEN_OUTPUTS_DIR = LAKE_SCENARIO_REGRESSION_DIR / "golden_outputs"
LAKE_SCENARIO_REGRESSION_SNAPSHOTS_DIR = LAKE_SCENARIO_REGRESSION_DIR / "snapshots"
LAKE_SCENARIO_REGRESSION_SNAPSHOT_DIFFS_DIR = LAKE_SCENARIO_REGRESSION_DIR / "snapshot_diffs"
LAKE_SCENARIO_REGRESSION_REPLAY_DIR = LAKE_SCENARIO_REGRESSION_DIR / "replay"
LAKE_SCENARIO_REGRESSION_FIXTURE_REPRODUCIBILITY_DIR = LAKE_SCENARIO_REGRESSION_DIR / "fixture_reproducibility"
LAKE_SCENARIO_REGRESSION_OUTPUT_CONTRACTS_DIR = LAKE_SCENARIO_REGRESSION_DIR / "output_contracts"
LAKE_SCENARIO_REGRESSION_DEMO_WORKFLOWS_DIR = LAKE_SCENARIO_REGRESSION_DIR / "demo_workflows"
LAKE_SCENARIO_REGRESSION_END_TO_END_ACCEPTANCE_DIR = LAKE_SCENARIO_REGRESSION_DIR / "end_to_end_acceptance"
LAKE_SCENARIO_REGRESSION_DRIFT_DIR = LAKE_SCENARIO_REGRESSION_DIR / "drift"
LAKE_SCENARIO_REGRESSION_FAILURES_DIR = LAKE_SCENARIO_REGRESSION_DIR / "failures"
LAKE_SCENARIO_REGRESSION_CHECKLISTS_DIR = LAKE_SCENARIO_REGRESSION_DIR / "checklists"
LAKE_SCENARIO_REGRESSION_QUALITY_DIR = LAKE_SCENARIO_REGRESSION_DIR / "quality"

REPORTS_SCENARIO_REGRESSION_DIR = REPORTS_DIR / "scenario_regression"
REPORTS_SCENARIO_REGRESSION_CSV_DIR = REPORTS_SCENARIO_REGRESSION_DIR / "csv"
REPORTS_SCENARIO_REGRESSION_MARKDOWN_DIR = REPORTS_SCENARIO_REGRESSION_DIR / "markdown"
REPORTS_SCENARIO_REGRESSION_TXT_DIR = REPORTS_SCENARIO_REGRESSION_DIR / "txt"
REPORTS_SCENARIO_REGRESSION_JSON_DIR = REPORTS_SCENARIO_REGRESSION_DIR / "json"

DOCS_SCENARIO_REGRESSION_DIR = PROJECT_ROOT / "docs" / "generated" / "scenario_regression"

LAKE_RESEARCH_REPORTS_DIR = LAKE_DIR / "research_reports"
LAKE_RESEARCH_REPORTS_SYMBOL_DIR = LAKE_RESEARCH_REPORTS_DIR / "symbol"
LAKE_RESEARCH_REPORTS_UNIVERSE_DIR = LAKE_RESEARCH_REPORTS_DIR / "universe"
LAKE_RESEARCH_REPORTS_DAILY_DIGEST_DIR = LAKE_RESEARCH_REPORTS_DIR / "daily_digest"
LAKE_RESEARCH_REPORTS_RANKINGS_DIR = LAKE_RESEARCH_REPORTS_DIR / "rankings"
LAKE_RESEARCH_REPORTS_TABLES_DIR = LAKE_RESEARCH_REPORTS_DIR / "tables"
LAKE_RESEARCH_REPORTS_QUALITY_DIR = LAKE_RESEARCH_REPORTS_DIR / "quality"
REPORTS_RESEARCH_REPORTS_DIR = REPORTS_DIR / "research_reports"
REPORTS_RESEARCH_REPORTS_MARKDOWN_DIR = REPORTS_RESEARCH_REPORTS_DIR / "markdown"
REPORTS_RESEARCH_REPORTS_CSV_DIR = REPORTS_RESEARCH_REPORTS_DIR / "csv"
REPORTS_RESEARCH_REPORTS_TXT_DIR = REPORTS_RESEARCH_REPORTS_DIR / "txt"

# Phase 58: Analyst UX
LAKE_ANALYST_UX_DIR = LAKE_DIR / "analyst_ux"
LAKE_ANALYST_UX_PROFILES_DIR = LAKE_ANALYST_UX_DIR / "profiles"
LAKE_ANALYST_UX_ALIASES_DIR = LAKE_ANALYST_UX_DIR / "aliases"
LAKE_ANALYST_UX_INTENTS_DIR = LAKE_ANALYST_UX_DIR / "intents"
LAKE_ANALYST_UX_SUGGESTIONS_DIR = LAKE_ANALYST_UX_DIR / "suggestions"
LAKE_ANALYST_UX_PROMPT_PACKS_DIR = LAKE_ANALYST_UX_DIR / "prompt_packs"
LAKE_ANALYST_UX_WORKFLOW_SHORTCUTS_DIR = LAKE_ANALYST_UX_DIR / "workflow_shortcuts"
LAKE_ANALYST_UX_QUERY_MAPPINGS_DIR = LAKE_ANALYST_UX_DIR / "query_mappings"
LAKE_ANALYST_UX_TASK_BOARD_DIR = LAKE_ANALYST_UX_DIR / "task_board"
LAKE_ANALYST_UX_CHEAT_SHEETS_DIR = LAKE_ANALYST_UX_DIR / "cheat_sheets"
LAKE_ANALYST_UX_CHECKLISTS_DIR = LAKE_ANALYST_UX_DIR / "checklists"
LAKE_ANALYST_UX_VALIDATION_DIR = LAKE_ANALYST_UX_DIR / "validation"
LAKE_ANALYST_UX_QUALITY_DIR = LAKE_ANALYST_UX_DIR / "quality"

REPORTS_ANALYST_UX_DIR = REPORTS_DIR / "analyst_ux"
REPORTS_ANALYST_UX_CSV_DIR = REPORTS_ANALYST_UX_DIR / "csv"
REPORTS_ANALYST_UX_MARKDOWN_DIR = REPORTS_ANALYST_UX_DIR / "markdown"
REPORTS_ANALYST_UX_TXT_DIR = REPORTS_ANALYST_UX_DIR / "txt"
REPORTS_ANALYST_UX_JSON_DIR = REPORTS_ANALYST_UX_DIR / "json"

DOCS_ANALYST_UX_DIR = PROJECT_ROOT / "docs" / "generated" / "analyst_ux"

# Phase 61: Portable Packaging
LAKE_PORTABLE_PACKAGING_DIR = LAKE_DIR / "portable_packaging"
LAKE_PORTABLE_PACKAGING_ENVIRONMENT_DIR = LAKE_PORTABLE_PACKAGING_DIR / "environment"
LAKE_PORTABLE_PACKAGING_DEPENDENCIES_DIR = LAKE_PORTABLE_PACKAGING_DIR / "dependencies"
LAKE_PORTABLE_PACKAGING_REQUIREMENTS_DIR = LAKE_PORTABLE_PACKAGING_DIR / "requirements"
LAKE_PORTABLE_PACKAGING_INSTALL_VERIFICATION_DIR = LAKE_PORTABLE_PACKAGING_DIR / "install_verification"
LAKE_PORTABLE_PACKAGING_IMPORT_VERIFICATION_DIR = LAKE_PORTABLE_PACKAGING_DIR / "import_verification"
LAKE_PORTABLE_PACKAGING_SCRIPT_VERIFICATION_DIR = LAKE_PORTABLE_PACKAGING_DIR / "script_verification"
LAKE_PORTABLE_PACKAGING_CONFIG_VERIFICATION_DIR = LAKE_PORTABLE_PACKAGING_DIR / "config_verification"
LAKE_PORTABLE_PACKAGING_BUNDLE_MANIFEST_DIR = LAKE_PORTABLE_PACKAGING_DIR / "bundle_manifest"
LAKE_PORTABLE_PACKAGING_ARCHIVE_MANIFEST_DIR = LAKE_PORTABLE_PACKAGING_DIR / "archive_manifest"
LAKE_PORTABLE_PACKAGING_SOURCE_POLICY_DIR = LAKE_PORTABLE_PACKAGING_DIR / "source_policy"
LAKE_PORTABLE_PACKAGING_SETUP_GUIDES_DIR = LAKE_PORTABLE_PACKAGING_DIR / "setup_guides"
LAKE_PORTABLE_PACKAGING_DRIFT_DIR = LAKE_PORTABLE_PACKAGING_DIR / "drift"
LAKE_PORTABLE_PACKAGING_SAFETY_DIR = LAKE_PORTABLE_PACKAGING_DIR / "safety"
LAKE_PORTABLE_PACKAGING_QUALITY_DIR = LAKE_PORTABLE_PACKAGING_DIR / "quality"

REPORTS_PORTABLE_PACKAGING_DIR = REPORTS_DIR / "portable_packaging"
REPORTS_PORTABLE_PACKAGING_CSV_DIR = REPORTS_PORTABLE_PACKAGING_DIR / "csv"
REPORTS_PORTABLE_PACKAGING_MARKDOWN_DIR = REPORTS_PORTABLE_PACKAGING_DIR / "markdown"
REPORTS_PORTABLE_PACKAGING_TXT_DIR = REPORTS_PORTABLE_PACKAGING_DIR / "txt"
REPORTS_PORTABLE_PACKAGING_JSON_DIR = REPORTS_PORTABLE_PACKAGING_DIR / "json"

PORTABLE_BUNDLE_DIR = PROJECT_ROOT / "portable_bundle"
PORTABLE_BUNDLE_MANIFESTS_DIR = PORTABLE_BUNDLE_DIR / "manifests"
PORTABLE_BUNDLE_SETUP_DIR = PORTABLE_BUNDLE_DIR / "setup"
PORTABLE_BUNDLE_ARCHIVE_PLANS_DIR = PORTABLE_BUNDLE_DIR / "archive_plans"

DOCS_PORTABLE_PACKAGING_DIR = PROJECT_ROOT / "docs" / "generated" / "portable_packaging"
