"""
Path definitions and directory management for the project.
"""

from pathlib import Path

# Project root directory
PROJECT_ROOT = Path(__file__).parent.parent.resolve()

# Base directories
DATA_DIR = PROJECT_ROOT / "data"
LOGS_DIR = PROJECT_ROOT / "logs"
REPORTS_DIR = PROJECT_ROOT / "reports" / "output"

REPORTS_VALIDATION_DIR = REPORTS_DIR / "validation_reports"

# Meta Research paths
REPORTS_META_RESEARCH_DIR = REPORTS_DIR / "meta_research"
REPORTS_META_RESEARCH_CSV_DIR = REPORTS_META_RESEARCH_DIR / "csv"
REPORTS_META_RESEARCH_MD_DIR = REPORTS_META_RESEARCH_DIR / "markdown"
REPORTS_META_RESEARCH_TXT_DIR = REPORTS_META_RESEARCH_DIR / "txt"


# Specific data directories
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
CACHE_DIR = DATA_DIR / "cache"

# Data Lake directories
LAKE_DIR = DATA_DIR / "lake"
LAKE_OHLCV_DIR = LAKE_DIR / "ohlcv"
LAKE_MACRO_DIR = LAKE_DIR / "macro"
LAKE_MACRO_RAW_DIR = LAKE_MACRO_DIR / "raw"
LAKE_MACRO_PROCESSED_DIR = LAKE_MACRO_DIR / "processed"
LAKE_BENCHMARKS_DIR = LAKE_DIR / "benchmarks"
LAKE_SYNTHETIC_DIR = LAKE_DIR / "synthetic"
LAKE_MANIFESTS_DIR = LAKE_DIR / "manifests"
LAKE_JOURNALS_DIR = LAKE_DIR / "journals"

# Phase 36: Observability Lake Directories
LAKE_OBSERVABILITY_DIR = LAKE_DIR / "observability"
LAKE_OBSERVABILITY_LOGS_DIR = LAKE_OBSERVABILITY_DIR / "logs"
LAKE_OBSERVABILITY_JSON_LOGS_DIR = LAKE_OBSERVABILITY_DIR / "json_logs"
LAKE_OBSERVABILITY_HEALTH_DIR = LAKE_OBSERVABILITY_DIR / "health"
LAKE_OBSERVABILITY_RUNTIME_METRICS_DIR = LAKE_OBSERVABILITY_DIR / "runtime_metrics"
LAKE_OBSERVABILITY_DIAGNOSTICS_DIR = LAKE_OBSERVABILITY_DIR / "diagnostics"
LAKE_OBSERVABILITY_ERROR_TAXONOMY_DIR = LAKE_OBSERVABILITY_DIR / "error_taxonomy"
LAKE_OBSERVABILITY_DATA_FRESHNESS_DIR = LAKE_OBSERVABILITY_DIR / "data_freshness"
LAKE_OBSERVABILITY_ARTIFACT_INTEGRITY_DIR = LAKE_OBSERVABILITY_DIR / "artifact_integrity"
LAKE_OBSERVABILITY_QUALITY_DIR = LAKE_OBSERVABILITY_DIR / "quality"
REPORTS_OBSERVABILITY_DIR = REPORTS_DIR / "observability_reports"


# Processed Lake Directories
LAKE_PROCESSED_DIR = LAKE_DIR / "processed"
LAKE_PROCESSED_OHLCV_DIR = LAKE_PROCESSED_DIR / "ohlcv"
LAKE_QUALITY_REPORTS_DIR = LAKE_PROCESSED_DIR / "quality_reports"
LAKE_CLEANING_REPORTS_DIR = LAKE_PROCESSED_DIR / "cleaning_reports"

# Feature Lake Directories
LAKE_FEATURES_DIR = LAKE_DIR / "features"
LAKE_FEATURES_TECHNICAL_DIR = LAKE_FEATURES_DIR / "technical"
LAKE_FEATURES_MANIFESTS_DIR = LAKE_FEATURES_DIR / "manifests"
LAKE_FEATURES_REPORTS_DIR = LAKE_FEATURES_DIR / "reports"

INDICATOR_REPORTS_DIR = REPORTS_DIR / "indicator_reports"
LAKE_FEATURES_MOMENTUM_DIR = LAKE_FEATURES_DIR / "momentum"
LAKE_FEATURES_MOMENTUM_EVENTS_DIR = LAKE_FEATURES_DIR / "momentum_events"
MOMENTUM_REPORTS_DIR = REPORTS_DIR / "momentum_reports"

LAKE_FEATURES_TREND_DIR = LAKE_FEATURES_DIR / "trend"
LAKE_FEATURES_TREND_EVENTS_DIR = LAKE_FEATURES_DIR / "trend_events"

LAKE_FEATURES_TREND_DIR = LAKE_FEATURES_DIR / "trend"
LAKE_FEATURES_TREND_EVENTS_DIR = LAKE_FEATURES_DIR / "trend_events"
TREND_REPORTS_DIR = REPORTS_DIR / "trend_reports"


LAKE_FEATURES_VOLATILITY_DIR = LAKE_FEATURES_DIR / "volatility"
LAKE_FEATURES_VOLATILITY_EVENTS_DIR = LAKE_FEATURES_DIR / "volatility_events"
VOLATILITY_REPORTS_DIR = REPORTS_DIR / "volatility_reports"

LAKE_FEATURES_PRICE_ACTION_DIR = LAKE_FEATURES_DIR / "price_action"
LAKE_FEATURES_PRICE_ACTION_EVENTS_DIR = LAKE_FEATURES_DIR / "price_action_events"
PRICE_ACTION_REPORTS_DIR = REPORTS_DIR / "price_action_reports"

LAKE_FEATURES_DIVERGENCE_DIR = LAKE_FEATURES_DIR / "divergence"
LAKE_FEATURES_DIVERGENCE_EVENTS_DIR = LAKE_FEATURES_DIR / "divergence_events"
DIVERGENCE_REPORTS_DIR = REPORTS_DIR / "divergence_reports"


LAKE_FEATURES_MTF_DIR = LAKE_FEATURES_DIR / "mtf"
LAKE_FEATURES_MTF_EVENTS_DIR = LAKE_FEATURES_DIR / "mtf_events"
MTF_REPORTS_DIR = REPORTS_DIR / "mtf_reports"


LAKE_FEATURES_REGIME_DIR = LAKE_FEATURES_DIR / "regime"
LAKE_FEATURES_REGIME_EVENTS_DIR = LAKE_FEATURES_DIR / "regime_events"
REGIME_REPORTS_DIR = REPORTS_DIR / "regime_reports"

LAKE_FEATURES_MACRO_DIR = LAKE_FEATURES_DIR / "macro"
LAKE_FEATURES_MACRO_EVENTS_DIR = LAKE_FEATURES_DIR / "macro_events"
LAKE_FEATURES_BENCHMARKS_DIR = LAKE_FEATURES_DIR / "benchmarks"
MACRO_REPORTS_DIR = REPORTS_DIR / "macro_reports"

LAKE_TMP_DIR = LAKE_DIR / "tmp"


LAKE_FEATURES_ASSET_PROFILES_DIR = LAKE_FEATURES_DIR / "asset_profiles"
LAKE_FEATURES_ASSET_PROFILE_EVENTS_DIR = LAKE_FEATURES_DIR / "asset_profile_events"
LAKE_FEATURES_GROUP_FEATURES_DIR = LAKE_FEATURES_DIR / "group_features"
ASSET_PROFILE_REPORTS_DIR = REPORTS_DIR / "asset_profile_reports"

LAKE_FEATURES_SIGNAL_CANDIDATES_DIR = LAKE_FEATURES_DIR / "signal_candidates"
LAKE_FEATURES_SIGNAL_POOL_DIR = LAKE_FEATURES_DIR / "signal_pool"
SIGNAL_REPORTS_DIR = REPORTS_DIR / "signal_reports"
LAKE_FEATURES_DECISION_CANDIDATES_DIR = LAKE_FEATURES_DIR / "decision_candidates"
LAKE_FEATURES_DECISION_POOL_DIR = LAKE_FEATURES_DIR / "decision_pool"
DECISION_REPORTS_DIR = REPORTS_DIR / "decision_reports"

LAKE_FEATURES_STRATEGY_CANDIDATES_DIR = LAKE_FEATURES_DIR / "strategy_candidates"
LAKE_FEATURES_STRATEGY_POOL_DIR = LAKE_FEATURES_DIR / "strategy_pool"
STRATEGY_REPORTS_DIR = REPORTS_DIR / "strategy_reports"

LAKE_FEATURES_STRATEGY_RULE_CANDIDATES_DIR = (
    LAKE_FEATURES_DIR / "strategy_rule_candidates"
)
LAKE_FEATURES_ENTRY_EXIT_CANDIDATES_DIR = LAKE_FEATURES_DIR / "entry_exit_candidates"
LAKE_FEATURES_STRATEGY_RULE_POOL_DIR = LAKE_FEATURES_DIR / "strategy_rule_pool"
STRATEGY_RULE_REPORTS_DIR = REPORTS_DIR / "strategy_rule_reports"



# Phase 29: ML Dataset Preparation
LAKE_ML_DIR = LAKE_DIR / "ml"
LAKE_ML_FEATURES_DIR = LAKE_ML_DIR / "features"
LAKE_ML_TARGETS_DIR = LAKE_ML_DIR / "targets"
LAKE_ML_DATASETS_DIR = LAKE_ML_DIR / "datasets"
LAKE_ML_SPLITS_DIR = LAKE_ML_DIR / "splits"
LAKE_ML_METADATA_DIR = LAKE_ML_DIR / "metadata"
LAKE_ML_QUALITY_DIR = LAKE_ML_DIR / "quality"

# ML Training Directories
LAKE_ML_MODELS_DIR = LAKE_ML_DIR / "models"
LAKE_ML_MODEL_ARTIFACTS_DIR = LAKE_ML_DIR / "model_artifacts"
LAKE_ML_MODEL_REGISTRY_DIR = LAKE_ML_DIR / "model_registry"
LAKE_ML_MODEL_EVALUATIONS_DIR = LAKE_ML_DIR / "model_evaluations"
LAKE_ML_MODEL_CV_DIR = LAKE_ML_DIR / "model_cv"
LAKE_ML_MODEL_QUALITY_DIR = LAKE_ML_DIR / "model_quality"

REPORTS_ML_TRAINING_REPORTS_DIR = REPORTS_DIR / "ml_training_reports"
REPORTS_ML_REPORTS_DIR = REPORTS_DIR / "ml_reports"

# Phase 32: ML Context Integration
LAKE_ML_INTEGRATION_DIR = LAKE_ML_DIR / "integration"
LAKE_ML_INTEGRATION_FEATURES_DIR = LAKE_ML_INTEGRATION_DIR / "features"
LAKE_ML_INTEGRATION_ALIGNMENT_DIR = LAKE_ML_INTEGRATION_DIR / "alignment"
LAKE_ML_INTEGRATION_CONFLICTS_DIR = LAKE_ML_INTEGRATION_DIR / "conflicts"
LAKE_ML_INTEGRATION_QUALITY_DIR = LAKE_ML_INTEGRATION_DIR / "quality"
REPORTS_ML_INTEGRATION_REPORTS_DIR = REPORTS_DIR / "ml_integration_reports"



# Phase 33: Paper Trading Simulation
LAKE_PAPER_DIR = LAKE_DIR / "paper"
LAKE_PAPER_RUNS_DIR = LAKE_PAPER_DIR / "runs"
LAKE_PAPER_ORDERS_DIR = LAKE_PAPER_DIR / "orders"
LAKE_PAPER_ORDER_BOOKS_DIR = LAKE_PAPER_DIR / "order_books"
LAKE_PAPER_POSITIONS_DIR = LAKE_PAPER_DIR / "positions"
LAKE_PAPER_PORTFOLIOS_DIR = LAKE_PAPER_DIR / "portfolios"
LAKE_PAPER_LEDGERS_DIR = LAKE_PAPER_DIR / "ledgers"
LAKE_PAPER_EQUITY_CURVES_DIR = LAKE_PAPER_DIR / "equity_curves"
LAKE_PAPER_AUDITS_DIR = LAKE_PAPER_DIR / "audits"
LAKE_PAPER_QUALITY_DIR = LAKE_PAPER_DIR / "quality"
PAPER_REPORTS_DIR = REPORTS_DIR / "paper_reports"

LAKE_NOTIFICATIONS_DIR = LAKE_DIR / "notifications"
LAKE_NOTIFICATIONS_MESSAGES_DIR = LAKE_NOTIFICATIONS_DIR / "messages"
LAKE_NOTIFICATIONS_DELIVERY_LOGS_DIR = LAKE_NOTIFICATIONS_DIR / "delivery_logs"
LAKE_NOTIFICATIONS_AUDITS_DIR = LAKE_NOTIFICATIONS_DIR / "audits"
LAKE_NOTIFICATIONS_QUALITY_DIR = LAKE_NOTIFICATIONS_DIR / "quality"
NOTIFICATION_REPORT_OUTPUT_DIR = REPORTS_DIR / "notification_reports"




# Orchestration Output Directories
LAKE_ORCHESTRATION_DIR = DATA_DIR / "orchestration"
LAKE_ORCHESTRATION_RUNS_DIR = LAKE_ORCHESTRATION_DIR / "runs"
LAKE_ORCHESTRATION_MANIFESTS_DIR = LAKE_ORCHESTRATION_DIR / "manifests"
LAKE_ORCHESTRATION_DEPENDENCY_GRAPHS_DIR = LAKE_ORCHESTRATION_DIR / "dependency_graphs"
LAKE_ORCHESTRATION_EXECUTION_PLANS_DIR = LAKE_ORCHESTRATION_DIR / "execution_plans"
LAKE_ORCHESTRATION_JOB_LOGS_DIR = LAKE_ORCHESTRATION_DIR / "job_logs"
LAKE_ORCHESTRATION_QUALITY_DIR = LAKE_ORCHESTRATION_DIR / "quality"
ORCHESTRATION_REPORT_OUTPUT_DIR = REPORTS_DIR / "orchestration_reports"



# Phase 37: Security
LAKE_SECURITY_DIR = LAKE_DIR / "security"
LAKE_SECURITY_AUDITS_DIR = LAKE_SECURITY_DIR / "audits"
LAKE_SECURITY_SECRET_HYGIENE_DIR = LAKE_SECURITY_DIR / "secret_hygiene"
LAKE_SECURITY_CONFIG_HARDENING_DIR = LAKE_SECURITY_DIR / "config_hardening"
LAKE_SECURITY_SAFE_DEFAULTS_DIR = LAKE_SECURITY_DIR / "safe_defaults"
LAKE_SECURITY_PERMISSIONS_DIR = LAKE_SECURITY_DIR / "permissions"
LAKE_SECURITY_PATH_SAFETY_DIR = LAKE_SECURITY_DIR / "path_safety"
LAKE_SECURITY_TOKEN_SCANS_DIR = LAKE_SECURITY_DIR / "token_scans"
LAKE_SECURITY_READINESS_DIR = LAKE_SECURITY_DIR / "readiness"
LAKE_SECURITY_QUALITY_DIR = LAKE_SECURITY_DIR / "quality"
REPORTS_SECURITY_REPORTS_DIR = REPORTS_DIR / "security_reports"


# Phase 40: Report Exports, Archive and Comparisons
LAKE_REPORT_EXPORTS_DIR = LAKE_DIR / "report_exports"
LAKE_REPORT_EXPORTS_MANIFESTS_DIR = LAKE_REPORT_EXPORTS_DIR / "manifests"
LAKE_REPORT_EXPORTS_ARCHIVE_DIR = LAKE_REPORT_EXPORTS_DIR / "archive"
LAKE_REPORT_EXPORTS_COMPARISONS_DIR = LAKE_REPORT_EXPORTS_DIR / "comparisons"
LAKE_REPORT_EXPORTS_TRACKING_DIR = LAKE_REPORT_EXPORTS_DIR / "tracking"
LAKE_REPORT_EXPORTS_PACKAGES_DIR = LAKE_REPORT_EXPORTS_DIR / "packages"
LAKE_REPORT_EXPORTS_QUALITY_DIR = LAKE_REPORT_EXPORTS_DIR / "quality"

REPORTS_REPORT_EXPORTS_DIR = REPORTS_DIR / "report_exports"
REPORTS_REPORT_EXPORTS_HTML_DIR = REPORTS_REPORT_EXPORTS_DIR / "html"
REPORTS_REPORT_EXPORTS_PDF_DIR = REPORTS_REPORT_EXPORTS_DIR / "pdf"
REPORTS_REPORT_EXPORTS_CSV_DIR = REPORTS_REPORT_EXPORTS_DIR / "csv"
REPORTS_REPORT_EXPORTS_PACKAGES_DIR = REPORTS_REPORT_EXPORTS_DIR / "packages"
REPORTS_REPORT_EXPORTS_COMPARISONS_DIR = REPORTS_REPORT_EXPORTS_DIR / "comparisons"
REPORTS_REPORT_EXPORTS_TRACKING_DIR = REPORTS_REPORT_EXPORTS_DIR / "tracking"


# Phase 42: Portfolio Regime Research
LAKE_PORTFOLIO_REGIME_DIR = LAKE_DIR / "portfolio_regime"
LAKE_PORTFOLIO_REGIME_REGIMES_DIR = LAKE_PORTFOLIO_REGIME_DIR / "regimes"
LAKE_PORTFOLIO_REGIME_CONDITIONED_RETURNS_DIR = LAKE_PORTFOLIO_REGIME_DIR / "conditioned_returns"
LAKE_PORTFOLIO_REGIME_CORRELATION_DIR = LAKE_PORTFOLIO_REGIME_DIR / "correlation"
LAKE_PORTFOLIO_REGIME_SCENARIOS_DIR = LAKE_PORTFOLIO_REGIME_DIR / "scenarios"
LAKE_PORTFOLIO_REGIME_STRESS_TESTS_DIR = LAKE_PORTFOLIO_REGIME_DIR / "stress_tests"
LAKE_PORTFOLIO_REGIME_DRAWDOWNS_DIR = LAKE_PORTFOLIO_REGIME_DIR / "drawdowns"
LAKE_PORTFOLIO_REGIME_RECOVERY_DIR = LAKE_PORTFOLIO_REGIME_DIR / "recovery"
LAKE_PORTFOLIO_REGIME_TAIL_RISK_DIR = LAKE_PORTFOLIO_REGIME_DIR / "tail_risk"
LAKE_PORTFOLIO_REGIME_EXPOSURE_DIR = LAKE_PORTFOLIO_REGIME_DIR / "exposure"
LAKE_PORTFOLIO_REGIME_QUALITY_DIR = LAKE_PORTFOLIO_REGIME_DIR / "quality"

REPORTS_PORTFOLIO_REGIME_DIR = REPORTS_DIR / "portfolio_regime"
REPORTS_PORTFOLIO_REGIME_CSV_DIR = REPORTS_PORTFOLIO_REGIME_DIR / "csv"
REPORTS_PORTFOLIO_REGIME_MARKDOWN_DIR = REPORTS_PORTFOLIO_REGIME_DIR / "markdown"
REPORTS_PORTFOLIO_REGIME_TXT_DIR = REPORTS_PORTFOLIO_REGIME_DIR / "txt"

def ensure_project_directories() -> None:


    """
    Ensure that all required project directories exist.
    Creates them if they do not exist.
    """
    directories = [
        LOGS_DIR,
        REPORTS_DIR,
        RAW_DATA_DIR,
        PROCESSED_DATA_DIR,
        CACHE_DIR,
        LAKE_DIR,
        LAKE_OHLCV_DIR,
        LAKE_MACRO_DIR,
        LAKE_SYNTHETIC_DIR,
        LAKE_MANIFESTS_DIR,
        LAKE_JOURNALS_DIR,

        LAKE_OBSERVABILITY_DIR,
        LAKE_OBSERVABILITY_LOGS_DIR,
        LAKE_OBSERVABILITY_JSON_LOGS_DIR,
        LAKE_OBSERVABILITY_HEALTH_DIR,
        LAKE_OBSERVABILITY_RUNTIME_METRICS_DIR,
        LAKE_OBSERVABILITY_DIAGNOSTICS_DIR,
        LAKE_OBSERVABILITY_ERROR_TAXONOMY_DIR,
        LAKE_OBSERVABILITY_DATA_FRESHNESS_DIR,
        LAKE_OBSERVABILITY_ARTIFACT_INTEGRITY_DIR,
        LAKE_OBSERVABILITY_QUALITY_DIR,
        REPORTS_OBSERVABILITY_DIR,
        LAKE_PROCESSED_DIR,
        LAKE_PROCESSED_OHLCV_DIR,
        LAKE_QUALITY_REPORTS_DIR,
        LAKE_CLEANING_REPORTS_DIR,
        LAKE_FEATURES_DIR,
        LAKE_FEATURES_TECHNICAL_DIR,
        LAKE_FEATURES_MOMENTUM_DIR,
        LAKE_FEATURES_MOMENTUM_EVENTS_DIR,
        LAKE_FEATURES_MANIFESTS_DIR,
        LAKE_FEATURES_REPORTS_DIR,
        INDICATOR_REPORTS_DIR,
        MOMENTUM_REPORTS_DIR,
        LAKE_FEATURES_TREND_DIR,
        LAKE_FEATURES_TREND_EVENTS_DIR,
        LAKE_FEATURES_TREND_EVENTS_DIR,
        TREND_REPORTS_DIR,
        LAKE_FEATURES_VOLATILITY_DIR,
        LAKE_FEATURES_VOLATILITY_EVENTS_DIR,
        VOLATILITY_REPORTS_DIR,
        LAKE_FEATURES_PRICE_ACTION_DIR,
        LAKE_FEATURES_PRICE_ACTION_EVENTS_DIR,
        PRICE_ACTION_REPORTS_DIR,
        LAKE_FEATURES_DIVERGENCE_DIR,
        LAKE_FEATURES_DIVERGENCE_EVENTS_DIR,
        DIVERGENCE_REPORTS_DIR,
        LAKE_FEATURES_MTF_DIR,
        LAKE_FEATURES_MTF_EVENTS_DIR,
        MTF_REPORTS_DIR,
        LAKE_FEATURES_REGIME_DIR,
        LAKE_FEATURES_REGIME_EVENTS_DIR,
        REGIME_REPORTS_DIR,
        LAKE_MACRO_RAW_DIR,
        LAKE_MACRO_PROCESSED_DIR,
        LAKE_BENCHMARKS_DIR,
        LAKE_FEATURES_MACRO_DIR,
        LAKE_FEATURES_MACRO_EVENTS_DIR,
        LAKE_FEATURES_BENCHMARKS_DIR,
        MACRO_REPORTS_DIR,
        LAKE_TMP_DIR,
        LAKE_FEATURES_ASSET_PROFILES_DIR,
        LAKE_FEATURES_ASSET_PROFILE_EVENTS_DIR,
        LAKE_FEATURES_GROUP_FEATURES_DIR,
        ASSET_PROFILE_REPORTS_DIR,
        LAKE_FEATURES_SIGNAL_CANDIDATES_DIR,
        LAKE_FEATURES_SIGNAL_POOL_DIR,
        SIGNAL_REPORTS_DIR,
        LAKE_FEATURES_DECISION_CANDIDATES_DIR,
        LAKE_FEATURES_DECISION_POOL_DIR,
        DECISION_REPORTS_DIR,
        LAKE_FEATURES_STRATEGY_CANDIDATES_DIR,
        LAKE_FEATURES_STRATEGY_POOL_DIR,
        STRATEGY_REPORTS_DIR,
        LAKE_FEATURES_STRATEGY_RULE_CANDIDATES_DIR,
        LAKE_FEATURES_ENTRY_EXIT_CANDIDATES_DIR,
        LAKE_FEATURES_STRATEGY_RULE_POOL_DIR,
        REPORTS_RISK_REPORTS_DIR,
        LAKE_FEATURES_RISK_CANDIDATES_DIR,
        LAKE_FEATURES_RISK_POOL_DIR,
        STRATEGY_RULE_REPORTS_DIR,
        REPORTS_SIZING_REPORTS_DIR,
        LAKE_FEATURES_SIZING_CANDIDATES_DIR,
        LAKE_FEATURES_SIZING_POOL_DIR,
        LAKE_FEATURES_LEVEL_CANDIDATES_DIR,
        LAKE_FEATURES_LEVEL_POOL_DIR,
        REPORTS_LEVEL_REPORTS_DIR,
        LAKE_DIR / "backtests",
        LAKE_DIR / "backtests" / "runs",
        LAKE_DIR / "backtests" / "trades",
        LAKE_DIR / "backtests" / "equity_curves",
        LAKE_DIR / "backtests" / "audits",
        REPORTS_DIR / "backtest_reports",
        LAKE_ML_DIR,
        LAKE_ML_FEATURES_DIR,
        LAKE_ML_TARGETS_DIR,
        LAKE_ML_DATASETS_DIR,
        LAKE_ML_SPLITS_DIR,
        LAKE_ML_METADATA_DIR,
        LAKE_ML_QUALITY_DIR,
        LAKE_ML_MODELS_DIR,
        LAKE_ML_MODEL_ARTIFACTS_DIR,
        LAKE_ML_MODEL_REGISTRY_DIR,
        LAKE_ML_MODEL_EVALUATIONS_DIR,
        LAKE_ML_MODEL_CV_DIR,
        LAKE_ML_MODEL_QUALITY_DIR,
        REPORTS_ML_TRAINING_REPORTS_DIR,
        REPORTS_ML_REPORTS_DIR,
        LAKE_ML_INTEGRATION_DIR,
        LAKE_ML_INTEGRATION_FEATURES_DIR,
        LAKE_ML_INTEGRATION_ALIGNMENT_DIR,
        LAKE_ML_INTEGRATION_CONFLICTS_DIR,
        LAKE_ML_INTEGRATION_QUALITY_DIR,
        REPORTS_ML_INTEGRATION_REPORTS_DIR,
        LAKE_PAPER_DIR,
        LAKE_PAPER_RUNS_DIR,
        LAKE_PAPER_ORDERS_DIR,
        LAKE_PAPER_ORDER_BOOKS_DIR,
        LAKE_PAPER_POSITIONS_DIR,
        LAKE_PAPER_PORTFOLIOS_DIR,
        LAKE_PAPER_LEDGERS_DIR,
        LAKE_PAPER_EQUITY_CURVES_DIR,
        LAKE_PAPER_AUDITS_DIR,
        LAKE_PAPER_QUALITY_DIR,
        PAPER_REPORTS_DIR,
        LAKE_NOTIFICATIONS_DIR,
        LAKE_NOTIFICATIONS_MESSAGES_DIR,
        LAKE_NOTIFICATIONS_DELIVERY_LOGS_DIR,
        LAKE_NOTIFICATIONS_AUDITS_DIR,
        LAKE_NOTIFICATIONS_QUALITY_DIR,
        NOTIFICATION_REPORT_OUTPUT_DIR,
    LAKE_ORCHESTRATION_DIR,
    LAKE_ORCHESTRATION_RUNS_DIR,
    LAKE_ORCHESTRATION_MANIFESTS_DIR,
    LAKE_ORCHESTRATION_DEPENDENCY_GRAPHS_DIR,

    LAKE_ORCHESTRATION_EXECUTION_PLANS_DIR,
    LAKE_ORCHESTRATION_JOB_LOGS_DIR,
    LAKE_ORCHESTRATION_QUALITY_DIR,
    ORCHESTRATION_REPORT_OUTPUT_DIR,
    LAKE_SECURITY_DIR,
    LAKE_SECURITY_AUDITS_DIR,
    LAKE_SECURITY_SECRET_HYGIENE_DIR,
    LAKE_SECURITY_CONFIG_HARDENING_DIR,
    LAKE_SECURITY_SAFE_DEFAULTS_DIR,
    LAKE_SECURITY_PERMISSIONS_DIR,
    LAKE_SECURITY_PATH_SAFETY_DIR,
    LAKE_SECURITY_TOKEN_SCANS_DIR,
    LAKE_SECURITY_READINESS_DIR,
    LAKE_SECURITY_QUALITY_DIR,
    REPORTS_SECURITY_REPORTS_DIR,
    ]


    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)


# Risk Reports directories
REPORTS_RISK_REPORTS_DIR = REPORTS_DIR / "risk_reports"


# Risk Data Lake directories
LAKE_FEATURES_RISK_CANDIDATES_DIR = LAKE_FEATURES_DIR / "risk_candidates"
LAKE_FEATURES_RISK_POOL_DIR = LAKE_FEATURES_DIR / "risk_pool"

# Sizing Reports
REPORTS_SIZING_REPORTS_DIR = REPORTS_DIR / "sizing_reports"

# Sizing Data Lake directories
LAKE_FEATURES_SIZING_CANDIDATES_DIR = LAKE_FEATURES_DIR / "sizing_candidates"
LAKE_FEATURES_SIZING_POOL_DIR = LAKE_FEATURES_DIR / "sizing_pool"
LAKE_FEATURES_LEVEL_CANDIDATES_DIR = LAKE_FEATURES_DIR / "level_candidates"
LAKE_FEATURES_LEVEL_POOL_DIR = LAKE_FEATURES_DIR / "level_pool"

REPORTS_LEVEL_REPORTS_DIR = REPORTS_DIR / "level_reports"



# Phase 43: Synthetic Indices
LAKE_SYNTHETIC_INDICES_DIR = LAKE_DIR / "synthetic_indices"
LAKE_SYNTHETIC_INDICES_DEFINITIONS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "definitions"
LAKE_SYNTHETIC_INDICES_LEVELS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "levels"
LAKE_SYNTHETIC_INDICES_RETURNS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "returns"
LAKE_SYNTHETIC_INDICES_RELATIVE_STRENGTH_DIR = LAKE_SYNTHETIC_INDICES_DIR / "relative_strength"
LAKE_SYNTHETIC_INDICES_RELATIVE_MOMENTUM_DIR = LAKE_SYNTHETIC_INDICES_DIR / "relative_momentum"
LAKE_SYNTHETIC_INDICES_ROTATION_DIR = LAKE_SYNTHETIC_INDICES_DIR / "rotation"
LAKE_SYNTHETIC_INDICES_LEADERSHIP_DIR = LAKE_SYNTHETIC_INDICES_DIR / "leadership"
LAKE_SYNTHETIC_INDICES_COMPARISONS_DIR = LAKE_SYNTHETIC_INDICES_DIR / "comparisons"
LAKE_SYNTHETIC_INDICES_PERFORMANCE_DIR = LAKE_SYNTHETIC_INDICES_DIR / "performance"
LAKE_SYNTHETIC_INDICES_QUALITY_DIR = LAKE_SYNTHETIC_INDICES_DIR / "quality"

REPORTS_SYNTHETIC_INDICES_DIR = REPORTS_DIR / "synthetic_indices"
REPORTS_SYNTHETIC_INDICES_CSV_DIR = REPORTS_SYNTHETIC_INDICES_DIR / "csv"
REPORTS_SYNTHETIC_INDICES_MARKDOWN_DIR = REPORTS_SYNTHETIC_INDICES_DIR / "markdown"
REPORTS_SYNTHETIC_INDICES_TXT_DIR = REPORTS_SYNTHETIC_INDICES_DIR / "txt"


# Phase 44: Factor Research
LAKE_FACTOR_RESEARCH_DIR = LAKE_DIR / "factor_research"
LAKE_FACTOR_RESEARCH_DEFINITIONS_DIR = LAKE_FACTOR_RESEARCH_DIR / "definitions"
LAKE_FACTOR_RESEARCH_SCORES_DIR = LAKE_FACTOR_RESEARCH_DIR / "scores"
LAKE_FACTOR_RESEARCH_RANKS_DIR = LAKE_FACTOR_RESEARCH_DIR / "ranks"
LAKE_FACTOR_RESEARCH_BACKTESTS_DIR = LAKE_FACTOR_RESEARCH_DIR / "backtests"
LAKE_FACTOR_RESEARCH_IC_DIR = LAKE_FACTOR_RESEARCH_DIR / "ic"
LAKE_FACTOR_RESEARCH_STABILITY_DIR = LAKE_FACTOR_RESEARCH_DIR / "stability"
LAKE_FACTOR_RESEARCH_EXPOSURE_DIR = LAKE_FACTOR_RESEARCH_DIR / "exposure"
LAKE_FACTOR_RESEARCH_NEUTRALIZATION_DIR = LAKE_FACTOR_RESEARCH_DIR / "neutralization"
LAKE_FACTOR_RESEARCH_REPORTS_DIR = LAKE_FACTOR_RESEARCH_DIR / "reports"

# Phase 45: Meta Research
LAKE_META_RESEARCH_DIR = LAKE_DIR / "meta_research"
LAKE_META_RESEARCH_EVIDENCE_DIR = LAKE_META_RESEARCH_DIR / "evidence"
LAKE_META_RESEARCH_RELIABILITY_DIR = LAKE_META_RESEARCH_DIR / "reliability"
LAKE_META_RESEARCH_CONSENSUS_DIR = LAKE_META_RESEARCH_DIR / "consensus"
LAKE_META_RESEARCH_CONFLICTS_DIR = LAKE_META_RESEARCH_DIR / "conflicts"
LAKE_META_RESEARCH_UNCERTAINTY_DIR = LAKE_META_RESEARCH_DIR / "uncertainty"
LAKE_META_RESEARCH_ENSEMBLE_DIR = LAKE_META_RESEARCH_DIR / "ensemble"
LAKE_META_RESEARCH_RANKINGS_DIR = LAKE_META_RESEARCH_DIR / "rankings"
LAKE_META_RESEARCH_SNAPSHOTS_DIR = LAKE_META_RESEARCH_DIR / "snapshots"
LAKE_META_RESEARCH_REPORTS_DIR = LAKE_META_RESEARCH_DIR / "reports"
LAKE_META_RESEARCH_QUALITY_DIR = LAKE_META_RESEARCH_DIR / "quality"
LAKE_FACTOR_RESEARCH_QUALITY_DIR = LAKE_FACTOR_RESEARCH_DIR / "quality"

REPORTS_FACTOR_RESEARCH_DIR = REPORTS_DIR / "factor_research"
REPORTS_FACTOR_RESEARCH_CSV_DIR = REPORTS_FACTOR_RESEARCH_DIR / "csv"
REPORTS_FACTOR_RESEARCH_MARKDOWN_DIR = REPORTS_FACTOR_RESEARCH_DIR / "markdown"
REPORTS_FACTOR_RESEARCH_TXT_DIR = REPORTS_FACTOR_RESEARCH_DIR / "txt"


# Phase 46: Experiment Tracking
LAKE_EXPERIMENTS_DIR = LAKE_DIR / "experiments"
LAKE_EXPERIMENTS_HYPOTHESES_DIR = LAKE_EXPERIMENTS_DIR / "hypotheses"
LAKE_EXPERIMENTS_DEFINITIONS_DIR = LAKE_EXPERIMENTS_DIR / "definitions"
LAKE_EXPERIMENTS_RUNS_DIR = LAKE_EXPERIMENTS_DIR / "runs"
LAKE_EXPERIMENTS_ARTIFACTS_DIR = LAKE_EXPERIMENTS_DIR / "artifacts"
LAKE_EXPERIMENTS_REPRODUCIBILITY_DIR = LAKE_EXPERIMENTS_DIR / "reproducibility"
LAKE_EXPERIMENTS_VERSIONS_DIR = LAKE_EXPERIMENTS_DIR / "versions"
LAKE_EXPERIMENTS_ABLATION_DIR = LAKE_EXPERIMENTS_DIR / "ablation"
LAKE_EXPERIMENTS_COMPARISONS_DIR = LAKE_EXPERIMENTS_DIR / "comparisons"
LAKE_EXPERIMENTS_LEADERBOARDS_DIR = LAKE_EXPERIMENTS_DIR / "leaderboards"
LAKE_EXPERIMENTS_QUALITY_DIR = LAKE_EXPERIMENTS_DIR / "quality"

REPORTS_EXPERIMENTS_DIR = REPORTS_DIR / "experiments"
REPORTS_EXPERIMENTS_CSV_DIR = REPORTS_EXPERIMENTS_DIR / "csv"
REPORTS_EXPERIMENTS_MARKDOWN_DIR = REPORTS_EXPERIMENTS_DIR / "markdown"
REPORTS_EXPERIMENTS_TXT_DIR = REPORTS_EXPERIMENTS_DIR / "txt"
REPORTS_EXPERIMENTS_JSON_DIR = REPORTS_EXPERIMENTS_DIR / "json"

class ProjectPaths:

    def __init__(self):

        self.experiments_dir = LAKE_EXPERIMENTS_DIR
        self.experiments_hypotheses = LAKE_EXPERIMENTS_HYPOTHESES_DIR
        self.experiments_definitions = LAKE_EXPERIMENTS_DEFINITIONS_DIR
        self.experiments_runs = LAKE_EXPERIMENTS_RUNS_DIR
        self.experiments_artifacts = LAKE_EXPERIMENTS_ARTIFACTS_DIR
        self.experiments_reproducibility = LAKE_EXPERIMENTS_REPRODUCIBILITY_DIR
        self.experiments_versions = LAKE_EXPERIMENTS_VERSIONS_DIR
        self.experiments_ablation = LAKE_EXPERIMENTS_ABLATION_DIR
        self.experiments_comparisons = LAKE_EXPERIMENTS_COMPARISONS_DIR
        self.experiments_leaderboards = LAKE_EXPERIMENTS_LEADERBOARDS_DIR
        self.experiments_quality = LAKE_EXPERIMENTS_QUALITY_DIR

        self.experiments_reports = REPORTS_EXPERIMENTS_DIR
        self.experiments_reports_csv = REPORTS_EXPERIMENTS_CSV_DIR
        self.experiments_reports_markdown = REPORTS_EXPERIMENTS_MARKDOWN_DIR
        self.experiments_reports_txt = REPORTS_EXPERIMENTS_TXT_DIR
        self.experiments_reports_json = REPORTS_EXPERIMENTS_JSON_DIR

        self.project_root = PROJECT_ROOT
        self.data_dir = DATA_DIR
        self.lake_dir = LAKE_DIR
        self.backtests = LAKE_DIR / "backtests"
        self.backtest_runs = self.backtests / "runs"
        self.backtest_trades = self.backtests / "trades"
        self.backtest_equity_curves = self.backtests / "equity_curves"
        self.backtest_audits = self.backtests / "audits"
        self.backtest_reports = REPORTS_DIR / "backtest_reports"
        self.ml_dir = LAKE_ML_DIR
        self.ml_features = LAKE_ML_FEATURES_DIR
        self.ml_targets = LAKE_ML_TARGETS_DIR
        self.ml_datasets = LAKE_ML_DATASETS_DIR
        self.ml_splits = LAKE_ML_SPLITS_DIR
        self.ml_metadata = LAKE_ML_METADATA_DIR
        self.ml_quality = LAKE_ML_QUALITY_DIR
        self.ml_models = LAKE_ML_MODELS_DIR
        self.ml_model_artifacts = LAKE_ML_MODEL_ARTIFACTS_DIR
        self.ml_model_registry = LAKE_ML_MODEL_REGISTRY_DIR
        self.ml_model_evaluations = LAKE_ML_MODEL_EVALUATIONS_DIR
        self.ml_model_cv = LAKE_ML_MODEL_CV_DIR
        self.ml_model_quality = LAKE_ML_MODEL_QUALITY_DIR
        self.ml_training_reports = REPORTS_ML_TRAINING_REPORTS_DIR
        self.ml_reports = REPORTS_ML_REPORTS_DIR

        # Phase 32: ML Context Integration
        self.ml_integration = LAKE_ML_INTEGRATION_DIR
        self.ml_integration_features = LAKE_ML_INTEGRATION_FEATURES_DIR
        self.ml_integration_alignment = LAKE_ML_INTEGRATION_ALIGNMENT_DIR
        self.ml_integration_conflicts = LAKE_ML_INTEGRATION_CONFLICTS_DIR
        self.ml_integration_quality = LAKE_ML_INTEGRATION_QUALITY_DIR
        self.ml_integration_reports = REPORTS_ML_INTEGRATION_REPORTS_DIR

        # Phase 33: Paper Trading
        self.paper_dir = LAKE_PAPER_DIR
        self.paper_runs = LAKE_PAPER_RUNS_DIR
        self.paper_orders = LAKE_PAPER_ORDERS_DIR
        self.paper_order_books = LAKE_PAPER_ORDER_BOOKS_DIR
        self.paper_positions = LAKE_PAPER_POSITIONS_DIR
        self.paper_portfolios = LAKE_PAPER_PORTFOLIOS_DIR
        self.paper_ledgers = LAKE_PAPER_LEDGERS_DIR
        self.paper_equity_curves = LAKE_PAPER_EQUITY_CURVES_DIR
        self.paper_audits = LAKE_PAPER_AUDITS_DIR
        self.paper_quality = LAKE_PAPER_QUALITY_DIR
        self.paper_reports = PAPER_REPORTS_DIR


        # Phase 34: Notifications
        self.LAKE_NOTIFICATIONS_DIR = LAKE_NOTIFICATIONS_DIR
        self.LAKE_NOTIFICATIONS_MESSAGES_DIR = LAKE_NOTIFICATIONS_MESSAGES_DIR
        self.LAKE_NOTIFICATIONS_DELIVERY_LOGS_DIR = LAKE_NOTIFICATIONS_DELIVERY_LOGS_DIR
        self.LAKE_NOTIFICATIONS_AUDITS_DIR = LAKE_NOTIFICATIONS_AUDITS_DIR
        self.LAKE_NOTIFICATIONS_QUALITY_DIR = LAKE_NOTIFICATIONS_QUALITY_DIR
        self.NOTIFICATION_REPORT_OUTPUT_DIR = NOTIFICATION_REPORT_OUTPUT_DIR

        # Phase 37: Security
        self.security_dir = LAKE_SECURITY_DIR
        self.security_audits = LAKE_SECURITY_AUDITS_DIR
        self.security_secret_hygiene = LAKE_SECURITY_SECRET_HYGIENE_DIR
        self.security_config_hardening = LAKE_SECURITY_CONFIG_HARDENING_DIR
        self.security_safe_defaults = LAKE_SECURITY_SAFE_DEFAULTS_DIR
        self.security_permissions = LAKE_SECURITY_PERMISSIONS_DIR
        self.security_path_safety = LAKE_SECURITY_PATH_SAFETY_DIR
        self.security_token_scans = LAKE_SECURITY_TOKEN_SCANS_DIR
        self.security_readiness = LAKE_SECURITY_READINESS_DIR
        self.security_quality = LAKE_SECURITY_QUALITY_DIR
        self.security_reports = REPORTS_SECURITY_REPORTS_DIR


        # Phase 42: Portfolio Regime Research
        self.portfolio_regime_dir = LAKE_PORTFOLIO_REGIME_DIR
        self.portfolio_regime_regimes = LAKE_PORTFOLIO_REGIME_REGIMES_DIR
        self.portfolio_regime_conditioned_returns = LAKE_PORTFOLIO_REGIME_CONDITIONED_RETURNS_DIR
        self.portfolio_regime_correlation = LAKE_PORTFOLIO_REGIME_CORRELATION_DIR
        self.portfolio_regime_scenarios = LAKE_PORTFOLIO_REGIME_SCENARIOS_DIR
        self.portfolio_regime_stress_tests = LAKE_PORTFOLIO_REGIME_STRESS_TESTS_DIR
        self.portfolio_regime_drawdowns = LAKE_PORTFOLIO_REGIME_DRAWDOWNS_DIR
        self.portfolio_regime_recovery = LAKE_PORTFOLIO_REGIME_RECOVERY_DIR
        self.portfolio_regime_tail_risk = LAKE_PORTFOLIO_REGIME_TAIL_RISK_DIR
        self.portfolio_regime_exposure = LAKE_PORTFOLIO_REGIME_EXPOSURE_DIR
        self.portfolio_regime_quality = LAKE_PORTFOLIO_REGIME_QUALITY_DIR

        self.portfolio_regime_reports = REPORTS_PORTFOLIO_REGIME_DIR

        # Phase 43: Synthetic Indices
        self.synthetic_indices_dir = LAKE_SYNTHETIC_INDICES_DIR
        self.synthetic_indices_definitions = LAKE_SYNTHETIC_INDICES_DEFINITIONS_DIR
        self.synthetic_indices_levels = LAKE_SYNTHETIC_INDICES_LEVELS_DIR
        self.synthetic_indices_returns = LAKE_SYNTHETIC_INDICES_RETURNS_DIR
        self.synthetic_indices_relative_strength = LAKE_SYNTHETIC_INDICES_RELATIVE_STRENGTH_DIR
        self.synthetic_indices_relative_momentum = LAKE_SYNTHETIC_INDICES_RELATIVE_MOMENTUM_DIR
        self.synthetic_indices_rotation = LAKE_SYNTHETIC_INDICES_ROTATION_DIR
        self.synthetic_indices_leadership = LAKE_SYNTHETIC_INDICES_LEADERSHIP_DIR
        self.synthetic_indices_comparisons = LAKE_SYNTHETIC_INDICES_COMPARISONS_DIR
        self.synthetic_indices_performance = LAKE_SYNTHETIC_INDICES_PERFORMANCE_DIR
        self.synthetic_indices_quality = LAKE_SYNTHETIC_INDICES_QUALITY_DIR
        self.synthetic_indices_reports = REPORTS_SYNTHETIC_INDICES_DIR
        self.synthetic_indices_reports_csv = REPORTS_SYNTHETIC_INDICES_CSV_DIR
        self.synthetic_indices_reports_markdown = REPORTS_SYNTHETIC_INDICES_MARKDOWN_DIR
        self.synthetic_indices_reports_txt = REPORTS_SYNTHETIC_INDICES_TXT_DIR

        # Phase 44: Factor Research
        self.factor_research_dir = LAKE_FACTOR_RESEARCH_DIR
        self.factor_research_definitions = LAKE_FACTOR_RESEARCH_DEFINITIONS_DIR
        self.factor_research_scores = LAKE_FACTOR_RESEARCH_SCORES_DIR
        self.factor_research_ranks = LAKE_FACTOR_RESEARCH_RANKS_DIR
        self.factor_research_backtests = LAKE_FACTOR_RESEARCH_BACKTESTS_DIR
        self.factor_research_ic = LAKE_FACTOR_RESEARCH_IC_DIR
        self.factor_research_stability = LAKE_FACTOR_RESEARCH_STABILITY_DIR
        self.factor_research_exposure = LAKE_FACTOR_RESEARCH_EXPOSURE_DIR
        self.factor_research_neutralization = LAKE_FACTOR_RESEARCH_NEUTRALIZATION_DIR
        self.factor_research_quality = LAKE_FACTOR_RESEARCH_QUALITY_DIR
        self.factor_research_lake_reports = LAKE_FACTOR_RESEARCH_REPORTS_DIR

        self.factor_research_reports = REPORTS_FACTOR_RESEARCH_DIR
        self.factor_research_reports_csv = REPORTS_FACTOR_RESEARCH_CSV_DIR
        self.factor_research_reports_markdown = REPORTS_FACTOR_RESEARCH_MARKDOWN_DIR
        self.factor_research_reports_txt = REPORTS_FACTOR_RESEARCH_TXT_DIR




# Phase 39: Research Reports
LAKE_RESEARCH_REPORTS_DIR = LAKE_DIR / "research_reports"
LAKE_RESEARCH_REPORTS_SYMBOL_DIR = LAKE_RESEARCH_REPORTS_DIR / "symbol"
LAKE_RESEARCH_REPORTS_UNIVERSE_DIR = LAKE_RESEARCH_REPORTS_DIR / "universe"
LAKE_RESEARCH_REPORTS_DAILY_DIGEST_DIR = LAKE_RESEARCH_REPORTS_DIR / "daily_digest"
LAKE_RESEARCH_REPORTS_RANKINGS_DIR = LAKE_RESEARCH_REPORTS_DIR / "rankings"
LAKE_RESEARCH_REPORTS_TABLES_DIR = LAKE_RESEARCH_REPORTS_DIR / "tables"
LAKE_RESEARCH_REPORTS_QUALITY_DIR = LAKE_RESEARCH_REPORTS_DIR / "quality"
REPORTS_RESEARCH_REPORTS_DIR = REPORTS_DIR / "research_reports"
REPORTS_RESEARCH_REPORTS_MARKDOWN_DIR = REPORTS_RESEARCH_REPORTS_DIR / "markdown"
REPORTS_RESEARCH_REPORTS_CSV_DIR = REPORTS_RESEARCH_REPORTS_DIR / "csv"
REPORTS_RESEARCH_REPORTS_TXT_DIR = REPORTS_RESEARCH_REPORTS_DIR / "txt"
