# -*- coding: utf-8 -*-
"""Phase 156: Portfolio Scenario Testing and Drawdown Control Labels."""


class ContractStatus:
    CONTRACT_ONLY = "CONTRACT_ONLY"
    DRY_RUN = "DRY_RUN"
    DISABLED = "DISABLED"
    READY = "READY"
    PASS = "PASS"
    FAIL = "FAIL"
    SATISFIED = "SATISFIED"
    UNSATISFIED = "UNSATISFIED"
    PROHIBITED = "PROHIBITED"
    ACTIVE = "ACTIVE"
    MONITORING = "MONITORING"
    INITIALIZED = "INITIALIZED"


class ScenarioType:
    HISTORICAL_CRISIS = "HISTORICAL_CRISIS"
    HYPOTHETICAL_SHOCK = "HYPOTHETICAL_SHOCK"
    REGIME_SHIFT = "REGIME_SHIFT"
    VOLATILITY_SPIKE = "VOLATILITY_SPIKE"
    LIQUIDITY_CRUNCH = "LIQUIDITY_CRUNCH"
    CORRELATION_BREAKDOWN = "CORRELATION_BREAKDOWN"
    CURRENCY_SHOCK = "CURRENCY_SHOCK"
    SPREAD_WIDENING = "SPREAD_WIDENING"
    TRANSACTION_COST_SHOCK = "TRANSACTION_COST_SHOCK"
    SLIPPAGE_SHOCK = "SLIPPAGE_SHOCK"


class DrawdownTier:
    NORMAL = "NORMAL"
    WARNING = "WARNING"
    ELEVATED = "ELEVATED"
    BREACH = "BREACH"
    CRITICAL = "CRITICAL"
    RECOVERY = "RECOVERY"


class ControlActionType:
    EXPOSURE_REDUCTION = "EXPOSURE_REDUCTION"
    DE_RISKING = "DE_RISKING"
    HEDGE_CONTROL = "HEDGE_CONTROL"
    REBALANCE_CONTROL = "REBALANCE_CONTROL"
    STOP_CONTROL = "STOP_CONTROL"
    FREEZE_CONTROL = "FREEZE_CONTROL"
    RESUME_CONTROL = "RESUME_CONTROL"
    RECOVERY_PLAN = "RECOVERY_PLAN"


class GuardType:
    NO_LOOKAHEAD = "NO_LOOKAHEAD"
    EXECUTION_CLAIM = "EXECUTION_CLAIM"
    DRAWDOWN_CLAIM = "DRAWDOWN_CLAIM"
    PORTFOLIO_ADJUSTMENT_CLAIM = "PORTFOLIO_ADJUSTMENT_CLAIM"
    HEDGE_DERISK_CLAIM = "HEDGE_DERISK_CLAIM"
    REBALANCE_CONTROL_CLAIM = "REBALANCE_CONTROL_CLAIM"
    INVESTMENT_ADVICE = "INVESTMENT_ADVICE"
    SCENARIO_ALERT = "SCENARIO_ALERT"
    DATA_SNOOPING_BIAS = "DATA_SNOOPING_BIAS"
    OVERFITTING = "OVERFITTING"
    MULTIPLE_TESTING = "MULTIPLE_TESTING"
    METADATA_ONLY_NEWS = "METADATA_ONLY_NEWS"
    SOURCE_PRESERVATION = "SOURCE_PRESERVATION"
    FORBIDDEN_COLUMN = "FORBIDDEN_COLUMN"
