# -*- coding: utf-8 -*-
"""Phase 157: Portfolio Acceptance Labels.

Standardized domain labels, status labels, and boundary identifiers for Phase 157.
"""

# Domain Labels
PORTFOLIO_ACCEPTANCE_PROFILE_DOMAIN = "portfolio_acceptance_profile_domain"
PORTFOLIO_ACCEPTANCE_DOMAIN = "portfolio_acceptance_domain"
PORTFOLIO_ACCEPTANCE_SCOPE_DOMAIN = "portfolio_acceptance_scope_domain"
COMPONENT_REGISTRY_DOMAIN = "component_registry_domain"
COMPONENT_CHECKPOINT_DOMAIN = "component_checkpoint_domain"
PHASE_153_PORTFOLIO_CONSTRUCTION_ACCEPTANCE_DOMAIN = "phase_153_portfolio_construction_acceptance_domain"
PHASE_154_PORTFOLIO_OPTIMIZATION_ACCEPTANCE_DOMAIN = "phase_154_portfolio_optimization_acceptance_domain"
PHASE_155_RISK_REPORTING_ACCEPTANCE_DOMAIN = "phase_155_risk_reporting_acceptance_domain"
PHASE_156_PORTFOLIO_SCENARIO_CONTROL_ACCEPTANCE_DOMAIN = "phase_156_portfolio_scenario_control_acceptance_domain"
DEPENDENCY_ACCEPTANCE_DOMAIN = "dependency_acceptance_domain"
VALIDATION_EVIDENCE_DOMAIN = "validation_evidence_domain"
SAFETY_BOUNDARY_DOMAIN = "safety_boundary_domain"
NON_PRODUCTION_BOUNDARY_DOMAIN = "non_production_boundary_domain"
MANUAL_REVIEW_GATE_DOMAIN = "manual_review_gate_domain"
GO_NO_GO_BOUNDARY_DOMAIN = "go_no_go_boundary_domain"
BLOCKER_DOMAIN = "blocker_domain"
GAP_DOMAIN = "gap_domain"
WARNING_DOMAIN = "warning_domain"
FINDING_DOMAIN = "finding_domain"
READINESS_SCORE_DOMAIN = "readiness_score_domain"
MANIFEST_DOMAIN = "manifest_domain"
HEALTH_DOMAIN = "health_domain"
VALIDATION_DOMAIN = "validation_domain"
SAFETY_DOMAIN = "safety_domain"
PHASE_158_HANDOFF_DOMAIN = "phase_158_handoff_domain"

# Status Labels
PORTFOLIO_ACCEPTANCE_READY = "portfolio_acceptance_ready"
PORTFOLIO_ACCEPTANCE_READY_WITH_WARNINGS = "portfolio_acceptance_ready_with_warnings"
PORTFOLIO_ACCEPTANCE_MANUAL_REVIEW_REQUIRED = "portfolio_acceptance_manual_review_required"
PORTFOLIO_ACCEPTANCE_BLOCKED_BY_SAFETY = "portfolio_acceptance_blocked_by_safety"
PORTFOLIO_ACCEPTANCE_MISSING_DEPENDENCY = "portfolio_acceptance_missing_dependency"
PORTFOLIO_ACCEPTANCE_CONTRACT_ONLY = "portfolio_acceptance_contract_only"
PORTFOLIO_ACCEPTANCE_UNKNOWN = "portfolio_acceptance_unknown"

# Boundary Labels
GO_CONTRACT_ONLY = "go_contract_only"
NO_GO_LIVE_TRADING = "no_go_live_trading"
NO_GO_BROKER_EXECUTION = "no_go_broker_execution"
NO_GO_INVESTMENT_ADVICE = "no_go_investment_advice"
NO_GO_SIGNAL_GENERATION = "no_go_signal_generation"
NO_GO_PORTFOLIO_CONSTRUCTION = "no_go_portfolio_construction"
NO_GO_POSITION_SIZING = "no_go_position_sizing"
NO_GO_PORTFOLIO_OPTIMIZATION = "no_go_portfolio_optimization"
NO_GO_ALLOCATION = "no_go_allocation"
NO_GO_REBALANCE = "no_go_rebalance"
NO_GO_ORDER_GENERATION = "no_go_order_generation"
NO_GO_RISK_REPORTING = "no_go_risk_reporting"
NO_GO_LIMIT_MONITORING = "no_go_limit_monitoring"
NO_GO_SCENARIO_EXECUTION = "no_go_scenario_execution"
NO_GO_DRAWDOWN_CONTROL = "no_go_drawdown_control"
NO_GO_PORTFOLIO_ADJUSTMENT = "no_go_portfolio_adjustment"
NO_GO_HEDGE_DERISK = "no_go_hedge_derisk"
NO_GO_METRIC_CALCULATION = "no_go_metric_calculation"
NO_GO_MODEL_TRAINING = "no_go_model_training"
NO_GO_PREDICTION = "no_go_prediction"
NO_GO_DEPLOYMENT = "no_go_deployment"
NO_GO_UNKNOWN = "no_go_unknown"

# Severity Labels
SEVERITY_INFO = "info"
SEVERITY_WARNING = "warning"
SEVERITY_HIGH = "high"
SEVERITY_CRITICAL = "critical"
