# -*- coding: utf-8 -*-
"""Phase 160: Final Delivery Report Inventory.

Builds metadata inventory of output report formats (Markdown, TXT, CSV, JSON) generated by the system.
Does not delete, move, or modify any files.
"""

from typing import Dict, Tuple
import pandas as pd
from advanced_final_delivery.final_delivery_config import (
    FinalDeliveryProfile,
    get_default_final_delivery_profile,
)
from advanced_final_delivery.final_delivery_labels import (
    FINAL_INVENTORY_DOMAIN,
    FULL_ADVANCED_BOT_FINAL_DELIVERY_READY,
)

REPORT_OUTPUT_DIRECTORIES = [
    ("advanced_final_delivery", "Phase 160", "Final delivery manifest, system summary and handover reports"),
    ("advanced_final_hardening", "Phase 159", "Final hardening, freeze audit and release candidate reports"),
    ("advanced_full_system_integration", "Phase 158", "Full-system integration and acceptance rehearsal reports"),
    ("advanced_portfolio_acceptance", "Phase 157", "Portfolio acceptance consolidated reports"),
    ("advanced_portfolio_scenario_control", "Phase 156", "Portfolio scenario testing and drawdown control reports"),
    ("advanced_risk_reporting", "Phase 155", "Risk reporting and limit monitoring reports"),
    ("advanced_portfolio_optimization", "Phase 154", "Portfolio optimization and allocation reports"),
    ("advanced_portfolio_construction", "Phase 153", "Portfolio construction and sizing reports"),
    ("advanced_backtest_acceptance", "Phase 152", "Backtest acceptance consolidated reports"),
    ("advanced_monte_carlo_robustness", "Phase 151", "Monte Carlo robustness reports"),
    ("advanced_stress_testing", "Phase 150", "Historical and stress test reports"),
    ("advanced_benchmark_evaluation", "Phase 149", "Benchmark comparison reports"),
    ("advanced_walk_forward_validation", "Phase 148", "Walk-forward validation reports"),
    ("advanced_realistic_backtest", "Phase 146-147", "Realistic backtest execution reports"),
    ("advanced_ml_acceptance", "Phase 145", "ML acceptance consolidated reports"),
]


def build_final_delivery_report_inventory_registry(
    profile: FinalDeliveryProfile | None = None,
) -> Tuple[pd.DataFrame, Dict]:
    """Build report inventory DataFrame and summary."""
    active_profile = profile or get_default_final_delivery_profile()

    rows = []
    for out_name, p_range, desc in REPORT_OUTPUT_DIRECTORIES:
        rows.append({
            "report_directory": out_name,
            "phase_range": p_range,
            "description": desc,
            "supported_formats": "MD, TXT, CSV, JSON",
            "non_signal": True,
            "local_only": True,
            "dry_run": True,
            "non_production": True,
            "domain": FINAL_INVENTORY_DOMAIN,
            "status": FULL_ADVANCED_BOT_FINAL_DELIVERY_READY,
        })

    df = pd.DataFrame(rows)
    summary = {
        "active_profile": active_profile.profile_name,
        "report_directory_count": len(rows),
        "formats_supported": ["MD", "TXT", "CSV", "JSON"],
        "status": FULL_ADVANCED_BOT_FINAL_DELIVERY_READY,
    }
    return df, summary
