# -*- coding: utf-8 -*-
"""Phase 150: Backtest Governance and Bias Control Labels.

Defines standardized domain, status, and execution labels for Phase 150.
"""

# Domain labels
BACKTEST_GOVERNANCE_PROFILE_DOMAIN = "backtest_governance_profile_domain"
BACKTEST_GOVERNANCE_DOMAIN = "backtest_governance_domain"
BACKTEST_GOVERNANCE_SCOPE_DOMAIN = "backtest_governance_scope_domain"
GOVERNANCE_CONTRACT_DOMAIN = "governance_contract_domain"
BIAS_CONTROL_DOMAIN = "bias_control_domain"
RESULT_REPORTING_DOMAIN = "result_reporting_domain"
METRIC_CLAIM_BOUNDARY_DOMAIN = "metric_claim_boundary_domain"
PERFORMANCE_CLAIM_BOUNDARY_DOMAIN = "performance_claim_boundary_domain"
LOOKAHEAD_BIAS_DOMAIN = "lookahead_bias_domain"
SURVIVORSHIP_BIAS_DOMAIN = "survivorship_bias_domain"
DATA_SNOOPING_BIAS_DOMAIN = "data_snooping_bias_domain"
OVERFITTING_BIAS_DOMAIN = "overfitting_bias_domain"
MULTIPLE_TESTING_BIAS_DOMAIN = "multiple_testing_bias_domain"
PARAMETER_FISHING_BIAS_DOMAIN = "parameter_fishing_bias_domain"
BENCHMARK_SELECTION_BIAS_DOMAIN = "benchmark_selection_bias_domain"
REGIME_COVERAGE_BIAS_DOMAIN = "regime_coverage_bias_domain"
SAMPLE_COVERAGE_BIAS_DOMAIN = "sample_coverage_bias_domain"
REALISM_GOVERNANCE_DOMAIN = "realism_governance_domain"
SPLIT_GOVERNANCE_DOMAIN = "split_governance_domain"
WALK_FORWARD_GOVERNANCE_DOMAIN = "walk_forward_governance_domain"
OOS_GOVERNANCE_DOMAIN = "oos_governance_domain"
STRESS_GOVERNANCE_DOMAIN = "stress_governance_domain"
MONTE_CARLO_GOVERNANCE_DOMAIN = "monte_carlo_governance_domain"
BENCHMARK_GOVERNANCE_DOMAIN = "benchmark_governance_domain"
AUDIT_POLICY_DOMAIN = "audit_policy_domain"
EVIDENCE_POLICY_DOMAIN = "evidence_policy_domain"
MANUAL_REVIEW_GATE_DOMAIN = "manual_review_gate_domain"
GO_NO_GO_BOUNDARY_DOMAIN = "go_no_go_boundary_domain"
DISABLED_EXECUTION_DOMAIN = "disabled_execution_domain"
DEPENDENCY_DOMAIN = "dependency_domain"
FINDING_DOMAIN = "finding_domain"
READINESS_SCORE_DOMAIN = "readiness_score_domain"
MANIFEST_DOMAIN = "manifest_domain"
HEALTH_DOMAIN = "health_domain"
VALIDATION_DOMAIN = "validation_domain"
SAFETY_DOMAIN = "safety_domain"
PHASE_151_HANDOFF_DOMAIN = "phase_151_handoff_domain"

# Status labels
STATUS_GOVERNANCE_CONTRACT_READY = "governance_contract_ready"
STATUS_GOVERNANCE_CONTRACT_READY_WITH_WARNINGS = "governance_contract_ready_with_warnings"
STATUS_GOVERNANCE_CONTRACT_MANUAL_REVIEW_REQUIRED = "governance_contract_manual_review_required"
STATUS_GOVERNANCE_CONTRACT_BLOCKED_BY_SAFETY = "governance_contract_blocked_by_safety"
STATUS_GOVERNANCE_CONTRACT_ONLY = "governance_contract_only"
STATUS_GOVERNANCE_UNKNOWN = "governance_unknown"

# Execution labels
EXEC_BLOCKED_NO_BACKTEST = "execution_blocked_no_backtest"
EXEC_BLOCKED_NO_BENCHMARK = "execution_blocked_no_benchmark"
EXEC_BLOCKED_NO_METRIC_CALCULATION = "execution_blocked_no_metric_calculation"
EXEC_BLOCKED_NO_RESULT_CLAIM = "execution_blocked_no_result_claim"
EXEC_BLOCKED_NO_OPTIMIZER = "execution_blocked_no_optimizer"
EXEC_BLOCKED_NO_MODEL_TRAINING = "execution_blocked_no_model_training"
EXEC_BLOCKED_NO_PREDICTION = "execution_blocked_no_prediction"
EXEC_BLOCKED_NO_LIVE_TRADING = "execution_blocked_no_live_trading"
EXEC_BLOCKED_NO_BROKER = "execution_blocked_no_broker"
EXEC_BLOCKED_NO_DEPLOYMENT = "execution_blocked_no_deployment"
EXEC_CONTRACT_ONLY = "execution_contract_only"
