# -*- coding: utf-8 -*-
"""Phase 150: Backtest Governance and Bias Control Models.

Defines dataclasses for governance contracts, bias guards, claim boundaries,
findings, scores, manifests, and review items.
All models enforce non-signal, local-only, zero-execution invariants.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from datetime import datetime, timezone


@dataclass
class BacktestGovernanceProfileItem:
    """Represents an active backtest governance profile record."""

    profile_name: str
    description: str
    current_phase: int = 150
    target_final_phase: int = 160
    next_phase: int = 151
    dry_run: bool = True
    local_only: bool = True
    non_production: bool = True
    non_signal: bool = True
    allow_live_trading: bool = False
    allow_broker_integration: bool = False
    allow_real_order: bool = False
    allow_backtest_execution: bool = False
    allow_metric_calculation: bool = False
    allow_result_claim: bool = False
    allow_performance_claim: bool = False
    allow_strategy_approval: bool = False
    allow_optimizer_execution: bool = False
    allow_model_training: bool = False
    allow_model_predict: bool = False
    min_readiness_score: float = 0.50


@dataclass
class BacktestGovernanceContract:
    """Core backtest governance contract definition."""

    contract_name: str
    governance_family: str
    phase_146_ref: str
    phase_147_ref: str
    phase_148_ref: str
    phase_149_ref: str
    no_lookahead_guard_ref: str
    bias_control_ref: str
    result_claim_boundary_ref: str
    metric_claim_boundary_ref: str
    backtest_execution_allowed: bool = False
    benchmark_execution_allowed: bool = False
    metric_calculation_allowed: bool = False
    optimizer_execution_allowed: bool = False
    result_claim_allowed: bool = False
    performance_claim_allowed: bool = False
    live_trading_allowed: bool = False
    broker_execution_allowed: bool = False
    signal_generation_allowed: bool = False
    manual_review_required: bool = True
    non_signal: bool = True
    local_only: bool = True
    dry_run: bool = True
    non_production: bool = True


@dataclass
class BiasControlContract:
    """Contract for a specific bias control regime."""

    bias_type: str
    control_name: str
    detection_methodology: str
    mitigation_policy: str
    enforcement_level: str
    lookahead_free_verified: bool = True
    claim_blocked: bool = True
    execution_allowed: bool = False
    non_signal: bool = True
    local_only: bool = True


@dataclass
class ResultClaimBoundary:
    """Enforces strict boundaries against unverified result and metric claims."""

    boundary_name: str
    target_claim_type: str
    policy_description: str
    is_blocked: bool = True
    metric_calculation_allowed: bool = False
    result_claim_allowed: bool = False
    performance_claim_allowed: bool = False
    strategy_approval_allowed: bool = False
    non_signal: bool = True
    local_only: bool = True


@dataclass
class BiasGuardItem:
    """Safety guard definition against data and validation biases."""

    guard_name: str
    bias_category: str
    prohibited_action: str
    status: str = "ACTIVE"
    execution_blocked: bool = True
    claim_blocked: bool = True
    non_signal: bool = True
    local_only: bool = True


@dataclass
class BacktestGovernanceDisabledExecutionItem:
    """Record representing an intentionally disabled execution capability."""

    operation_name: str
    disabled_reason: str
    target_phase: int = 150
    execution_permitted: bool = False
    live_trading_permitted: bool = False
    broker_permitted: bool = False
    optimizer_permitted: bool = False
    metric_calc_permitted: bool = False
    non_signal: bool = True


@dataclass
class BacktestGovernanceFinding:
    """Finding or audit item generated by governance inspection."""

    finding_id: str
    finding_type: str
    domain: str
    severity_label: str
    message: str
    recommendation: str
    manual_review_required: bool = True
    auto_remediation_allowed: bool = False
    non_signal: bool = True


@dataclass
class BacktestGovernanceReadinessScore:
    """Calculated governance and bias-control readiness score."""

    score: float
    classification: str
    current_phase: int = 150
    target_final_phase: int = 160
    meets_threshold: bool = True
    non_signal: bool = True
    local_only: bool = True
    dry_run: bool = True
    non_production: bool = True
    broker_ready: bool = False
    production_ready: bool = False
    live_trading_ready: bool = False
    official_approval: bool = False
    contains_target_or_prediction: bool = False
    contains_trading_recommendation: bool = False

    def __post_init__(self):
        if not (0.0 <= self.score <= 1.0):
            raise ValueError(f"Readiness score must be between 0.0 and 1.0, got {self.score}")


@dataclass
class BacktestGovernanceManifest:
    """Formal Phase 150 Backtest Governance Manifest."""

    manifest_id: str
    current_phase: int = 150
    target_final_phase: int = 160
    next_phase: int = 151
    non_signal: bool = True
    local_only: bool = True
    dry_run: bool = True
    non_production: bool = True
    research_only: bool = True
    production_ready: bool = False
    broker_ready: bool = False
    live_trading_ready: bool = False
    official_approval: bool = False
    backtest_executed: bool = False
    benchmark_executed: bool = False
    metric_calculated: bool = False
    result_claim_generated: bool = False
    performance_claim_generated: bool = False
    strategy_approved: bool = False
    optimizer_executed: bool = False
    model_training_executed: bool = False
    prediction_generated: bool = False
    target_label_generated: bool = False
    broker_order_sent: bool = False
    live_order_sent: bool = False
    artifact_persisted: bool = False
    model_registry_written: bool = False
    model_deployed: bool = False
    production_deployed: bool = False
    source_preserved: bool = True
    manual_review_required: bool = True
    phase_151_handoff_ready: bool = True
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class BacktestGovernanceManualReviewItem:
    """Manual review queue item for human governance oversight."""

    review_id: str
    title: str
    category: str
    description: str
    manual_action_required: str
    status: str = "PENDING_MANUAL_REVIEW"
    auto_approval_allowed: bool = False
    non_signal: bool = True
